### ISSUE TITLE
Doesn't display all pulseaudio input sources (limits 5 first)

### ISSUE THREAD

**Issue by olberger** [vkohaupt/vokoscreen#103]
Hi.

It seems to me that only the 5 first input sources are displayed in the list of Pulse devices.

See my report in Debian BTS:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=783626

Im puzzled, because, I can't spot anything weird even under debugger. Maybe a Qt limitation ?

Thanks in advance.

**Comment by vkohaupt** [comment]
Olivier Berger schrieb am 28.04.2015 um 17:55:
> Hi.
>
> It seems to me that only the 5 first input sources are displayed in the list of Pulse devices.
>
> See my report in Debian BTS:
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=783626
>
> Im puzzled, because, I can't spot anything weird even under debugger. Maybe a Qt limitation ?

1.
Please go into a terminal and give me the
complete output from "pactl list"

2.
And then give me the complete terminal output from vokoscreen.


I´m understand right, you see only five source in the list?


Thanks

**Comment by olberger** [comment]
I'm sorry, I no longer have the device I've plugged in at the moment, so the list of pulse audio sources is currently only 4 elements and not 6 as it was yesterday.

I have internal Mic, USB webcam's and an external USB Microphone (ideal setup for DIY screencast recording, AFAICT ;), each resulting in one direct source and one monitor, I think.

Anyway, there are sources numbered Source #0 to Source #5, but the list only produces 5 tickable input sources in the UI.

The debug log however produces 6 lines for CaptureCard (IIRC) devices.

I've recompiled with debug option and stepped through the code with ddd, and there were indeed 6 loops of adding the checkboxes in the frame... so my understanding is that there's a bug wrt Qt widgets maybe...

Hope this helps, until I can provide the logs when I have the hardware at hand.

**Comment by olberger** [comment]
FYI, the easiest workaround I've found is to plug the microphone before the webcam, so that the order of devices brings the microphone first in the list.

On a side note, maybe it isn't optimal to use pactl's default output, and "pactl list short" could be better to be parsed. Also, "pactl list source" would be more straightforward, I guess.

**Comment by vkohaupt** [comment]
I have emulate nine device and see that vokoscreen only five devices 
displaying, look code and found the bug.
Thanks four your help

**Comment by vkohaupt** [comment]
fixed in 2.3.1-beta

**Comment by olberger** [comment]
I confirm this is a fix. Thanks :-)
