### ISSUE TITLE
 qmake error & libs in centos 6 x86 

### ISSUE THREAD

**Issue by mariarti** [vkohaupt/vokoscreen#104]
$ qmake
sh: lrelease: command not found
Project MESSAGE: 
Project MESSAGE: [vokoscreen] Makefile --> qt4
Project MESSAGE: 
Package libv4l2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libv4l2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libv4l2' found
Package libv4l2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libv4l2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libv4l2' found
Package libv4l2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libv4l2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libv4l2' found
Package libv4lconvert was not found in the pkg-config search path.
Perhaps you should add the directory containing `libv4lconvert.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libv4lconvert' found
Package libv4lconvert was not found in the pkg-config search path.
Perhaps you should add the directory containing `libv4lconvert.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libv4lconvert' found
Package libv4lconvert was not found in the pkg-config search path.
Perhaps you should add the directory containing `libv4lconvert.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libv4lconvert' found
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_ar.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_ast.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_ca.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_cs_CZ.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_cs.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_da_DK.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_de_AT.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_de_CH.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_de_DE.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_es_ES.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_es.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_fi_FI.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_fr_FR.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_hr.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_hu.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_id.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_it_CH.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_it_IT.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_ja_JP.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_nl_NL.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_pl_PL.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_pt_BR.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_ro.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_ru.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_sv_SE.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_th_TH.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_tr_TR.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_uk_UA.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_vi.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_zh_CN.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_zh_TW.qm'
==================================================================

Package 1:qt-4.6.2-28.el6_5.x86_64 already installed and latest version
Package 1:qt-4.6.2-28.el6_5.x86_64 already installed and latest version
qmake --version
Make version 2.01a
Using Qt version 4.6.2 in /usr/lib64

**Comment by vkohaupt** [comment]
You need the package
--libqt4-linguist
--libv4l
--libv4l-devel
--libv4l2
--libv4lconvert0

And its better you install Qt 4.8
