### ISSUE TITLE
vokoscreen and ffmpeg 2.6.3

### ISSUE THREAD

**Issue by texstar** [vkohaupt/vokoscreen#105]
ffmpeg 2.6.3 appears to break vokoscreens ability to record in full screen mode. 

Capture area 1600x900 at position 0.0 outside the screen size 1600x900
:0.0+0,0: Invalid argument

Nevermind: I found the bug in the ffmpeg code in their xcbgrab.c file which I've patched so vokoscreen works properly.

--- ffmpeg-2.6.3/libavdevice/xcbgrab.c	2015-05-16 20:26:53.000000000 -0500
+++ ffmpeg-2.6.3/libavdevice/xcbgrab.c	2015-05-18 16:05:27.946817248 -0500
@@ -532,8 +532,8 @@
     gc  = xcb_get_geometry(c->conn, c->screen->root);
     geo = xcb_get_geometry_reply(c->conn, gc, NULL);
 
-    if (c->x + c->width >= geo->width ||
-        c->y + c->height >= geo->height) {
+    if (c->x + c->width > geo->width ||
+        c->y + c->height > geo->height) {
         av_log(s, AV_LOG_ERROR,
                "Capture area %dx%d at position %d.%d "
                "outside the screen size %dx%d\n",

**Comment by vkohaupt** [comment]
thanks for the hint.
