### ISSUE TITLE
The last ffmpeg version crash vokoscreen.

### ISSUE THREAD

**Issue by alu18999959g** [vkohaupt/vokoscreen#107]
Hi, i have notice that the last ffmpeg version crash vokoscreen. I have dual boot Debian Testing and Ubuntu 14.04.2 .. i few days my system upgrade "ffmpeg" to the version 2.6.3 on Debian and Ubuntu. 

Example: Ubuntu Trusty 14.04.2

~$ apt-cache policy ffmpeg
"
ffmpeg:
  Instalados: 7:2.6.3~trusty1
  Candidato:  7:2.6.3~trusty1
  Tabla de versión:
 *** 7:2.6.3~trusty1 0
        100 /var/lib/dpkg/status
"

If i try start vokoscreen, I get the next error:
"
......................................................
[vokoscreen] "/usr/bin/ffmpeg" is not running 
[vokoscreen] [Regional selection] Frame locked: false 
.......................................................
"

You can read the extend output here:

http://codepad.org/H65howYy 

My vokoscreen version is not official repository from trusty ( i think this is 1.9.2), this is a compiled version : vokoscreen 2.3.0.

$ apt-cache policy vokoscreen
vokoscreen:
  Instalados: 2-3
  Candidato:  2-3
  Tabla de versión:
 *** 2-3 0
        100 /var/lib/dpkg/status
     1.9.0-2 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages

 Example : Debian Testing ( Stretch)
 
$ apt-cache policy ffmpeg
 "
ffmpeg:
  Instalados: 10:2.6.3-dmo1
  Candidato:  10:2.6.3-dmo1
  Tabla de versión:
 *** 10:2.6.3-dmo1 0
        990 http://www.deb-multimedia.org/ testing/main amd64 Packages
        100 /var/lib/dpkg/status
     7:2.6.3-1+b1 0
        800 http://ftp.es.debian.org/debian/ unstable/main amd64 Packages
"
        
The error is identical to that given in Ubuntu:

"
[vokoscreen] "ffmpeg" is running and is ready for reading and writing 
[vokoscreen] "ffmpeg" is not running 
[vokoscreen] [Regional selection] Frame locked: false 
[vokoscreen] File VERSION available
"

You can read the extend output here:

http://codepad.org/FWlEX7ts

My vokoscreen version:

$ apt-cache policy vokoscreen

"
vokoscreen:
  Instalados: 2.3.0-dmo1
  Candidato:  2.3.0-dmo1
  Tabla de versión:
 *** 2.3.0-dmo1 0
        990 http://www.deb-multimedia.org/ testing/main amd64 Packages
        100 /var/lib/dpkg/status
     2.2.0-2 0
        800 http://ftp.es.debian.org/debian/ unstable/main amd64 Packages
     2.1.0-1 0
        990 http://ftp.es.debian.org/debian/ testing/main amd64 Packages

"

Regards.

**Comment by vkohaupt** [comment]
Thanks for the hint. In the next week i fix the problem.
http://linuxecke.volkoh.de/vokoscreen/vokoscreen-troubleshooting.html
