### ISSUE TITLE
Build fix for Qt5.5rc

### ISSUE THREAD

**Issue by demmm** [vkohaupt/vokoscreen#110]
Trying to build from commit 41784d9d92bb2b95bd9c7dd6485423b1ba2ee43c with Qt 5.5rc fails, fix is a simple added include (Qt 5.5.0 stable should be released in 2-3 days):
https://github.com/KaOSx/apps/blob/master/vokoscreen/qt5.5.diff

Build fail without the patch:
```
linux-g++ -o qtlocalpeer.o QtSingleApplicationQt5/qtlocalpeer.cpp
QtSingleApplicationQt5/qtlocalpeer.cpp: In member function 'bool QtLocalPeer::sendMessage(const QString&, int)':
QtSingleApplicationQt5/qtlocalpeer.cpp:157:19: error: variable 'QDataStream ds' has initializer but incomplete type
     QDataStream ds(&socket);
                   ^
QtSingleApplicationQt5/qtlocalpeer.cpp: In member function 'void QtLocalPeer::receiveConnection()':
QtSingleApplicationQt5/qtlocalpeer.cpp:177:26: error: variable 'QDataStream ds' has initializer but incomplete type
     QDataStream ds(socket);
                          ^
Makefile:976: recipe for target 'qtloc
```

**Comment by vkohaupt** [comment]
I have now installed Qt 5.5 and test your patch. It´s compile fine with
QT 4.8.6
QT 5.4.2
QT 5.5
Thanks for your hint.

https://github.com/KaOSx/apps/blob/master/vokoscreen/PKGBUILD

You can remove the dependency 'opencv', the webcam modul works directly 
since vokoscreen-2.1.0 with v4l
