### ISSUE TITLE
Can't launch Vokoscreen on Fedora 22 XFCE

### ISSUE THREAD

**Issue by ChemBioScripting** [vkohaupt/vokoscreen#112]
Hello, I just installed _Fedora 22 XFCE x86_ to my friend and, between other programs, I installed `vokoscreen`, as on my _Fedora 21 XFCE x64_, but it can't start. This is the output when I launch `vokoscreen` in a terminal:

```
[Carolina@CaroLaptop Scrivania]$ vokoscreen 

[vokoscreen] Locale: "it_IT" 
[vokoscreen] Version: "2.3.0" 
[vokoscreen] Qt version:  4.8.6 
[vokoscreen] Operating system: "fedora 22" 
[vokoscreen] asoundlib version: "1.0.29" 
[vokoscreen] current icon-theme: "Faenza-Ambiance" 

[vokoscreen] ---Begin Search external tools--- 
[vokoscreen] Search ffmpeg ..... found Version: "2.6.3" 
[vokoscreen] Search pactl  ..... found Version: "6.0" 
[vokoscreen] ---End search external tools--- 

[vokoscreen] ---Begin search Screen--- 
[vokoscreen] Number of screens: 1 
[vokoscreen] Primary screen is: Display 1 
[vokoscreen] VirtualDesktop: false 
[vokoscreen] "Display 1:  1280 x 800" 
[vokoscreen] ---End search Screen--- 

[vokoscreen] ---Begin Environment--- 
[vokoscreen] runs on DISPLAY ":0.0" 
[vokoscreen] ---End Environment--- 

[vokoscreen] ---Begin search Videoplayer--- 
[vokoscreen] Find Videoplayer : "/bin/vlc" 
[vokoscreen] ---End search Videoplayer--- 

[vokoscreen] [Regional selection] Frame locked: false 

[vokoscreen] ---Begin search PulseAudio Plugin--- 
[vokoscreen] Found file .asound for PulseAudio Plugin 
[vokoscreen] ---End search PulseAudio Plugin--- 

 
[vokoscreen] ---Begin Pulse unload Module--- 
[vokoscreen] ---End Pulse unload Module--- 
 
[vokoscreen] ---Begin search Alsa capture device--- 
[vokoscreen] alsa_device_sample() in alsadevice.c: open audio device hw:0,0 (Successo)
[vokoscreen] alsa_device_sample() in alsadevice.c: Samplerate = 44100
[vokoscreen] Find CaptureCard: "[hw:0,0] HDA Intel" 
[vokoscreen] ---End search Alsa capture device--- 

[vokoscreen] ---Begin search PulseAudio Capture Devices--- 
[vokoscreen] Find CaptureCard: "Monitor of Audio interno Stereo analogico" with device: "alsa_output.pci-0000_00_1b.0.analog-stereo.monitor" 
[vokoscreen] Find CaptureCard: "Audio interno Stereo analogico" with device: "alsa_input.pci-0000_00_1b.0.analog-stereo" 
[vokoscreen] ---End search PulseAudio Capture Devices--- 

[vokoscreen] File VERSION available
[vokoscreen] recording fullscreen Display:  0 
[vokoscreen] Executive command : "/usr/bin/ffmpeg -report  -f x11grab -framerate 30 -video_size 1280x800 -i :0.0+0,0  -pix_fmt yuv420p -c:v libx264 -preset veryfast   -q:v 1  /tmp/vokoscreen-vokoscreen/vokoscreen-2015-07-13_21-18-51.mkv" 

[vokoscreen] "/usr/bin/ffmpeg" is running and is ready for reading and writing 

[vokoscreen] "/usr/bin/ffmpeg" is not running 
[vokoscreen] [Regional selection] Frame locked: false
```

I also tried to install _ffmpeg_ and _ffmpeg-devel_, but nothing. On my _Fedora 21_ all is working, but now I don't know if there is some missing package not yet installed, or there is some compatibility issue with _Fedora 22_. Searching on Google, I found the same error in other topics, like [here](http://askubuntu.com/questions/460149/vokoscreen-not-working-on-ubuntu-14-04).

I have to try it, but it seems there is no package for _avconv_ in Fedora... so I need to compile it from [source](http://sourceforge.net/projects/avconv/) and test that way, or may you suggest me something else? I have not made use of `avconv` on my _Fedora 21_, so this is strange for me.

Thanks a lot for the support,
Greetings,
Riccardo

**Comment by vkohaupt** [comment]
ffmpeg-2.6.3 is broken, please install a ffmpeg Version greater or 
smaller, or install vokoscreen 2.4.0 thats have a Workaround.

See on my page 
http://linuxecke.volkoh.de/vokoscreen/vokoscreen-troubleshooting.html

**Comment by ChemBioScripting** [comment]
Many thanks for your reply. I will try, and I will update you. Vokoscreen works very well!

**Comment by ChemBioScripting** [comment]
Perfect! :-)

I removed `ffmpeg` and `ffmpeg-devel` packages before to reinstall `vokoscreen`, and finally 
I saw that _vokoscreen_ searches in `/usr/bin` to run the `ffmpeg` command, so I copied the _ffmpeg_ executable file there. Now all is working!

Thanks a lot,
Regards,
Riccardo
