### ISSUE TITLE
showkey no display turkish character

### ISSUE THREAD

**Issue by namso-01** [vkohaupt/vokoscreen#113]
https://www.youtube.com/watch?v=-Z8iguXpbrE

ö ç ğ ş ü no display

**Comment by vkohaupt** [comment]
currently showkey display only a subset of ASCII characters

**Comment by namso-01** [comment]
please turkish character support

**Comment by vkohaupt** [comment]
I added KeyboardMapping, please test the new beta-2.4.6.
