### ISSUE TITLE
Crash in screencast::getFfmpegVersion() with SVN ffmpeg

### ISSUE THREAD

**Issue by DrMcCoy** [vkohaupt/vokoscreen#115]
vokoscreen segfaults in screencast::getFfmpegVersion(), in screencast.cpp:1988

My ffmpeg version string says "FFmpeg SVN-r25783\n[...]", i.e. after splitting the first line at " ", ```list[2]``` does not exist.

There seriously need to be checks that ```list[2]``` and ```list[0]``` above (i.e. if ffmpegversion is empty) exist before accessing them.

**Comment by DrMcCoy** [comment]
Also, with that old an ffmpeg version, recording in vokoscreen doesn't work. That's understandable, though, but you might want to add a warning somewhere, somehow.

Recording does work with the newer build from my distribution, though. A shame that there doesn't seem to be a way to select which ffmpeg binary to use on the command line ("--help"/"-h" doesn't show a help text, so I wouldn't know).

**Comment by vkohaupt** [comment]
Bitte lass mir eine Url zukommen von wo ich diese ffmpeg Version 
downloaden kann, ich werde das dann fixen.

**Comment by DrMcCoy** [comment]
Naja, das Problem ist ja nicht nur die ffmpeg-Version. Das Problem ist, dass das Program nicht segfaulten darf, wenn ein Programm, das, warum auch immer "ffmpeg" heißt, nicht das erwartete bei "-version" ausgibt. Auch (bzw. besonders!) nicht, wenn es nicht ffmpeg, sondern irgendwas anderes ist, das sich als ffmpeg ausgibt.

Wenn du wirklich ein ffmpeg haben möchtest, was dieses Verhalten an den Tag legt, dann nimm zB das alte SVN Repository hier: svn://svn.mplayerhq.hu/ffmpeg/trunk . Wird zwar seit langem nicht mehr geupdated, aber im HEAD siehst du dieses Verhalten. Oder nimm irgendwas vor 9ac58ba1 aus dem aktuellen git Repository (https://github.com/FFmpeg/FFmpeg/commit/9ac58ba1), wo das neue Verhalten mit " version " in der Mitte anscheinend seinen Ursprung hat.

**Comment by vkohaupt** [comment]
https://github.com/vkohaupt/vokoscreen/commit/b59b9886e724bb3f013753bae725843d49915e05

Danke für den Hinweis.

**Comment by DrMcCoy** [comment]
Jo, das ist meiner Meinung nach besser. Danke. :)
