### ISSUE TITLE
Sound bad quality for vokoscreenMix

### ISSUE THREAD

**Issue by petrposvic** [vkohaupt/vokoscreen#116]
If I use PulseAudio with recording HDMI and microphone audio together, audio has bad quality after 40 seconds. I change screencast.cpp (line 2370) from

      if ( counter > 0 )
        value = "-f alsa -i pulse ";

to

      if (counter > 1) { 
        value = "-f alsa -f pulse -i vokoscreenMix.monitor ";
      } else 
      if ( counter > 0 )
        value = "-f alsa -i pulse ";

and everything works prefectly now.

All executive command is: /usr/bin/ffmpeg -report  -f x11grab -framerate 25 -video_size 1918x1078 -i :0+0,0 -f alsa -f pulse -i vokoscreenMix.monitor  -pix_fmt yuv420p -c:v libx264 -preset veryfast -c:a libmp3lame  -q:v 1  -s 1920x1080 /tmp/vokoscreen-vokoscreen/vokoscreen-2015-09-01_14-40-43.avi

vokoscreen 2.4.0
pulseaudio 6.0
ffmpeg version 2.5.8-0ubuntu0.15.04.1

**Comment by vkohaupt** [comment]
Many thanks,
the Audio recordung with tow devices, with your patch  is much better.
https://github.com/vkohaupt/vokoscreen/commit/b47bdc1109ba0f116af615706650526413cda07c
Thanks again for the excellent work
