### ISSUE TITLE
Multi-users / terminal server support.

### ISSUE THREAD

**Issue by viewizard** [vkohaupt/vokoscreen#119]
The issue is single for all users "temp" folder with user-related permission (only owner can write in "temp" folder, since folder have 755 permission mode). Here is the patch I am using with 2.4.4 version for per-user "temp" foldes.

```
--- a/screencast.cpp
+++ b/screencast.cpp
@@ -2326,7 +2327,7 @@
 QString screencast::PathTempLocation()
 {
   // Doppelter ProgName um Eindeutigkeit in tmp zuerreichen
-  QString tmpName = vkSettings.getProgName() + "-" + vkSettings.getProgName();
+  QString tmpName = vkSettings.getProgName() + "-" + qgetenv( "USER" );
 
   #ifdef QT4
   QString tempPathProg = QDesktopServices::storageLocation ( QDesktopServices::TempLocation ) + QDir::separator() + tmpName;
```

**Comment by vkohaupt** [comment]
Have testet with two User, and working wonderful.

https://github.com/vkohaupt/vokoscreen/commit/7e46d2ab97761670ea60db56e4d16267d3fa726c

Many Thanks

**Comment by viewizard** [comment]
Thanks a lot for fast implementation!
