### ISSUE TITLE
Save audio recording settings

### ISSUE THREAD

**Issue by bonanza123** [vkohaupt/vokoscreen#121]
I'm running 2.4.3 beta on archlinux and noticed that, contrary to the video settings, the audio settings are not saved. Before I was recording the presentation I checked the video settings and they were saved, so I assumed that would also be the case for the audio settings. This ended in the situation where I was recording a 30 minutes presentation just noticing at the end that no audio was recorded -.-

**Comment by vkohaupt** [comment]
Will the Audio settings principle not saved?

**Comment by bonanza123** [comment]
In my case, the audio source was not saved.

**Comment by vkohaupt** [comment]
is reproducible?

**Comment by bonanza123** [comment]
Yes happens everytime I start vokoscreen. For testing purposes I updated to the lastest availabe beta for archlinux (2.4.5) and noticed the same issue. What I forgot to mention is that the microphone I used is external (connected via USB)

**Comment by vkohaupt** [comment]
-start vokoscreen
-set the audio settings
-close vokoscreen
-send me the file ~/.config/vokoscreen/vokoscreen.config

then

-open a terminal
-start vokoscreen
-send me the complete ouput
