### ISSUE TITLE
Vokoscreen build in Pisi Linux 2.0 with QT5 but starts not

### ISSUE THREAD

**Issue by groni** [vkohaupt/vokoscreen#122]
Hello Mr. Kohaupt
I have build Vokoscreen 2.4.6 in Pisi Linux with QT5 building was perfect without an Error, but after install it starts not, In the Menu was all correct the executable was in /usr/bin.

I try to start it in the Terminal but nothing alone this output:

groni@groni_pisilinux2 ~ $ vokoscreen
vokoscreen(4158)/default unknown: 
vokoscreen(4158)/default unknown: [vokoscreen] Locale: "en_US"
vokoscreen(4158)/default unknown: [vokoscreen] Version: "2.4.6 Beta"
vokoscreen(4158)/default unknown: [vokoscreen] Qt version:  5.5.1
vokoscreen(4158)/default unknown: [vokoscreen] Operating system: "/etc/os-release not found"
vokoscreen(4158)/default unknown: [vokoscreen] asoundlib version: "1.0.29"
vokoscreen(4158)/default unknown: [vokoscreen] current icon-theme: "Nitrux"
vokoscreen(4158)/default unknown: 
vokoscreen(4158)/default unknown: [vokoscreen] ---Begin Search external tools---
vokoscreen(4158)/default unknown: [vokoscreen] Search ffmpeg ..... found "ffmpeg" Version: "ffmpeg version 2.7.2 Copyright (c) 2000-2015 the FFmpeg developers"
vokoscreen(4158)/default unknown: [vokoscreen] Search pactl  ..... found Version: "6.0"
vokoscreen(4158)/default unknown: [vokoscreen] ---End search external tools---
vokoscreen(4158)/default unknown: 
vokoscreen(4158)/default unknown: [vokoscreen] ---Begin search Screen---
vokoscreen(4158)/default unknown: [vokoscreen] Number of screens: 1
vokoscreen(4158)/default unknown: [vokoscreen] Primary screen is: Display 1
vokoscreen(4158)/default unknown: [vokoscreen] VirtualDesktop: false
vokoscreen(4158)/default unknown: [vokoscreen] "Display 1:  1920 x 1080"
vokoscreen(4158)/default unknown: [vokoscreen] ---End search Screen---
vokoscreen(4158)/default unknown: 
vokoscreen(4158)/default unknown: [vokoscreen] ---Begin Environment---
vokoscreen(4158)/default unknown: [vokoscreen] runs on DISPLAY ":0"
vokoscreen(4158)/default unknown: [vokoscreen] ---End Environment---
vokoscreen(4158)/default unknown: 
vokoscreen(4158)/default unknown: [vokoscreen] ---Begin search Videoplayer---
vokoscreen(4158)/default unknown: [vokoscreen] Find Videoplayer : "/usr/bin/dragon"
vokoscreen(4158)/default unknown: [vokoscreen] Find Videoplayer : "/usr/bin/vlc"
vokoscreen(4158)/default unknown: [vokoscreen] ---End search Videoplayer---
vokoscreen(4158)/default unknown: 
vokoscreen(4158)/default unknown: [vokoscreen] [Regional selection] Frame locked: false
vokoscreen(4158)/default unknown: 
vokoscreen(4158)/default unknown: [vokoscreen] ---Begin search PulseAudio Plugin---
vokoscreen(4158)/default unknown: [vokoscreen] Found file .asound for PulseAudio Plugin
vokoscreen(4158)/default unknown: [vokoscreen] ---End search PulseAudio Plugin---
vokoscreen(4158)/default unknown: 
vokoscreen(4158)/default unknown: 
vokoscreen(4158)/default unknown: [vokoscreen] ---Begin Pulse unload Module---
vokoscreen(4158)/default unknown: [vokoscreen] ---End Pulse unload Module---
vokoscreen(4158)/default unknown:                                                                                    
Segmentation fault                                                                                                   
groni@groni_pisilinux2 ~ $ 

Did you have an Idea why it not start?
Thanks in advanced for your Answer

**Comment by vkohaupt** [comment]
Hi groni,

das machen wir auf deutsch, da tue ich mir leichter :>)

Wenn ich mir die Ausgabe so anschaue schmiert vokoscreen ab sobald es um 
die Initialisierung der Shortcuts und dem Systray geht.

Das ganze würde ich in einer Virtuellen Umgebung nachvollziehen, dazu 
bräuchte ich am besten ne step by step Anleitung mit direkten Links zu 
den Downloaddateien Qt, Compiler, etc. und einen Crashkurs für den Pisi 
Paketmanager.

Sofern der Fehler reproduzierbar ist sollte der Bug schnell behoben sein.

Da fällt mir auf wo kommt denn diese immer kehrende Ausgabe her?
vokoscreen(4158)/default unknown:

Viele grüße Volker

**Comment by groni** [comment]
Hallo Herr Kohaupt


Auch für mich ist es in Deutsch wesentlich Leichter.

Wo die Ausgabe herkommt im Moment  keine Ahnung.

Pisi Linux in einer virtuellen Umgehbung zu installieren auch nicht.

ich schicke ihnen alles komplett zu, mit Anleitung des Paket Managers

gruß

groni

Am 11. November 2015 um 23:58 schrieb Volker Kohaupt <
notifications@github.com>:

**Comment by groni** [comment]
Hallo Herr Kohaupt

Anbei einen Link auf die deutsche Pisi Linux Seite von mir

https://pisilinuxgermany.wordpress.com/

Da sie Pisi Linux 2.0 runterladen müssen nehmen sie bitte die alpha 5, da
die alpha6 sich in der Virtualbox nicht installieren läßt

https://openload.co/f/vuimrNgPjSE/Pisi-Linux-2.0-Alfa5-KDE5-KaraKedi-x86_64.iso

Wenn sie es installiert haben, öffnen sie ein Terminal und schreiben "*sudo
pisi up -dsy*" zum updaten auf die alpah6.

Nach einem neustart steht ihnen Pisi Linux voll zur verfügung.

ich werde Ihnen, da Pisi Linux 2.0 alpha im Moment nicht über einen
grafischen Paket Verwalter verfügt, vokoscreen als fertiges Pisi Paket und
zum Bauen als Anhang in

 dieser Mail mitsenden.

Zum Bauen von Vokoscreen brauchen sie eigentlich nur "sudo pisi bi
pspec.xml -vd" im Terminal ausführen, bitte darauf achten das sie sich mit
dem Terminal im Verzeichnis

befinden wo die pspec.xml liegt.

Zum installieren des fertigen Paketes von Vokoscreen schreiben sie im
Terminal nur "*sudo pisi it *.pisi*" oder mit dem ganzen namen "*sudo pisi
it *


*vokoscreen-2.4.6-1-p01-x86_64.pisi *das ist eigentlich alles.


Sollten sie das Paket wieder entfernen wollen schreiben Sie "*sudo pisi rm
vokoscreen*".


Beim installieren  werden die benötigten Abhängigkeiten mit installiert,
beim Bauen müssten Sie die Bau abhängigkeiten vorher installieren mit "*sudo
pisi it -c system.devel*"


Sollten noch Fragen auftauchen, können Sie sich jederzeit bei mir melden.


E-Mail adresse : groni3427@gmail.com oder groni@pisilinux.org  oder über
das github.


Ich bedanke mich für Ihre Unterstützung und möchte noch hinzufügen in Pisi
Linux 1.2 läuft Vokoscreen ganz große Klasse.


Mit freundlichen Grüßen


Stefan Gronewold (aka groni)

Am 12. November 2015 um 00:22 schrieb groni g <groni3427@gmail.com>:

**Comment by vkohaupt** [comment]
Hallo groni,

anscheinend akzeptiert github keine Anhänge, sende das Paket bitte 
direkt an mich vkohaupt@freenet.de

Vielen Dank und grüße Volker

**Comment by tuxmuck** [comment]
Problem wurde intern mit groni per mail geklärt -
Kann somit hier geschlossen werden.

**Comment by groni** [comment]
Vokoscreen ist perfekt gebaut worden in Pisi Linux 2.0.
Nach der Erklärung von Volker Kohaupt an was es liegen könnte hat sich unser Team auf Fehlersuche begeben und es geschafft die Fehler zu beheben. Nach einem Update und einem Neustart arbeitet Vokoscreen pefekt.

Herzlich Dank an Volker für seine Bemühungen und seiner Hilfe

![vokoscreen](https://cloud.githubusercontent.com/assets/3329657/11169056/8bffaf52-8baa-11e5-94bc-382b79a99c15.png)
