### ISSUE TITLE
Add libfaac or libfdk_aac as audio encoder?

### ISSUE THREAD

**Issue by maz-1** [vkohaupt/vokoscreen#123]
Should be useful for mkv container.
Though I'm not sure if avi supports aac.

**Comment by vkohaupt** [comment]
I added acc in vokoscreen and have testet with mkv, avi and the pause 
funktion.The name from acc audiocodec is libvo_aacenc, it´s not very 
nice name and i must for the future redesign the audio codec name.
https://github.com/vkohaupt/vokoscreen/commit/84cc01ac8d09e49de2af1a3975e2ab8ad45223e9

**Comment by maz-1** [comment]
Maybe use such codec name format?
AAC (libvo_aacenc)
AAC (libfaac)
MP3 (libmp3lame)

**Comment by maz-1** [comment]
Also, I think it would be good if we can choose between any aac encoder supported by ffmpeg
which can be listed by 
ffmpeg -codecs|grep -P '^ [A-Z.]{6} aac '|grep -oP '(?<=encoders: )[a-z0-9_ ]+'

**Comment by sl1pkn07** [comment]
in beta 2.4.10 (commit 3a53631f03d20048d7efb3b714e4c2074f224d9d) can't select the audio libvo_aacenc

**Comment by vkohaupt** [comment]
Please give the output from

ffmpeg -encoders | grep libvo_aacenc

**Comment by sl1pkn07** [comment]
mmm yes, Arch ffmpeg seems has not been compiled with vo-AACEnc, but support for encoding AAC is available

└───╼  ffmpeg -encoders |grep aac
ffmpeg version 2.8.4 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libdcadec --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-shared --enable-version3 --enable-x11grab
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
 A..X.. aac                  AAC (Advanced Audio Coding)

is possible add support for libavcode-aac? (included in ffmpeg)
