### ISSUE TITLE
Can't exit vokoscreen with exit menu

### ISSUE THREAD

**Issue by sl1pkn07** [vkohaupt/vokoscreen#125]
Hi

When trying exit with 'Menu -> Exit' in systray, vokoscreen is going minimized to systray instead of exit, neither Alt+F4 works

Then when press in menu "Hide window" (it should be "Show Window"?) show again the GUI, (in menu still show "Hide Window", but if press again, then switch to "Show window" and the GUI is going minimized in systray again). but still can't exit with menu

Only can exit with killall/system activity, or Ctrl+C if is run in terminal

All on plasma 5

Greetings

**Comment by vkohaupt** [comment]
It was a problem with Qt5, but now it does.
Please test it.

I activate aac, but by my ffmpeg is aac expermintal and i can´t test, i 
must write additionally code in vokoscreen.
Please test it.

See the last commit

**Comment by sl1pkn07** [comment]
Yep. Sems still experimental, for use with ffmpeg need a extra command '-strict' for can use it. Is posible add it?

Greetings

**Comment by sl1pkn07** [comment]
Yep. Sems  is still experimental codec, for use with ffmpeg need a extra command '-strict' for can use it. Is posible add it?

Greetings

**Comment by sl1pkn07** [comment]
the problem with exit is fixed. thanks!!!

and yep, aac audo not works, need add '-strict' option to ffmpeg

**Comment by vkohaupt** [comment]
I am work on this, and i think in 2-3 days i can show result

**Comment by vkohaupt** [comment]
The two days are gone :>)
You can test acc, see the last commit

**Comment by sl1pkn07** [comment]
thanks a lot. now can use aac without problem!

great work and great program! (finally on Qt5 ;_;)

greetings
