### ISSUE TITLE
Creating .asoundrc might break audio playback

### ISSUE THREAD

**Issue by andree182** [vkohaupt/vokoscreen#127]
The .asoundrc file created breaks audio playback in flashplugin in on my system (ubuntu 14.04). The reason is perhaps some clash with pulseaudio/alsa - anyhow, once the file is removed, playback works again.

Maybe the comment "-Die .asoundrc sollte nur erstellt werden wenn der Start von ffmpeg fehlschägt." should be really implemented, or the .asoundrc made less "conflicting"...

**Comment by vkohaupt** [comment]
Hallo,

ich habe mir das ganze mal angeschaut und ja das kann ein Problem 
darstellen. Mal schauen ob ich es hin bekomme das man die ".asoundrc" 
für Aufnahmen mit Pulse nicht mehr benötigt.

Mit einem Aufnahmegerät ohne der ".asoundrc" klappt das hier schon.

**Comment by vkohaupt** [comment]
Beta 2.4.13 is out
the .asoundrc is no longer needed

Thank for your help
