### ISSUE TITLE
Don't record mouse pinter option is ignored

### ISSUE THREAD

**Issue by Rombusevil** [vkohaupt/vokoscreen#128]
Don't record mouse pointer checkbox is ignored. When on mouse pointer is still recorded, when off it's still recorded.

Setings tested:
fps 25, 
Codec video: libx264 format:avi/mkv
Codec audio: libmp3lame

From debian repos on debian 9 testing

**Comment by vkohaupt** [comment]
Thanks for your hint i have the bug fixed

https://github.com/vkohaupt/vokoscreen/commit/835a8c181610ba6d0278525282169532afa188b5

**Comment by Rombusevil** [comment]
Thanks! it works as intended now :+1:
