### ISSUE TITLE
Save as GIF animation?

### ISSUE THREAD

**Issue by orschiro** [vkohaupt/vokoscreen#130]
Dear all, 

Just an idea that I had: 

What are your thoughts on a "Save as GIF animation" feature?

Thankfully,

~Robert

**Comment by vkohaupt** [comment]
added gif support

https://github.com/vkohaupt/vokoscreen/commits/master

Best regards
Volker

**Comment by orschiro** [comment]
Dear @vkohaupt,

This is so great. Thank you for your supportive and active listening to feature requests!

Thankfully,

~Robert
