### ISSUE TITLE
hidpi support

### ISSUE THREAD

**Issue by polpodan** [vkohaupt/vokoscreen#131]
I'm a owner of Lenovo Yoga 2 pro.  It has a retina display (3200 X 1800).  However, vokoscreen detect my screen as half of it (1600 x 900).  Full screen capture and zone capture doesn't capture the right section of my screen.  It acts as if my screen is detected as half of it.  Window capture works as intended.  I'm using version 2.4.15 beta on arch linux, with plasma 5.5.4.

**Comment by vkohaupt** [comment]
Hmmm.....

the best way is we make that step by step. As first i need the output 
from vokoscreen.

Open a terminal, start vokoscreen, enable fullscreen, make a record and 
then stop.

Copy the full output here.

Thanks.

**Comment by polpodan** [comment]
[vokoscreen] Locale: "fr_FR"
[vokoscreen] Version: "2.4.15 Beta"
[vokoscreen] Qt version:  5.5.1
[vokoscreen] Operating system: "arch "
[vokoscreen] Desktop: "KDE"
[vokoscreen] asoundlib version: "1.1.0"
[vokoscreen] current icon-theme: "Antu"
 
[vokoscreen] ---Begin Search external tools---
[vokoscreen] Search ffmpeg ..... found "/usr/bin/ffmpeg" Version: "ffmpeg version 2.8.6 Copyright (c) 2000-2016 the FFmpeg developers"
[vokoscreen] Search pactl  ..... found Version: "8.0"
[vokoscreen] ---End search external tools---
 
[vokoscreen] ---Begin search Screen---
[vokoscreen] Number of screens: 1
[vokoscreen] Primary screen is: Display 1
[vokoscreen] VirtualDesktop: false
[vokoscreen] "Display 1:  1600 x 900"
[vokoscreen] ---End search Screen---
 
[vokoscreen] ---Begin Environment---
[vokoscreen] runs on DISPLAY ":0"
[vokoscreen] ---End Environment---
 
[vokoscreen] added device ("video0")
[vokoscreen] connected devices ("video0")
[vokoscreen] v4l2 device info  /dev/video0
[vokoscreen] ---Begin search Videoplayer---
[vokoscreen] Find Videoplayer : "/usr/bin/vlc"
[vokoscreen] Find Videoplayer : "/usr/bin/totem"
[vokoscreen] Find Videoplayer : "/usr/bin/smplayer"
[vokoscreen] Find Videoplayer : "/usr/bin/kdenlive"
[vokoscreen] Find Videoplayer : "/usr/bin/mpv"
[vokoscreen] ---End search Videoplayer---
 
[vokoscreen] ---Begin search GIFplayer---
[vokoscreen] Find GIFplayer : "firefox"
[vokoscreen] Find GIFplayer : "mpv"
[vokoscreen] Find GIFplayer : "chromium"
[vokoscreen] ---End search GIFoplayer---
 
[vokoscreen] ---Begin Pulse unload Module---
[vokoscreen] ---End Pulse unload Module---
 
[vokoscreen] ---Begin search video codec---
[vokoscreen] find Videocodec "libx264"
[vokoscreen] find Videocodec "libx265"
[vokoscreen] find Videocodec "mpeg4"
[vokoscreen] find Videocodec "huffyuv"
[vokoscreen] find Videocodec "gif"
[vokoscreen] ---End search video codec---
 
[vokoscreen] ---Begin search audio codec---
[vokoscreen] find Audiocodec "libmp3lame"
[vokoscreen] find Audiocodec "libvorbis"
[vokoscreen] find Audiocodec "pcm_s16le"
[vokoscreen] not found Audiocodec "libvo_aacenc"
[vokoscreen] find Audiocodec "aac"
[vokoscreen] ---End search audio codec---
 
[vokoscreen] ---Begin search formats---
[vokoscreen] find Format "mkv"
[vokoscreen] find Format "avi"
[vokoscreen] find Format "gif"
[vokoscreen] ---End search formats---
 
[vokoscreen] ---Begin search Alsa capture device---
[vokoscreen] alsa_device_sample() in alsadevice.c: cannot open audio device hw:0,3 (Aucun fichier ou dossier de ce type)
[vokoscreen] Find CaptureCard: "[hw:0,3] HDA Intel HDMI"
[vokoscreen] alsa_device_sample() in alsadevice.c: open audio device hw:1,0 (Succès)
[vokoscreen] alsa_device_sample() in alsadevice.c: Samplerate = 44100
[vokoscreen] Find CaptureCard: "[hw:1,0] HDA Intel PCH"
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM 
[vokoscreen] alsa_device_sample() in alsadevice.c: cannot open audio device  (Aucun fichier ou dossier de ce type)
[vokoscreen] Find CaptureCard: "[] ThinkPad Console Audio Control"
[vokoscreen] ---End search Alsa capture device---
 
[vokoscreen] ---Begin search PulseAudio Capture Devices---
[vokoscreen] Find CaptureCard: "Monitor of Audio interne Digital Stereo (HDMI)" with device: "alsa_output.pci-0000_00_03.0.hdmi-stereo.monitor"
[vokoscreen] Find CaptureCard: "Monitor of Audio interne Stéréo analogique" with device: "alsa_output.pci-0000_00_1b.0.analog-stereo.monitor"
[vokoscreen] Find CaptureCard: "Audio interne Stéréo analogique" with device: "alsa_input.pci-0000_00_1b.0.analog-stereo"
[vokoscreen] ---End search PulseAudio Capture Devices---
 
[vokoscreen] File VERSION available
 
[vokoscreen] recording fullscreen Display:  0
[vokoscreen] Executive command : "/usr/bin/ffmpeg -report -f x11grab -draw_mouse 1 -framerate 30 -video_size 1600x900 -i :0+0,0 -f pulse -i vokoscreenMix.monitor -pix_fmt yuv420p -c:v libx264 -preset veryfast -c:a libmp3lame -q:v 1 -s 1600x900 -f matroska /tmp/vokoscreen-tintin/vokoscreen-2016-02-13_08-10-24.mkv"
 
[vokoscreen] ---Begin Pulse loade module---
[vokoscreen] pactl load-module module-null-sink sink_name=vokoscreenMix  "28"
[vokoscreen] pactl load-module module-loopback source= "alsa_output.pci-0000_00_1b.0.analog-stereo.monitor" sink=vokoscreenMix number "29"
[vokoscreen] pactl load-module module-loopback source= "alsa_input.pci-0000_00_1b.0.analog-stereo" sink=vokoscreenMix number "30"
[vokoscreen] ---End Pulse loade module---
 
[vokoscreen] "/usr/bin/ffmpeg" is running and is ready for reading and writing
 
[vokoscreen] "/usr/bin/ffmpeg" is not running
 
[vokoscreen] ---Begin Pulse unload Module---
[vokoscreen] pactl unload-module number "30"
[vokoscreen] pactl unload-module number "29"
[vokoscreen] pactl unload-module number "28"
[vokoscreen] ---End Pulse unload Module---
 
[vokoscreen] ---Begin Pulse unload Module---
[vokoscreen] ---End Pulse unload Module---

**Comment by tuxmuck** [comment]
Volker,
>>  -video_size 1600x900
Ist dieser Wert evtl. im code als Maximum gesetzt?

**Comment by vkohaupt** [comment]
The probleme can make the qt4 funktions. I have added Qt5 funktions only 
for terminal output.

beta 2.5.16 is out

Please put here the completle terminal output

**Comment by polpodan** [comment]
Here's the new complete terminal output!

[vokoscreen] Locale: "fr_FR"
[vokoscreen] Version: "2.4.16 Beta"
[vokoscreen] Qt version:  5.5.1
[vokoscreen] Operating system: "arch "
[vokoscreen] Desktop: "KDE"
[vokoscreen] asoundlib version: "1.1.0"
[vokoscreen] current icon-theme: "Antu"
 
[vokoscreen] ---Begin Search external tools---
[vokoscreen] Search ffmpeg ..... found "/usr/bin/ffmpeg" Version: "ffmpeg version 2.8.6 Copyright (c) 2000-2016 the FFmpeg developers"
[vokoscreen] Search pactl  ..... found Version: "8.0"
[vokoscreen] ---End search external tools---
 
[vokoscreen] Qt5 availableGeometry() QRect(0,34 1600x866)
[vokoscreen] Qt5 availableSize() QSize(1600, 866)
[vokoscreen] Qt5 physicalSize() QSizeF(293, 165)
[vokoscreen] Qt5 size() QSize(1600, 900)
 
[vokoscreen] ---Begin search Screen---
[vokoscreen] Number of screens: 1
[vokoscreen] Primary screen is: Display 1
[vokoscreen] VirtualDesktop: false
[vokoscreen] "Display 1:  1600 x 900"
[vokoscreen] ---End search Screen---
 
[vokoscreen] ---Begin Environment---
[vokoscreen] runs on DISPLAY ":0"
[vokoscreen] ---End Environment---
 
[vokoscreen] added device ("video0")
[vokoscreen] connected devices ("video0")
[vokoscreen] v4l2 device info  /dev/video0
[vokoscreen] ---Begin search Videoplayer---
[vokoscreen] Find Videoplayer : "/usr/bin/vlc"
[vokoscreen] Find Videoplayer : "/usr/bin/totem"
[vokoscreen] Find Videoplayer : "/usr/bin/smplayer"
[vokoscreen] Find Videoplayer : "/usr/bin/kdenlive"
[vokoscreen] Find Videoplayer : "/usr/bin/mpv"
[vokoscreen] ---End search Videoplayer---
 
[vokoscreen] ---Begin search GIFplayer---
[vokoscreen] Find GIFplayer : "firefox"
[vokoscreen] Find GIFplayer : "mpv"
[vokoscreen] Find GIFplayer : "chromium"
[vokoscreen] ---End search GIFoplayer---
 
[vokoscreen] ---Begin Pulse unload Module---
[vokoscreen] ---End Pulse unload Module---
 
[vokoscreen] ---Begin search video codec---
[vokoscreen] find Videocodec "libx264"
[vokoscreen] find Videocodec "libx265"
[vokoscreen] find Videocodec "mpeg4"
[vokoscreen] find Videocodec "huffyuv"
[vokoscreen] find Videocodec "gif"
[vokoscreen] ---End search video codec---
 
[vokoscreen] ---Begin search audio codec---
[vokoscreen] find Audiocodec "libmp3lame"
[vokoscreen] find Audiocodec "libvorbis"
[vokoscreen] find Audiocodec "pcm_s16le"
[vokoscreen] not found Audiocodec "libvo_aacenc"
[vokoscreen] find Audiocodec "aac"
[vokoscreen] ---End search audio codec---
 
[vokoscreen] ---Begin search formats---
[vokoscreen] find Format "mkv"
[vokoscreen] find Format "avi"
[vokoscreen] find Format "gif"
[vokoscreen] ---End search formats---
 
[vokoscreen] ---Begin search Alsa capture device---
[vokoscreen] alsa_device_sample() in alsadevice.c: cannot open audio device hw:0,3 (Aucun fichier ou dossier de ce type)
[vokoscreen] Find CaptureCard: "[hw:0,3] HDA Intel HDMI"
[vokoscreen] alsa_device_sample() in alsadevice.c: open audio device hw:1,0 (Succès)
[vokoscreen] alsa_device_sample() in alsadevice.c: Samplerate = 44100
[vokoscreen] Find CaptureCard: "[hw:1,0] HDA Intel PCH"
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM 
[vokoscreen] alsa_device_sample() in alsadevice.c: cannot open audio device  (Aucun fichier ou dossier de ce type)
[vokoscreen] Find CaptureCard: "[] ThinkPad Console Audio Control"
[vokoscreen] ---End search Alsa capture device---
 
[vokoscreen] ---Begin search PulseAudio Capture Devices---
[vokoscreen] Find CaptureCard: "Monitor of Audio interne Digital Stereo (HDMI)" with device: "alsa_output.pci-0000_00_03.0.hdmi-stereo.monitor"
[vokoscreen] Find CaptureCard: "Monitor of Audio interne Stéréo analogique" with device: "alsa_output.pci-0000_00_1b.0.analog-stereo.monitor"
[vokoscreen] Find CaptureCard: "Audio interne Stéréo analogique" with device: "alsa_input.pci-0000_00_1b.0.analog-stereo"
[vokoscreen] ---End search PulseAudio Capture Devices---
 
[vokoscreen] File VERSION available
 
[vokoscreen] recording fullscreen Display:  0
[vokoscreen] Executive command : "/usr/bin/ffmpeg -report -f x11grab -draw_mouse 1 -framerate 30 -video_size 1600x900 -i :0+0,0 -f pulse -i vokoscreenMix.monitor -pix_fmt yuv420p -c:v libx264 -preset veryfast -c:a libmp3lame -q:v 1 -s 1600x900 -f matroska /tmp/vokoscreen-tintin/vokoscreen-2016-02-13_20-07-32.mkv"
 
[vokoscreen] ---Begin Pulse loade module---
[vokoscreen] pactl load-module module-null-sink sink_name=vokoscreenMix  "31"
[vokoscreen] pactl load-module module-loopback source= "alsa_output.pci-0000_00_1b.0.analog-stereo.monitor" sink=vokoscreenMix number "32"
[vokoscreen] pactl load-module module-loopback source= "alsa_input.pci-0000_00_1b.0.analog-stereo" sink=vokoscreenMix number "33"
[vokoscreen] ---End Pulse loade module---
 
[vokoscreen] "/usr/bin/ffmpeg" is running and is ready for reading and writing
 
[vokoscreen] "/usr/bin/ffmpeg" is not running
 
[vokoscreen] ---Begin Pulse unload Module---
[vokoscreen] pactl unload-module number "33"
[vokoscreen] pactl unload-module number "32"
[vokoscreen] pactl unload-module number "31"
[vokoscreen] ---End Pulse unload Module---
 
[vokoscreen] ---Begin Pulse unload Module---
[vokoscreen] ---End Pulse unload Module---

**Comment by vkohaupt** [comment]
next step

compile please from the current Branch:Master

Copy the full output here.

**Comment by polpodan** [comment]
This time, it detects the screen as 3200 x 1800 but recorded as 1600 x 900.



[vokoscreen] Locale: "fr_FR"
[vokoscreen] Version: "2.4.16 Beta"
[vokoscreen] Qt version:  5.5.1
[vokoscreen] Operating system: "arch "
[vokoscreen] Desktop: "KDE"
[vokoscreen] asoundlib version: "1.1.0"
[vokoscreen] current icon-theme: "Antu"
 
[vokoscreen] ---Begin Search external tools---
[vokoscreen] Search ffmpeg ..... found "/usr/bin/ffmpeg" Version: "ffmpeg version 2.8.6 Copyright (c) 2000-2016 the FFmpeg developers"
[vokoscreen] Search pactl  ..... found Version: "8.0"
[vokoscreen] ---End search external tools---
 
[vokoscreen] Qt5 availableGeometry() QRect(0,34 1600x866)
[vokoscreen] Qt5 availableSize() QSize(1600, 866)
[vokoscreen] Qt5 physicalSize() QSizeF(293, 165)
[vokoscreen] Qt5 size() QSize(1600, 900)
[vokoscreen] Qt5 devicePixelRatio() 2
 
[vokoscreen] ---Begin search Screen---
[vokoscreen] Number of screens: 1
[vokoscreen] Primary screen is: Display 1
[vokoscreen] VirtualDesktop: false
[vokoscreen] "Display 1:  3200 x 1800"
[vokoscreen] ---End search Screen---
 
[vokoscreen] ---Begin Environment---
[vokoscreen] runs on DISPLAY ":0"
[vokoscreen] ---End Environment---
 
[vokoscreen] added device ("video0")
[vokoscreen] connected devices ("video0")
[vokoscreen] v4l2 device info  /dev/video0
[vokoscreen] ---Begin search Videoplayer---
[vokoscreen] Find Videoplayer : "/usr/bin/vlc"
[vokoscreen] Find Videoplayer : "/usr/bin/totem"
[vokoscreen] Find Videoplayer : "/usr/bin/smplayer"
[vokoscreen] Find Videoplayer : "/usr/bin/kdenlive"
[vokoscreen] Find Videoplayer : "/usr/bin/mpv"
[vokoscreen] ---End search Videoplayer---
 
[vokoscreen] ---Begin search GIFplayer---
[vokoscreen] Find GIFplayer : "firefox"
[vokoscreen] Find GIFplayer : "mpv"
[vokoscreen] Find GIFplayer : "chromium"
[vokoscreen] ---End search GIFoplayer---
 
[vokoscreen] ---Begin Pulse unload Module---
[vokoscreen] ---End Pulse unload Module---
 
[vokoscreen] ---Begin search video codec---
[vokoscreen] find Videocodec "libx264"
[vokoscreen] find Videocodec "libx265"
[vokoscreen] find Videocodec "mpeg4"
[vokoscreen] find Videocodec "huffyuv"
[vokoscreen] find Videocodec "gif"
[vokoscreen] ---End search video codec---
 
[vokoscreen] ---Begin search audio codec---
[vokoscreen] find Audiocodec "libmp3lame"
[vokoscreen] find Audiocodec "libvorbis"
[vokoscreen] find Audiocodec "pcm_s16le"
[vokoscreen] not found Audiocodec "libvo_aacenc"
[vokoscreen] find Audiocodec "aac"
[vokoscreen] ---End search audio codec---
 
[vokoscreen] ---Begin search formats---
[vokoscreen] find Format "mkv"
[vokoscreen] find Format "avi"
[vokoscreen] find Format "gif"
[vokoscreen] ---End search formats---
 
[vokoscreen] ---Begin search Alsa capture device---
[vokoscreen] alsa_device_sample() in alsadevice.c: cannot open audio device hw:0,3 (Aucun fichier ou dossier de ce type)
[vokoscreen] Find CaptureCard: "[hw:0,3] HDA Intel HDMI"
[vokoscreen] alsa_device_sample() in alsadevice.c: open audio device hw:1,0 (Succès)
[vokoscreen] alsa_device_sample() in alsadevice.c: Samplerate = 44100
[vokoscreen] Find CaptureCard: "[hw:1,0] HDA Intel PCH"
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM 
[vokoscreen] alsa_device_sample() in alsadevice.c: cannot open audio device  (Aucun fichier ou dossier de ce type)
[vokoscreen] Find CaptureCard: "[] ThinkPad Console Audio Control"
[vokoscreen] ---End search Alsa capture device---
 
[vokoscreen] ---Begin search PulseAudio Capture Devices---
[vokoscreen] Find CaptureCard: "Monitor of Audio interne Digital Stereo (HDMI)" with device: "alsa_output.pci-0000_00_03.0.hdmi-stereo.monitor"
[vokoscreen] Find CaptureCard: "Monitor of Audio interne Stéréo analogique" with device: "alsa_output.pci-0000_00_1b.0.analog-stereo.monitor"
[vokoscreen] Find CaptureCard: "Audio interne Stéréo analogique" with device: "alsa_input.pci-0000_00_1b.0.analog-stereo"
[vokoscreen] ---End search PulseAudio Capture Devices---
 
[vokoscreen] recording fullscreen Display:  0
[vokoscreen] Executive command : "/usr/bin/ffmpeg -report -f x11grab -draw_mouse 1 -framerate 30 -video_size 1600x900 -i :0+0,0 -f pulse -i vokoscreenMix.monitor -pix_fmt yuv420p -c:v libx264 -preset veryfast -c:a libmp3lame -q:v 1 -s 1600x900 -f matroska /tmp/vokoscreen-tintin/vokoscreen-2016-02-14_07-23-50.mkv"
 
[vokoscreen] ---Begin Pulse loade module---
[vokoscreen] pactl load-module module-null-sink sink_name=vokoscreenMix  "34"
[vokoscreen] pactl load-module module-loopback source= "alsa_output.pci-0000_00_1b.0.analog-stereo.monitor" sink=vokoscreenMix number "35"
[vokoscreen] pactl load-module module-loopback source= "alsa_input.pci-0000_00_1b.0.analog-stereo" sink=vokoscreenMix number "36"
[vokoscreen] ---End Pulse loade module---
 
[vokoscreen] "/usr/bin/ffmpeg" is running and is ready for reading and writing
 
[vokoscreen] "/usr/bin/ffmpeg" is not running
[vokoscreen] ---Begin Pulse unload Module---
[vokoscreen] pactl unload-module number "36"
[vokoscreen] pactl unload-module number "35"
[vokoscreen] pactl unload-module number "34"
[vokoscreen] ---End Pulse unload Module---
 
[vokoscreen] ---Begin Pulse unload Module---
[vokoscreen] ---End Pulse unload Module---

**Comment by vkohaupt** [comment]
Ok, we are on the right way,  i continue work on this problem.

**Comment by vkohaupt** [comment]
Please test again from the current Branch:Master

**Comment by polpodan** [comment]
It now works as expected for fullscreen.
There was also a problem with zone capture.  It still exist.  It captures half the zone it supposed to capture.  Here's the output!

vokoscreen] Locale: "fr_FR"
[vokoscreen] Version: "2.4.16 Beta"
[vokoscreen] Qt version:  5.5.1
[vokoscreen] Operating system: "arch "
[vokoscreen] Desktop: "KDE"
[vokoscreen] asoundlib version: "1.1.0"
[vokoscreen] current icon-theme: "Antu"
 
[vokoscreen] ---Begin Search external tools---
[vokoscreen] Search ffmpeg ..... found "/usr/bin/ffmpeg" Version: "ffmpeg version 2.8.6 Copyright (c) 2000-2016 the FFmpeg developers"
[vokoscreen] Search pactl  ..... found Version: "8.0"
[vokoscreen] ---End search external tools---
 
[vokoscreen] ---Begin search Screen---
[vokoscreen] Number of screens: 1
[vokoscreen] Primary screen is: Display 1
[vokoscreen] VirtualDesktop: false
[vokoscreen] DevicePixelRatio: 2  (On normal displays is 1 and on Retina is 2)
[vokoscreen] "Display 1:  3200 x 1800"
[vokoscreen] ---End search Screen---
 
[vokoscreen] ---Begin Environment---
[vokoscreen] runs on DISPLAY ":0"
[vokoscreen] ---End Environment---
 
[vokoscreen] added device ("video0")
[vokoscreen] connected devices ("video0")
[vokoscreen] v4l2 device info  /dev/video0
[vokoscreen] ---Begin search Videoplayer---
[vokoscreen] Find Videoplayer : "/usr/bin/vlc"
[vokoscreen] Find Videoplayer : "/usr/bin/totem"
[vokoscreen] Find Videoplayer : "/usr/bin/smplayer"
[vokoscreen] Find Videoplayer : "/usr/bin/kdenlive"
[vokoscreen] Find Videoplayer : "/usr/bin/mpv"
[vokoscreen] ---End search Videoplayer---
 
[vokoscreen] ---Begin search GIFplayer---
[vokoscreen] Find GIFplayer : "firefox"
[vokoscreen] Find GIFplayer : "mpv"
[vokoscreen] Find GIFplayer : "chromium"
[vokoscreen] ---End search GIFoplayer---
 
[vokoscreen] ---Begin Pulse unload Module---
[vokoscreen] ---End Pulse unload Module---
 
[vokoscreen] ---Begin search video codec---
[vokoscreen] find Videocodec "libx264"
[vokoscreen] find Videocodec "libx265"
[vokoscreen] find Videocodec "mpeg4"
[vokoscreen] find Videocodec "huffyuv"
[vokoscreen] find Videocodec "gif"
[vokoscreen] ---End search video codec---
 
[vokoscreen] ---Begin search audio codec---
[vokoscreen] find Audiocodec "libmp3lame"
[vokoscreen] find Audiocodec "libvorbis"
[vokoscreen] find Audiocodec "pcm_s16le"
[vokoscreen] not found Audiocodec "libvo_aacenc"
[vokoscreen] find Audiocodec "aac"
[vokoscreen] ---End search audio codec---
 
[vokoscreen] ---Begin search formats---
[vokoscreen] find Format "mkv"
[vokoscreen] find Format "avi"
[vokoscreen] find Format "gif"
[vokoscreen] ---End search formats---
 
[vokoscreen] ---Begin search Alsa capture device---
[vokoscreen] alsa_device_sample() in alsadevice.c: cannot open audio device hw:0,3 (Aucun fichier ou dossier de ce type)
[vokoscreen] Find CaptureCard: "[hw:0,3] HDA Intel HDMI"
[vokoscreen] alsa_device_sample() in alsadevice.c: open audio device hw:1,0 (Succès)
[vokoscreen] alsa_device_sample() in alsadevice.c: Samplerate = 44100
[vokoscreen] Find CaptureCard: "[hw:1,0] HDA Intel PCH"
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM 
[vokoscreen] alsa_device_sample() in alsadevice.c: cannot open audio device  (Aucun fichier ou dossier de ce type)
[vokoscreen] Find CaptureCard: "[] ThinkPad Console Audio Control"
[vokoscreen] ---End search Alsa capture device---
 
[vokoscreen] ---Begin search PulseAudio Capture Devices---
[vokoscreen] Find CaptureCard: "Monitor of Audio interne Digital Stereo (HDMI)" with device: "alsa_output.pci-0000_00_03.0.hdmi-stereo.monitor"
[vokoscreen] Find CaptureCard: "Monitor of Audio interne Stéréo analogique" with device: "alsa_output.pci-0000_00_1b.0.analog-stereo.monitor"
[vokoscreen] Find CaptureCard: "Audio interne Stéréo analogique" with device: "alsa_input.pci-0000_00_1b.0.analog-stereo"
[vokoscreen] ---End search PulseAudio Capture Devices---
 
[vokoscreen] recording area
[vokoscreen] Executive command : "/usr/bin/ffmpeg -report -f x11grab -draw_mouse 1 -framerate 30 -video_size 1180x798 -i :0+394,73 -f pulse -i vokoscreenMix.monitor -pix_fmt yuv420p -c:v libx264 -preset veryfast -c:a libmp3lame -q:v 1 -s 1180x798 -f matroska /tmp/vokoscreen-tintin/vokoscreen-2016-02-14_10-08-38.mkv"
 
[vokoscreen] ---Begin Pulse loade module---
[vokoscreen] pactl load-module module-null-sink sink_name=vokoscreenMix  "34"
[vokoscreen] pactl load-module module-loopback source= "alsa_output.pci-0000_00_1b.0.analog-stereo.monitor" sink=vokoscreenMix number "35"
[vokoscreen] pactl load-module module-loopback source= "alsa_input.pci-0000_00_1b.0.analog-stereo" sink=vokoscreenMix number "36"
[vokoscreen] ---End Pulse loade module---
 
[vokoscreen] "/usr/bin/ffmpeg" is running and is ready for reading and writing
 
[vokoscreen] "/usr/bin/ffmpeg" is not running
 
[vokoscreen] ---Begin Pulse unload Module---
[vokoscreen] pactl unload-module number "36"
[vokoscreen] pactl unload-module number "35"
[vokoscreen] pactl unload-module number "34"
[vokoscreen] ---End Pulse unload Module---
 
[vokoscreen] File VERSION available
 
[vokoscreen] ---Begin Pulse unload Module---
[vokoscreen] ---End Pulse unload Module---

**Comment by obilodeau** [comment]
I did a video that highlighted two issues with High-DPI support:

1. Fullscreen recording doesn't record the appropriate resolution. My resolution: 3200x1800, vokoscreen resolution: 1600x900. This results in only portion of the screen to be recorded.
2. Magnifier is badly placed and doesn't follow the mouse pointer. On a multi-monitor setup, the magnified portion never leaves the monitor 1 even if the pointer is moved over to monitor 2.

* Using 2.5.0 on Arch
* Video: https://youtu.be/83NpsiYi7Mk
* Log: https://gist.github.com/obilodeau/9d08d0530f7ec1a7a1d841302bbda5fa

**Comment by polpodan** [comment]
Using Arch Linux either but with plasma 5.7.3 an everything's working fine (my resolution is also 3200x1800).  Must be Gnome's problem...

**Comment by vkohaupt** [comment]
OK, i want write you must select "All screens"

polpodan schrieb am 08.08.2016 um 22:11:

**Comment by vkohaupt** [comment]
![bild6](https://cloud.githubusercontent.com/assets/3152567/17495864/0db4647e-5dbb-11e6-95af-58494414c29a.png)

**Comment by vkohaupt** [comment]
Olivier Bilodeau schrieb am 08.08.2016 um 21:53:
> 2. Magnifier is badly placed and doesn't follow the mouse pointer. On a multi-monitor setup, the magnified portion never leaves the monitor 1 even if the pointer is moved over to monitor 2.

The Magnifier support to time only the first screen.

Maybe i extend for multi-monitor in the next version.

**Comment by vkohaupt** [comment]
Olivier Bilodeau schrieb am 08.08.2016 um 21:53:

> 2. Magnifier is badly placed and doesn't follow the mouse pointer.

I look the video, but not understand why the mouse -> magnifier offset.
I see the log from you and i mean its all ok.

Maybe a Problem with Qt 5.7
Can you install Qt 5.7.3, the User polpodan has write with this QT 
version is all ok.

Hmm... i have to time no idea.

**Comment by obilodeau** [comment]
> Can you install Qt 5.7.3, the User polpodan has write with this QT version is all ok.

He's using plasma 5.7.3 not Qt 5.7.3. Qt's latest version is 5.7.0 (which is the one I use). According to his logs he is using Qt 5.5.1 which is before Qt's Hi-DPI changes[1].

> OK, i want write you must select "All screens"

With "all screens" I still get an incomplete video.

> The Magnifier support to time only the first screen.

With one Hi-DPI screen, video records fine but magnifier is a little bit offset. See here: https://youtu.be/M1SlxMoROlo. Not a big problem though.

I think multi-monitor with one being Hi-DPI (laptop screen) and the other isn't is where the recording resolution problems are.

[1]: Qt 5.7 and 5.6 introduced a lot of changes regarding Hi-DPI displays. See here: https://blog.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6/

p.s.: I use the `QT_AUTO_SCREEN_SCALE_FACTOR=1` mentioned in the blog post. This makes most QT5 applications pretty.

**Comment by vkohaupt** [comment]
I have a table created with the features supported.
I see a lot of work for the next years
http://linuxecke.volkoh.de/vokoscreen/vokoscreen-download.html
