### ISSUE TITLE
provide log output in GUI

### ISSUE THREAD

**Issue by debuglevel** [vkohaupt/vokoscreen#132]
Currently, the log is only printed to stdout. If vokoscreen was not invoked via the shell, the log output is lost.
Instead, the log could _also_ be stored internally, so that it can be access via the GUI. For this I would suggest a link in the info tab which opens a log window.
This way, it might be more easy and obvious for people to include log output into issues.

**Comment by vkohaupt** [comment]
Yes this is to time a big problem. A prototyp exists, and i work on this 
in the next time.

**Comment by vkohaupt** [comment]
I have added a logwindow it is only for Qt5

Please test it from the current Master

Here a demo

http://linuxecke.volkoh.de/public/vokoscreen-clipboard.mkv
