### ISSUE TITLE
 ubuntu

### ISSUE THREAD

**Issue by Angelin** [vkohaupt/vokoscreen#136]

**Comment by vkohaupt** [comment]
Love angelin, it would be nice if you could write a few lines.

Volker

**Comment by scasic** [comment]
Can it be compiled for Linux Mint/Ubuntu? Current package in repository is quite old 1.9.02.
It would be great to have a tutorial how to compile it manually from sources.

**Comment by vkohaupt** [comment]
Please read the INSTALL file.

**Comment by Angelin** [comment]
Hey ,

I have currently all video encoding libraries in repository broken. I need to fix them as it a loop of dependencies broken. Will fix and update them. Then, will update you too

**Comment by vkohaupt** [comment]
I understand no word what you mean.
