### ISSUE TITLE
ffmpeg Unrecognized option 'draw_mouse'

### ISSUE THREAD

**Issue by scasic** [vkohaupt/vokoscreen#137]
When i hit start button recording immediately stops.

Log:
~~~
[vokoscreen] Executive command : "/usr/bin/ffmpeg -report -f x11grab -draw_mouse 1 -framerate 25 -video_size 800x600 -i :0+0,0  -pix_fmt yuv420p -c:v libx264 -preset veryfast  -q:v 1 -s 800x600 -f matroska /tmp/vokoscreen-scs/vokoscreen-2016-03-14_22-36-10.mkv" 

[vokoscreen] "/usr/bin/ffmpeg" is running and is ready for reading and writing 
 
[vokoscreen] "/usr/bin/ffmpeg" is not running 
~~~

If i run ffmpeg from console it returns an error:
~~~
Unrecognized option 'draw_mouse'.
Error splitting the argument list: Option not found
~~~

Does it mean that ffmpeg version is not compatible with vokoscreen?
ffmpeg version N-78590-g5590ab4 Copyright (c) 2000-2016

**Comment by vkohaupt** [comment]
Please start ffmpeg without options and give the output here.

**Comment by scasic** [comment]
~~~
 $ /usr/bin/ffmpeg
ffmpeg version N-78590-g5590ab4 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04.1)
  configuration: --extra-libs=-ldl --prefix=/opt/ffmpeg --mandir=/usr/share/man --enable-avresample --disable-debug --enable-nonfree --enable-gpl --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb --disable-decoder=amrnb --disable-decoder=amrwb --enable-libpulse --enable-libfreetype --enable-gnutls --enable-libx264 --enable-libx265 --enable-libfdk-aac --enable-libvorbis --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libspeex --enable-libass --enable-avisynth --enable-libsoxr --enable-libxvid --enable-libvidstab
  libavutil      55. 18.100 / 55. 18.100
  libavcodec     57. 24.103 / 57. 24.103
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 32.100 /  6. 32.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
~~~

**Comment by vkohaupt** [comment]
Your ffmpeg is not compiled with the option --enable-x11grab
see my ffmpeg output on the last option

Get a compatible ffmpeg version or you can download ffmpeg from my Homepage
http://linuxecke.volkoh.de/vokoscreen/vokoscreen-troubleshooting.html


ffmpeg version 3.0 Copyright (c) 2000-2016 the FFmpeg developers
   built with gcc 4.8 (SUSE Linux)
   configuration: --prefix=/usr --libdir=/usr/lib64 
--shlibdir=/usr/lib64 --incdir=/usr/include/ffmpeg 
--extra-cflags='-fmessage-length=0 -grecord-gcc-switches -O2 -Wall 
-D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables 
-fasynchronous-unwind-tables -g' --optflags='-fmessage-length=0 
-grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector 
-funwind-tables -fasynchronous-unwind-tables -g' --disable-htmlpages 
--enable-pic --disable-stripping --enable-shared --disable-static 
--enable-runtime-cpudetect --enable-gpl --disable-openssl 
--enable-avresample --enable-libcdio --enable-gnutls --enable-ladspa 
--enable-libass --enable-libbluray --enable-libcelt --enable-libcdio 
--enable-libdc1394 --enable-libfreetype --enable-libgsm 
--enable-libopenjpeg --enable-libopus --enable-libpulse 
--enable-libschroedinger --enable-libspeex --enable-libtheora 
--enable-libvorbis --enable-libvpx --enable-libwebp --enable-pic 
--enable-pthreads --enable-vaapi --enable-vdpau --disable-decoder=dca 
--enable-libdcadec --enable-libmp3lame --enable-libopencore-amrnb 
--enable-libopencore-amrwb --enable-version3 --enable-libtwolame 
--enable-libx264 --enable-libx265 --enable-libxvid --enable-x11grab
