### ISSUE TITLE
Missing right ALSA recording device

### ISSUE THREAD

**Issue by Ilya87** [vkohaupt/vokoscreen#139]
For recording sound from my speakers I use Loopback, but vokoscreen see only hw:0,0 not hw:0,1 (SimpleScreenRecorder let me choose hw:0,1). Capturing from 0:0 device provides obviously no sound.

**Comment by tuxmuck** [comment]
Which distribution?
Which version of vokoscreen?

Start vokoscreen from console and post here the output.

**Comment by Ilya87** [comment]
Arch Linux x86_64
Version: "2.4.17 Beta"

[vokoscreen] Locale: "ru_RU"
[vokoscreen] Version: "2.4.17 Beta" 
[vokoscreen] Qt version:  5.5.1 
[vokoscreen] Operating system: "arch " 
[vokoscreen] Desktop: "LXQt" 
[vokoscreen] asoundlib version: "1.1.0" 
[vokoscreen] current icon-theme: "elementary-xfce" 
  
[vokoscreen] ---Begin Search external tools--- 
[vokoscreen] Search ffmpeg ..... found "/usr/bin/ffmpeg" Version: "ffmpeg version N-79087-gefa98cd Copyright (c) 2000-2016 the FFmpeg developers" 
[vokoscreen] Search pactl  ..... found Version: "8.0" 
[vokoscreen] ---End search external tools--- 
  
[vokoscreen] ---Begin search Screen--- 
[vokoscreen] Number of screens: 2 
[vokoscreen] Primary screen is: Display 1 
[vokoscreen] VirtualDesktop: true 
[vokoscreen] DevicePixelRatio: 1  (Normal displays is 1, Retina display is 2) 
[vokoscreen] "Display 1:  1280 x 1024" 
[vokoscreen] "Display 2:  1920 x 1080" 
[vokoscreen] ---End search Screen--- 
  
[vokoscreen] ---Begin Environment--- 
[vokoscreen] runs on DISPLAY ":0" 
[vokoscreen] ---End Environment--- 
  
[vokoscreen] ---Begin search Videoplayer--- 
[vokoscreen] Find Videoplayer : "/usr/bin/smplayer" 
[vokoscreen] ---End search Videoplayer--- 
  
[vokoscreen] ---Begin search GIFplayer--- 
[vokoscreen] ---End search GIFoplayer--- 
  
Warning: QObject::connect: No such slot screencast::windowMove() ((null):0, (null))
Warning: QObject::connect:  (receiver name: 'screencast') ((null):0, (null))
[vokoscreen] ---Begin Pulse unload Module--- 
[vokoscreen] ---End Pulse unload Module--- 
  
[vokoscreen] ---Begin search video codec--- 
[vokoscreen] find Videocodec "libx264" 
[vokoscreen] find Videocodec "libx265" 
[vokoscreen] find Videocodec "mpeg4" 
[vokoscreen] find Videocodec "huffyuv" 
[vokoscreen] find Videocodec "gif" 
[vokoscreen] ---End search video codec--- 
  
[vokoscreen] ---Begin search audio codec--- 
[vokoscreen] find Audiocodec "libmp3lame" 
[vokoscreen] find Audiocodec "libvorbis" 
[vokoscreen] find Audiocodec "pcm_s16le" 
[vokoscreen] not found Audiocodec "libvo_aacenc" 
[vokoscreen] find Audiocodec "aac" 
[vokoscreen] ---End search audio codec--- 
  
[vokoscreen] ---Begin search formats--- 
[vokoscreen] find Format "mkv" 
[vokoscreen] find Format "mp4" 
[vokoscreen] find Format "gif" 
[vokoscreen] ---End search formats--- 
  
[vokoscreen] ---Begin search devices--- 
[vokoscreen] find device "x11grab" 
[vokoscreen] ---End search devices--- 
  
[vokoscreen] ---Begin search Alsa capture device--- 
[vokoscreen] Find CaptureCard: "[hw:0,0] Loopback" 
[vokoscreen] Find CaptureCard: "[hw:1,0] HDA Intel PCH" 
[vokoscreen] alsa_device_sample() in alsadevice.c: cannot open audio device hw:2,3 (Нет такого файла или каталога)
[vokoscreen] Find CaptureCard: "[hw:2,3] HDA NVidia" 
[vokoscreen] ---End search Alsa capture device--- 
  
[vokoscreen] ---Begin search PulseAudio Capture Devices--- 
[vokoscreen] ---End search PulseAudio Capture Devices---

**Comment by Ilya87** [comment]
In the latest git master version all stays the same. I can't record desktop sound.

**Comment by vkohaupt** [comment]
a few days ago I started to integrate alsa Subdevices. When I'm done, I 
give notice so that you can test.

Volker

**Comment by vkohaupt** [comment]
Ups, i mean devices not subdevices.
vokoscreen identify to time only "cards" and in the next step i want to 
implement "devices"
