### ISSUE TITLE
Ubuntu deb packages for beta releases?

### ISSUE THREAD

**Issue by orschiro** [vkohaupt/vokoscreen#140]
Dear all, 

Are there Ubuntu deb packages available for the latest Beta releases?

I would love to test the latest gif support. :-)

Thankfully,

~Robert

**Comment by vkohaupt** [comment]
I have make a packet for all disributions
http://linuxecke.volkoh.de/vokoscreen/vokoscreen-beta.html

**Comment by orschiro** [comment]
@vkohaupt,

This is great! 

It would be furthermore fantastic if someone could add a dedicated `deb` package to this list. :smile: 

~Robert

**Comment by vkohaupt** [comment]
Hi Robert,
 From my side, gives no other distribution-related packages.
It's too much work to create and maintain.

Sorry.
