### ISSUE TITLE
Not saving video when you pause it!

### ISSUE THREAD

**Issue by hossein4heydari** [vkohaupt/vokoscreen#141]
Hello
I am using Arch Linux and I installed vokoscreen, it is good but when user pause the video the video will be lost and no more we can have it!

**Comment by vkohaupt** [comment]
Hello,

in the last two week i write new code for Windowsrecord, in this time 
pause was broken, please test with the last Branch:Master

**Comment by hossein4heydari** [comment]
Why don't you put new version at AUR?
Which file should "make"? please talk alittle about installing it from source code!

**Comment by vkohaupt** [comment]
I not understand, wath is AUR?

**Comment by debuglevel** [comment]
AUR ist the archlinux user repository. The package "vokoscreen" as well as "vokoscreen-git" is maintained by AlfredoRamos. You may address him if the package is out of date. https://aur.archlinux.org/packages/vokoscreen/ https://aur.archlinux.org/packages/vokoscreen-git/

You can compile vokoscreen by yourself as described in the INSTALL file: https://github.com/vkohaupt/vokoscreen/blob/master/INSTALL

**Comment by hossein4heydari** [comment]
The package in AUR is not the last version, please put the Updates for that so I can use this application!

**Comment by tuxmuck** [comment]
Wrong place - we are not the AUR maintainers ! For this, contact Alfredo Ramos, he is the maintainer.
The current version is 2.4.0.
Each version over it is beta -

**Comment by AlfredoRamos** [comment]
Maintainer here.

@hossein4heydari we can continue the discussion on the Arch forum.
- https://bbs.archlinux.org/viewtopic.php?pid=1622742

If the issue has been fixed, then this is not the right place to report that, thus the issue can be closed ( @vkohaupt ).

**Comment by tuxmuck** [comment]
Thank you Alfredo -
