### ISSUE TITLE
[IMP] Better video and sound quality

### ISSUE THREAD

**Issue by rdmachadog** [vkohaupt/vokoscreen#142]
In any configuration that i tried from the GUI, all of them, I can't make a good video for my project. I was looking for a configuration file to modify the properties to generate a RAW video or an mkv one with a better resolution (no more frames) but i haven't found it yet.

1.- Is there a configuration file to do that?
2.- If 1.- (it exists) what must be changed?

TODO: a configuration file in order to hack the vokoscreen using ffmpeg could generate the best screen recorder ever, IMHO

**Comment by rdmachadog** [comment]
For example

From: https://trac.ffmpeg.org/wiki/Capture/Desktop

**Lossless recording** 

If you want a perfect recording of your desktop, x264 can help. Use lossless encoding, e.g.:

ffmpeg -video_size 1920x1080 -framerate 30 -f x11grab -i :0.0 -c:v libx264 -qp 0 -preset ultrafast capture.mkv
-qp 0 tells x264 to encode in lossless mode, -preset ultrafast advises it to do so fast.

The encoder should be fast enough on most modern hardware to record without any framedrop, and even leave enough CPU headroom for other applications.

If you're going to archive the recording or are concerned about file size, re-encode it losslessly again but with a slower preset. Note that since the initial recording was lossless, and the re-encode is lossless too, no quality loss is introduced in this process in any way.

ffmpeg -i capture.mkv -c:v libx264 -qp 0 -preset veryslow capture_smaller.mkv

**Comment by vkohaupt** [comment]
Hi,

which vokoscreen have you?

**Comment by vkohaupt** [comment]
Hi Ruben,

what you mean with "better resolution"

**Comment by rdmachadog** [comment]
Hi,

I have vokoscreen 2.4.0

When i said "better resolution" means lossless quality.

Which are the parameters you use to make an mkv video?

I don't know how to degree my tests technically but i attach 2 resulting images, the first one is a capture from vokoscreen using mkv and the same resolution of my screen, the second one i used via CLI ffmpeg with the following: 

ffmpeg -video_size 1920x1080 -framerate 13 -f x11grab -i :0.0 -c:v libx264 -qp 0 -preset ultrafast capture2.mkv

IMHO: the second one has a better quality, vivid colors, less "garbage" in the background (lost dots) and more defined fonts

Captured with Vokoscreen:

![captured-with-vokoscreen-2 4 0-mkv-parameters-fitting-my screen-resolution](https://cloud.githubusercontent.com/assets/16785686/15395162/66c0f86c-1da0-11e6-99ac-0596a3e64c3d.png)

Capture via CLI with ffmpeg parameters:

![captured-directly with-ffmpeg-lossless-parameters](https://cloud.githubusercontent.com/assets/16785686/15395210/93cae9da-1da0-11e6-9ec8-4cba89bc7b03.png)

**Comment by rdmachadog** [comment]
Very little diferencies

**Comment by tuxmuck** [comment]
Very little !

**Comment by rdmachadog** [comment]
My others advice is refered by the folowing:

If you used a config file that the user might modified it would be better for a tech or advanced user. We could use more ffmpeg options.

Another good way to do an advance option is using a modifiable text field inside vokoscreen GUI like it is used in WINFF (This app use ffmpeg too)

See these images:

![winff_016](https://cloud.githubusercontent.com/assets/16785686/15395621/44397128-1da2-11e6-942a-95833b31991b.png)

![winff_017](https://cloud.githubusercontent.com/assets/16785686/15395622/443abe70-1da2-11e6-80c5-bcff3bab9576.png)

**Comment by vkohaupt** [comment]
Very little?

I see nothing, not on text, not on Picture.

Please give a point wer is a difference.



Ruben Dario Machado schrieb am 19.05.2016 um 15:36:

**Comment by rdmachadog** [comment]
I hope you can see the light differences now

**Vokoscreen:**

![vokoscreen-2016-05-19_16-57-16 mkv - vlc media player_018](https://cloud.githubusercontent.com/assets/16785686/15410259/92f41206-1de2-11e6-9dce-68960eb5502e.png)

**ffmpeg via CLI:**
using: ffmpeg -video_size 1920x1080 -framerate 13 -f x11grab -i :0.0 -c:v libx264 -qp 0 -preset ultrafast capture.mkv

![consola mkv - vlc media player_019](https://cloud.githubusercontent.com/assets/16785686/15410297/c63818a6-1de2-11e6-9375-87bff9c01716.png)

**Comparison:**

![vokoandclicomparison](https://cloud.githubusercontent.com/assets/16785686/15410338/f2c3bfec-1de2-11e6-948d-9876248c8fba.png)

**Comment by rdmachadog** [comment]
I think that the modifications must be done in screencast.cpp

This code for example
-----------------------------------------------------------------------------------

ffmpegString = recordApplikation + " "
               + "-report" + " "
               + "-f x11grab" + " "
               + noMouse() + " "
               + framerate + " "
               + "-video_size" + " " + getRecordWidth() + "x" + getRecordHeight() + " "
               + "-i " + DISPLAY + "+" + deltaX + "," + deltaY + " "
               + myAlsa() + " "
               + "-pix_fmt yuv420p" + " "
               + "-c:v" + " " + myVcodec + " "
               + myAcodec() + " "
               + "-q:v 1" + " "
               + "-s" + " " + getRecordWidth() + "x" + getRecordHeight() + " "
               + "-f" + " " + myUi.VideoContainerComboBox->itemData( myUi.VideoContainerComboBox->currentIndex() ).toString() + " ";
  
  startRecord( PathTempLocation() + QDir::separator() + nameInMoviesLocation );
}

------------------------------------------------------------------

**Comment by debuglevel** [comment]
For beta testing, I would recommand a new x264 loseless codec entry in vokoscreen. This would give the chance to gather experience with loseless x264. It's quite possible, that loseless x264 results in smaller files, better quality and less CPU consumption (as the recoding should be way less complex).

Expert-Configuration might also be a nice feature for power users - but I think we should focus on how we can improve vokoscreen for regular users without that they need to hack around in some ugly config files.

**Comment by rdmachadog** [comment]
Thanks for you consideration.

I'll be waiting for the new beta version.

**Comment by vkohaupt** [comment]
I have looked closer to me, and you've convinced me, in the next betas i 
code that.

**Comment by vkohaupt** [comment]
vokoscreen-2.4.27-beta is ready, please test lossless

https://github.com/vkohaupt/vokoscreen/commit/476dd7c5b68af21fbe08f7f59eb3e509054a23d4

**Comment by rdmachadog** [comment]
Please i need some help


I read the INSTALL doc, I have installed qt-defaults, qt5-dev-tools, alsa-base and alsa-utils but when i try to RUN qmake this ERROR appears:

rdmachadog@4ll1n0n3:~/vokoscreen-2.4.27-beta$ qmake
sh: 1: lrelease-qt5: not found
Project ERROR: alsa development package not found


![image](https://cloud.githubusercontent.com/assets/16785686/15445563/a592d54e-1eca-11e6-93c5-0b5d477c0f9c.png)

What do you think about that?
What is it missing?

**Comment by vkohaupt** [comment]
I devlop under openSUSE, in Ubuntu the filename "lrelease-qt5" is "lrelease"
http://packages.ubuntu.com/de/trusty/amd64/qttools5-dev-tools/filelist
Please go in the sourcecode from vokoscreen and open the file 
vokoscreen.pro and change all "lrelease-qt5" to "lrelease"
And for alsa you need alsa dev package

The easy way download the *.tar.gz from
http://linuxecke.volkoh.de/vokoscreen/vokoscreen-beta.html

**Comment by rdmachadog** [comment]
![vokoandclicomparison](https://cloud.githubusercontent.com/assets/16785686/15485407/fdde483e-210c-11e6-883e-d04a604a2756.png)

As result we have a real HIGH QUALITY VIDEO!!! with the new Vokoscreen beta (and other improves like to capture as a gif).

You ROCK!!!

Vokoscreen ROCKS!!!

Thank you

**Comment by debuglevel** [comment]
Thank you for testing this issue!

Do you have any information about how big the resulting video files become in comparison? (e.g. when you capture a 30 seconds lasting sequence of a terminal, file explorer and browser).
Additionally it would be interessting how much the CPU is used during each capturing session.
