### ISSUE TITLE
Recording window area, rather than the indicated window.

### ISSUE THREAD

**Issue by myswiat** [vkohaupt/vokoscreen#143]
When I check the game window, vokocreen, records the area, but as a region, not as a game window. The problem is that the movement of the window / shift (check the recording window, and not selected manually in your area) vokoscreen recording continues but the area which drew a window, and does not follow the specified window (like a obs-studio).
What is the problem?
Described above ailments vokoscreen. When recording a specified window, sometimes it is necessary to postpone or move. And here the problem is that Vokoscreen will record the area that designated window, not advisable window.

This causes a problem such as that by selecting the game window, vokoscreen, somehow selects the panel (which is also located on the recording), even though the panel and window games do not touch each other or do not overlap each other.

It excludes any recording guides, because at the recording window, or games can and are moved and vokoscreen still recording, but not the window, and leaves only the selected area. And that means a lack of functionality and usefulness in this topic.

**Comment by vkohaupt** [comment]
Please download vokoscreen-2.4.27-beta.tar.gz and check once more

http://linuxecke.volkoh.de/vokoscreen/vokoscreen-beta.html

**Comment by myswiat** [comment]
I installed the beta version and the problem still exists.
Just as I downloaded and installed version of git, and the problem still exists.

**Comment by vkohaupt** [comment]
You move a window but no record the Windows, its record the background 
of the old Place from the window?

I test under the Desktops plasma5, Unity and Gnome, and yes under Gnome 
the functionality is broken.

You uses Gnome?

**Comment by myswiat** [comment]
Desktop: LXDE 
Manager window: openbox

**Comment by vkohaupt** [comment]
tell me the Distribution, then want test in VirtualBox

**Comment by myswiat** [comment]
Ubuntu 16.10 (Daily Build) 64 bit

**Comment by vkohaupt** [comment]
problem solved, is fixed in 2.4.28-beta

http://linuxecke.volkoh.de/vokoscreen/vokoscreen-beta.html

or

https://github.com/vkohaupt/vokoscreen

**Comment by myswiat** [comment]
The zone under the window .
The upper area of the game will be cut, especially since I raised the window to the edge is not in contact with the panel (but still it is recorded).

Proof:
https://youtu.be/msY4idqRxRE
https://youtu.be/CfZ-j3lTKdY

It seems to me that vokoscreen has problems with the recording of games that run under wine (windows game), but it's a little strange ailment.
