### ISSUE TITLE
Multiarch installation paths for architecture independent data (/usr/share)

### ISSUE THREAD

**Issue by tgurr** [vkohaupt/vokoscreen#144]
vokoscreen should install the architecture independent data outside the prefix, for example on a multiarch layout where the prefix is /usr/{host-triplet} it currently it installs the architecture independent data to e.g. /usr/x86_64-pc-linux-gnu/share/{applications,man,pixmaps} instead of /usr/share/{applications,man,pixmaps}. Sorry for not providing any patch but I'm not really familiar with the Qt build system (for CMake there is ${CMAKE_INSTALL_DATAROOTDIR} handling this case).

**Comment by vkohaupt** [comment]
THe standard is /usr/share/{applications,man,pixmaps}
see the file vokoscreen.pro
[..]
[..]
# Install paths
isEmpty(PREFIX) {
     PREFIX = /usr
}
image.path = $$PREFIX/share/pixmaps
image.files += applications/vokoscreen.png
desktop.path = $$PREFIX/share/applications
desktop.files += applications/vokoscreen.desktop
man.path = $$PREFIX/share
man.files += man
target.path = $$PREFIX/bin
[..]
[..]

if you want other path you can give by install a PREFIX.

**Comment by tgurr** [comment]
Sorry maybe I failed to explain properly, on a multiarch setup the prefix is /usr/{host-triplet}, for example /usr/x86_64-pc-linux-gnu and/or /usr/i686-pc-linux-gnu and the binaries have to go there (/usr/x86_64-pc-linux-gnu/bin, /usr/i686-pc-linux-gnu/bin and so on).
The shared data however does still has to go to /usr/share since it is not architecture dependent so we need a way to set specify the architecture dependent stuff seperately from the architecture independent stuff.

More detailed explenations can be found here:
https://exherbo.org/docs/multiarch-pr.html

Small excerpt of examples of such fixes which went upstream:
https://git.reviewboard.kde.org/r/123232/
https://git.reviewboard.kde.org/r/126422/
https://bugs.scribus.net/view.php?id=13035

**Comment by vkohaupt** [comment]
Thanks for the hint, but to time i not understand this stuff, i must 
read any more.

**Comment by tgurr** [comment]
I've created a pull request with a possible solution: https://github.com/vkohaupt/vokoscreen/pull/148
If SHARE_INSTALL_PREFIX is not set everything should work like before and if SHARE_INSTALL_PREFIX is set it allows to install the shared data outside of the prefix.
