### ISSUE TITLE
Screen region capturing in full screen width

### ISSUE THREAD

**Issue by tgurr** [vkohaupt/vokoscreen#145]
My screen is 1920x1200 and when I set the capture region of vokoscreen to 1920x1080 it works well:

![vokoscreen-1920x1080_before_restart](https://cloud.githubusercontent.com/assets/414984/15825291/7381a634-2c03-11e6-96f9-379d7f9d53b2.png)

However every time vokoscreen is restarted it doesn't remember the capture region correctly and needs manual adjustment again since it shifts it to the right (probably to be able to display the full green circles again):

![vokoscreen-1920x1080_after_restart](https://cloud.githubusercontent.com/assets/414984/15825294/79f66338-2c03-11e6-85d4-9f834391f121.png)

**Comment by vkohaupt** [comment]
Ok, i see the bug and can reproduce, i want fix it.

**Comment by vkohaupt** [comment]
found the bug, it was an unsigend integer but we need sigend integer

please test from github the 2.4.29-beta
or from here
http://linuxecke.volkoh.de/vokoscreen/vokoscreen-beta.html

thanks for your help

**Comment by tgurr** [comment]
I confirm that 2.4.29-beta fixes this issue for me, thank you very much!

**Comment by tgurr** [comment]
Closing as there is now a stable release (2.5.0) containing the fix.
