### ISSUE TITLE
Add option to set the capture duration

### ISSUE THREAD

**Issue by tgurr** [vkohaupt/vokoscreen#146]
It would be very handy to have the possibility to specify the duration of the capture process and not having to worry about manually stopping it.

**Comment by vkohaupt** [comment]
Yes i can do, but in the next weeks i fix only bugs. I want 
vokoscreen-2.5.0 released in middle or end of this month.

**Comment by tpnsolutions** [comment]
Is there any news on this new option being added?

**Comment by vkohaupt** [comment]
Peter Knowles schrieb am 10.02.2017 um 13:25:
> Is there any news on this new option being added?

i have not forgotten, but to time i lazy to program and make other stuff 
with the Maschine.
