### ISSUE TITLE
Failed to start on Fedora 23 with the latest updates as per June 9 2016

### ISSUE THREAD

**Issue by chapati** [vkohaupt/vokoscreen#150]
$ vokoscreen

[vokoscreen] Locale: "en_US" 
[vokoscreen] Version: "2.4.0" 
[vokoscreen] Qt version:  4.8.7 
[vokoscreen] Operating system: "fedora 23" 
[vokoscreen] asoundlib version: "1.1.1" 
[vokoscreen] current icon-theme: "Moka" 

[vokoscreen] ---Begin Search external tools--- 
Segmentation fault (core dumped)

journalctl -e
#1  0x00005607a6f026c3 _ZN10screencast22searchExternalProgramsEv (vokoscreen)
#2  0x00005607a6f0528b _ZN10screencastC1Ev (vokoscreen)
#3  0x00005607a6eedcdf main (vokoscreen)

 #4  0x00007f2b31e1c580 __libc_start_main (libc.so.6)
#5  0x00005607a6eedfd9 _start (vokoscreen)

Stack trace of thread 6943:
#0  0x00007f2b31ef2b1d poll (libc.so.6)
#1  0x00007f2b32e3eb48 _Z12qt_safe_pollP6pollfdiib (libQtCore.so.4)
#2  0x00007f2b32dec608 _ZN15QProcessManager3runEv (libQtCore.so.4)
#3  0x00007f2b32d0238c _ZN14QThreadPrivate5startEPv (libQtCore.so.4)
#4  0x00007f2b32a5f61a start_thread (libpthread.so.0)
#5  0x00007f2b31efe59d __clone (libc.so.6)

(bamfdaemon:3280): GLib-CRITICAL *_: Source ID 1672 was not found when attempting to remove it
(bamfdaemon:3280): GLib-CRITICAL *_: Source ID 1674 was not found when attempting to remove it
Jun 10 01:58:41 audit[6992]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=1 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=6992
Jun 10 01:58:41 kernel: vokoscreen[6992]: segfault at 6e006f ip 0000561275a0623d sp 00007ffd96e0db10 error 6 in vokoscreen[5612759d9000+14e00
Jun 10 01:58:43 oppc 

systemd-coredump[6995]: Process 6992 (vokoscreen) of user 1000 dumped core.

Stack trace of thread 6992:
#0  0x0000561275a0623d _ZN10screencast16getFfmpegVersionEv (vokoscreen)
#1  0x0000561275a066c3 _ZN10screencast22searchExternalProgramsEv (vokoscreen)
#2  0x0000561275a0928b _ZN10screencastC1Ev (vokoscreen)

 #3  0x00005612759f1cdf main (vokoscreen)
#4  0x00007fcccddd1580 __libc_start_main (libc.so.6)
#5  0x00005612759f1fd9 _start (vokoscreen)

Stack trace of thread 6993:
#0  0x00007fcccdea7b1d poll (libc.so.6)

 #1  0x00007fcccedf3b48 _Z12qt_safe_pollP6pollfdiib (libQtCore.so.4)
#2  0x00007fccceda1608 _ZN15QProcessManager3runEv (libQtCore.so.4)
#3  0x00007fcccecb738c _ZN14QThreadPrivate5startEPv (libQtCore.so.4)
#4  0x00007fcccea1461a start_thread (libpthread.so.0)
#5  0x00007fcccdeb359d __clone (libc.so.6)

[voko-6992.dmp.tar.gz](https://github.com/vkohaupt/vokoscreen/files/307742/voko-6992.dmp.tar.gz)

**Comment by vkohaupt** [comment]
Hi chapati,

i see in the stack trace qt4 libs, but vokoscreen required Qt5 libs

**Comment by vkohaupt** [comment]
Hi chapati,

if you start vokoscreen from a terminal, is there a little output?

**Comment by chapati** [comment]
Hi @vkohaupt, all I've able collect is above between $vokoscreen and crash dump message. I've tried to uninstall/install voko and got the same crash. Package is the following:

vokoscreen  x86_64 2.4.0-1.fc23 rpmfusion-free-updates 975 k

Dependencies:

$ ldd $(which vokoscreen)
	linux-vdso.so.1 (0x00007ffe177e2000)
	libQxtCore.so.0 => /lib64/libQxtCore.so.0 (0x00007f64d0dc0000)
	libQxtGui.so.0 => /lib64/libQxtGui.so.0 (0x00007f64d0ae2000)
	libQtSolutions_SingleApplication-2.6.so.1 => /lib64/libQtSolutions_SingleApplication-2.6.so.1 (0x00007f64d08d8000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007f64d0598000)
	libasound.so.2 => /lib64/libasound.so.2 (0x00007f64d02a1000)
	libv4l2.so.0 => /lib64/libv4l2.so.0 (0x00007f64d0091000)
	libv4lconvert.so.0 => /lib64/libv4lconvert.so.0 (0x00007f64cfe17000)
	libQtTest.so.4 => /lib64/libQtTest.so.4 (0x00007f64cfbf0000)
	libQtGui.so.4 => /lib64/libQtGui.so.4 (0x00007f64ceeb6000)
	libQtNetwork.so.4 => /lib64/libQtNetwork.so.4 (0x00007f64ceb61000)
	libQtCore.so.4 => /lib64/libQtCore.so.4 (0x00007f64ce65a000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f64ce43b000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f64ce0b9000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f64cddb7000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f64cdb9f000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f64cd7de000)
	libXrandr.so.2 => /lib64/libXrandr.so.2 (0x00007f64cd5d3000)
	libQtSolutions_LockedFile-2.4.so.1 => /lib64/libQtSolutions_LockedFile-2.4.so.1 (0x00007f64cd3ce000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f64cd1ac000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f64ccfa8000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f64ccd9f000)
	/lib64/ld-linux-x86-64.so.2 (0x00005594e98f8000)
	libjpeg.so.62 => /lib64/libjpeg.so.62 (0x00007f64ccb46000)
	libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00007f64cc943000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f64cc60a000)
	libpng16.so.16 => /lib64/libpng16.so.16 (0x00007f64cc3d7000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f64cc1c1000)
	libfreetype.so.6 => /usr/lib64/freetype-freeworld/libfreetype.so.6 (0x00007f64cbf16000)
	libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007f64cbcc4000)
	libSM.so.6 => /lib64/libSM.so.6 (0x00007f64cbabb000)
	libICE.so.6 => /lib64/libICE.so.6 (0x00007f64cb89e000)
	libXi.so.6 => /lib64/libXi.so.6 (0x00007f64cb68e000)
	libXrender.so.1 => /lib64/libXrender.so.1 (0x00007f64cb483000)
	libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00007f64cb27c000)
	libXcursor.so.1 => /lib64/libXcursor.so.1 (0x00007f64cb071000)
	libXinerama.so.1 => /lib64/libXinerama.so.1 (0x00007f64cae6e000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007f64cac29000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007f64caa17000)
	libssl.so.10 => /lib64/libssl.so.10 (0x00007f64ca7a5000)
	libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f64ca344000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007f64ca140000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f64c9f2f000)
	libffi.so.6 => /lib64/libffi.so.6 (0x00007f64c9d27000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f64c9b22000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f64c98f7000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f64c96a9000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f64c93c1000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f64c91bc000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f64c8f8a000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f64c8d7a000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f64c8b76000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f64c895b000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f64c8737000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f64c84c7000)

Seems that I have an older version which uses Qt4 and nothing is missing. 
I would appreciate any help. Really missing your nice piece of software.
Thank you.

**Comment by chapati** [comment]
Qt5 is installed on my PC as well:

$sudo dnf list qt5*
Last metadata expiration check: 0:22:33 ago on Fri Jun 10 05:11:52 2016.
Installed Packages
qt5-qtbase.x86_64 5.6.0-13.fc23                                          @updates
qt5-qtbase-common.noarch 5.6.0-13.fc23                                          @updates
qt5-qtbase-gui.x86_64 5.6.0-13.fc23                                          @updates
qt5-qtdeclarative.x86_64 5.6.0-5.fc23                                           @updates
qt5-qttools-common.noarch 5.6.0-3.fc23                                           @updates
qt5-qttools-libs-designer.x86_64  5.6.0-3.fc23                                           @updates
qt5-qtwayland.x86_64 5.6.0-9.fc23                                           @updates
qt5-qtx11extras.x86_64  5.6.0-3.fc23                                           @updates
qt5-qtxmlpatterns.x86_64 5.6.0-4.fc23                                           @updates

**Comment by chapati** [comment]
By the way it worked a few weeks ago. The only qt-based thing i've installed since is calligra-krita. May be it is connected somehow.

**Comment by vkohaupt** [comment]
Hi chapati,

/*Zitat*/
libQxtCore.so.0 => /lib64/libQxtCore.so.0 (0x00007f64d0dc0000)
libQxtGui.so.0 => /lib64/libQxtGui.so.0 (0x00007f64d0ae2000)
libQtSolutions_SingleApplication-2.6.so.1 => 
/lib64/libQtSolutions_SingleApplication-2.6.so.1 (0x00007f64d08d8000)
/*Zit
at*/

this three libs are not original vokoscreen, fedora maintair has patched 
vokoscreen. Please tell the fedora maintainer she must full tests 
vokoscreen self. I can´t give support and bugfixes vor my site.

If you want a running vokoscreen please download here.

http://linuxecke.volkoh.de/vokoscreen/vokoscreen-beta.html

**Comment by chapati** [comment]
OK, got it. Thanks for the update @vkohaupt, your recommendation and your care!
At least I know where to go now.

**Comment by leigh123linux** [comment]
@chapati 

```
[vokoscreen] ---Begin Search external tools---
Segmentation fault (core dumped)

https://bugzilla.rpmfusion.org/show_bug.cgi?id=4188

```
Try installing ffmpeg and lame

```
dnf install ffmpeg lame
```

**Comment by leigh123linux** [comment]
@vkohaupt 

vokoscreen shouldn't Segmentation fault because it can't find ffmpeg or lame when looking for external tools.
It should warn that the ffmpeg and lame binaries aren't installed instead.

**Comment by vkohaupt** [comment]
leigh123linux schrieb am 19.08.2016 um 11:18:
> @vkohaupt
>
> vokoscreen shouldn't Segmentation fault because it can't find ffmpeg or lame when looking for external tools.
> It should warn that the ffmpeg and lame binaries aren't installed instead.

Vokoscreen 2.4.0?

I have dozen Bugs eliminated in vokoscreen 2.5.0, please say to the 
Fedora Maintainer she can update to the new Version.

If you want a runnable Version you can Download here.
http://linuxecke.volkoh.de/vokoscreen/vokoscreen-download.html
