### ISSUE TITLE
Ubuntu Deb Installer for 2.5.0 release?

### ISSUE THREAD

**Issue by orschiro** [vkohaupt/vokoscreen#152]
Dear all, 

2.5.0 seems to be a great release, thank you for your work!

I am wondering if there is any Deb Installer available for Ubuntu 16.04 to test the new release?

Thankfully,

~Robert

**Comment by vkohaupt** [comment]
Hallo Robert,

you can download from here.

http://linuxecke.volkoh.de/vokoscreen/vokoscreen-download.html

**Comment by tuxmuck** [comment]
It will take a few weeks until the Debian/Ubuntu repos involve the new version -

**Comment by debuglevel** [comment]
Ubuntu 16.04 and Debian 8 won't include vokoscreen 2.5 (maybe via the backports repositories).
vokoscreen 2.5 might be included in Ubuntu 16.10 Yakkety as well as Debian 9 Stretch.

As far as I know, there is also no up-to-date PPA available. To my knowledge, the only binary version available is http://linuxecke.volkoh.de/vokoscreen/vokoscreen-download.html which contains a self-executing archive (amd64 only) which therefore is not handled by your package manager and does not integrate well into your desktop environment, but must be started from command line.

If you want to install vokoscreen 2.5 the proper way, the best idea would probably to compile it yourself and install it via "checkinstall" (wraps a .deb package around the outcome of a "make install"). Compiling stuff and ensuring build dependencies is, of course, not exactly that much fun. So you might be best of with using the provided .run file.

I managed to build a 32bit version on Ubuntu 16.04, but I had to modify vokoscreen.pro to use lrelease instead of lrelease-qt5. (And I don't really want to encourage anyone to manually install a .deb file, as only via a repository/ppa security updates can be provided.)

[vokoscreen_2.5.0-1_i386.deb.zip](https://github.com/vkohaupt/vokoscreen/files/344499/vokoscreen_2.5.0-1_i386.deb.zip)

**Comment by tuxmuck** [comment]
> but must be started from command line

?!
Create a link on your desktop -

**Comment by orschiro** [comment]
Hi all, 

Maybe this is a good moment to start experimenting with Ubuntu's new Snap format?

Would it be a good idea to start creating one for Vokoscreen 2.5?

Moreover, such a Snap package could run on different Linux platforms.

**Comment by debuglevel** [comment]
On 02.07.2016 12:51, tuxmuck wrote:
>
>     but must be started from command line
>
> ?!
> Create a link on your desktop -
>
Of course, you can manually create a link on your desktop or on your
taskbar. But the freedesktop.org standard behaviour is to provide a
.desktop file (/usr/share/applications/vokoscreen.desktop) which is used
by the desktop enviroment's program menu. This standard cannot be
supported by a .run file as easy as a package does. (one could, of
course, dynamically create a .desktop file in the
~/.local/share/applications directory which points to the last-known
path of vokoscreen.run. But this seems to be much trouble compared to a
.deb/.rpm package which just does work.)

**Comment by vkohaupt** [comment]
Marc Kohaupt schrieb am 02.07.2016 um 12:13:

> [vokoscreen_2.5.0-1_i386.deb.zip](https://github.com/vkohaupt/vokoscreen/files/344499/vokoscreen_2.5.0-1_i386.deb.zip)

Ich habe so ein Link schon mal irgendwo so gesehen, kann/konnte mir aber 
keine Reim darauf machen wie man dies praktiziert, der Download kommt 
dann von https://github-cloud.s3.amazonaws.com

Viele grüße Volker

**Comment by orschiro** [comment]
Hi all, 

I'm currently trying to build a Snap package for version 2.5.0:

https://gist.github.com/orschiro/489710764173788d07c00b5a84ddaafe

However, I am receiving the following build error which I don't know how to resolve. 

Any ideas?

```
...
RCC: Error in '../src/screencast.qrc': Cannot find file 'language/vokoscreen_vi.qm'
RCC: Error in '../src/screencast.qrc': Cannot find file 'language/vokoscreen_zh_CN.qm'
RCC: Error in '../src/screencast.qrc': Cannot find file 'language/vokoscreen_zh_TW.qm'
make -j4
/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease-qt5 ../src/language/vokoscreen_ar.ts
make: /usr/lib/x86_64-linux-gnu/qt5/bin/lrelease-qt5: Command not found
Makefile:588: recipe for target 'language/vokoscreen_ar.qm' failed
make: *** [language/vokoscreen_ar.qm] Error 127
Command '['/bin/sh', '/tmp/tmp4y470n89', 'make', '-j4']' returned non-
zero exit status 2
```

Thankfully,

~Robert

**Comment by vkohaupt** [comment]
Hi Robert,

> make: /usr/lib/x86_64-linux-gnu/qt5/bin/lrelease-qt5: Command not found

Change all lrelease-qt5 to lrelease in screencast.pro

Volker

**Comment by orschiro** [comment]
Hi Volker, 

I can't find the file `screencast.pro`.

**Comment by vkohaupt** [comment]
Robert Orzanna schrieb am 05.07.2016 um 21:05:
> Hi Volker,
>
> I can't find the file `screencast.pro`.

Ups, vokoscreen.pro

**Comment by probonopd** [comment]
Given the self-contained `.run` file I wonder whether an [AppImage](http://appimage.org/) might be an option. It would not have to extract itself prior to running the application, since it self-mounts.

**Comment by orschiro** [comment]
@probonopd are AppImages easier to build than Snaps?

**Comment by probonopd** [comment]
Definitely, especially if (like this project) there are already existing binaries that run on most systems. Shall I give it a try?

**Comment by orschiro** [comment]
Yes, why not! :-)

**Comment by probonopd** [comment]
Here we go:
https://bintray.com/probono/AppImages/vokoscreen/_latestVersion#files

Built from the existing binaries using [this](https://github.com/probonopd/AppImages/blob/master/recipes/meta/vokoscreen.yml) tiny yml file.

**Comment by orschiro** [comment]
orschiro@x230:~/Downloads$ ./vokoscreen-2.5.1.glibc2.17-x86_64.AppImage
/tmp/.mount_wuL1RM/AppRun: line 7: /home/orschiro/Downloads/vokoscreen: No
such file or directory

**Comment by probonopd** [comment]
Thanks for testing, I believe this is actually a bug in the shell script that comes with vokoscreen, I will fix it in a minute.

**Comment by probonopd** [comment]
Should be fixed now.

**Comment by orschiro** [comment]
Nice, it does work now!

So, just to recap, what is the advantage of the AppImage and what is the advantage of the run file?

**Comment by probonopd** [comment]
By providing a distribution-independent standalone bundle as a .run file, vokoscreen does already much better than the majority of open source projects which only say "for Linux we offer only source code; for binaries, check your distribution".

The AppImage does offer some advantages over the .run file though:
 * One app = one file; simple management of apps; can easily be transported between multiple machines
 * Does not need to be extracted before it runs (can make a difference for large applications; for vokoscreen probably not that much of an issue)
 * Can be updated using the AppImageUpdate tool with binary delta updates (especially useful for, e.g., nightly builds, where you download only the bits that have actually changed)
 * Can be automatically integrated into the menus using the `desktopintegration` script bundled inside the AppImage; and/or using the external `appimaged` daemon
 * Can be digitally signed by the author
 * Can also extract itself like the .run file using `--appimage-extract` (this feature is work-in-progress)

**Comment by vkohaupt** [comment]
>  * Does not need to be extracted before it runs (can make a difference for large applications; for vokoscreen probably not that much of an issue)

look in your tmp dir, appimage was extract.

**Comment by probonopd** [comment]
No, the AppImage is only temporarily mounted there while the application is running.

**Comment by orschiro** [comment]
Cool, thanks for the list!

**Comment by vkohaupt** [comment]
ok i see, the directory .mount_Qs5Avg in /tmp is the mountpoint.


vk@cvolker:~>  cd /home/vk/Downloads
vk@cvolker:~/Downloads> mount
[..]
[..]
/home/vk/Downloads/vokoscreen-2.5.1.glibc2.17-x86_64.AppImage on 
/tmp/.mount_Qs5Avg type fuse.vokoscreen-2.5.1.glibc2.17-x86_64.AppImage 
(ro,nosuid,nodev,relatime,user_id=1002,group_id=100)
vk@cvolker:~/Downloads>

**Comment by eribertomota** [comment]
Hi,

I uploaded vokoscreen 2.5.0 to Debian Sid now. In few days it will arrive in Ubuntu. In six days I will upload to jessie-backports.

Volker, there is how test if the system is using lrelease-qt5 or lrelease before build?

Thanks!

Eriberto

**Comment by orschiro** [comment]
Wow, thanks so much, Eriberto!

Can't wait to see this arriving on Ubuntu 16.10. :-)

**Comment by vkohaupt** [comment]
Hi Eriberto,

Vokoscreen 2.5.0 is required Qt >= 5.4

Qt4 is no longer supported, you can change your build scripts.

For the most important dependencies please read the INSTALL file.

Volker

**Comment by vkohaupt** [comment]
Hi Eriberto,,

here is a list of the changes

http://linuxecke.volkoh.de/vokoscreen/vokoscreen-changes.html

Volker

**Comment by tuxmuck** [comment]
Thank you Eriberto  :-)

**Comment by eribertomota** [comment]
2016-10-30 5:28 GMT-02:00 Volker Kohaupt <notifications@github.com>:

> Hi Eriberto,
>
> Vokoscreen 2.5.0 is required Qt >= 5.4
>
> Qt4 is no longer supported, you can change your build scripts.
>
> For the most important dependencies please read the INSTALL file.
>
> Volker
>
>
>

Hi Volker,

I am not using Qt4. From my package:

Build-Depends: debhelper (>= 10),
               libasound2-dev,
               libqt5x11extras5-dev,
               libv4l-dev,
               libx11-dev,
               libxrandr-dev,
               pkg-config,
               qt5-qmake,
               qttools5-dev-tools

From changelog:

  * debian/copyright:
      - Removed all licensing about Qt4. (no longer used by the upstream)
      - Updated several data about upstream source code.

However, in Debian, the Qt5 provides lrelease, not lrelease-qt5. See
here[1].

[1] https://packages.debian.org/sid/amd64/qttools5-dev-tools/filelist

The package already built[2].

[2] https://buildd.debian.org/status/package.php?p=vokoscreen&suite=unstable

Thanks!

Eriberto

**Comment by vkohaupt** [comment]
Hi Eriberto,

> However, in Debian, the Qt5 provides lrelease, not lrelease-qt5. See
> here[1].

I am developing under opensuse and opensuse supports Qt4 and Qt5 and the 
commands are differently to debian.
lrelease     --> Qt4
lrelease-qt5 --> Qt5

**Comment by eribertomota** [comment]
2016-10-30 9:58 GMT-02:00 Volker Kohaupt <notifications@github.com>:

> Hi Eriberto,
>
> > However, in Debian, the Qt5 provides lrelease, not lrelease-qt5. See
> > here[1].
>
> I am developing under opensuse and opensuse supports Qt4 and Qt5 and the
> commands are differently to debian.
> lrelease --> Qt4
> lrelease-qt5 --> Qt5



Hum...  Debian uses a selector.

# ls /usr/bin/lrelease -l
lrwxrwxrwx 1 root root 9 mai 22 15:36 /usr/bin/lrelease -> qtchooser

OpenSUSE changes the names to avoid a conflict inside /usr/bin.

It isn't a problem for me because I can, naturally, use a patch. However,
it will be a problem for all users that want install from source code in
other distributions. So, I suggest a test to search the right executable.
But, as I said, it isn't a problem for me.

Thanks Volker.

Cheers,

Eriberto
