### ISSUE TITLE
Startup with Hide Window?

### ISSUE THREAD

**Issue by orschiro** [vkohaupt/vokoscreen#153]
Dear all, 

I have added Vokoscreen to my Ubuntu Startup Applications as follows:

![image](https://cloud.githubusercontent.com/assets/170947/17247909/e3391126-5596-11e6-9d5a-2ed32886686d.png)

This successfully starts Vokoscreen, however, with the main window being shown. 

I would like to start Vokoscreen by just showing the tray icon and hide the main window automatically. 

Is this somehow possible?

Thankfully,

~Robert

**Comment by tuxmuck** [comment]
Not possible when you start the programm.

But:
Settings in vokoscreen - Checkbox -> minimize when vokoscreen is recording

**Comment by orschiro** [comment]
Dear @tuxmuck,

Thanks!

I already made sure it disappears when starting the recording. 

What a pity that it cannot be done from the start. 

But thanks!

~Robert

**Comment by vkohaupt** [comment]
Please test the new feature "vokoscreen starts minimized"

http://linuxecke.volkoh.de/vokoscreen/vokoscreen-beta.html

**Comment by orschiro** [comment]
Dear Volker, 

The new feature does work great in the latest beta. 

Thank you so much! :-)

~Robert
