### ISSUE TITLE
Area setting lost after removing second monitor

### ISSUE THREAD

**Issue by graeme-defty** [vkohaupt/vokoscreen#154]
I have a second monitor attached when at my desk but use my laptop stand-alone much of the time. If I have recorded an area of the second display and then inadvertently disconnect leaving the recording area set to the second display, I can not get it back to the laptop display without returning to my desk and re-connecting to the second display. This renders Vokoscreen unusable - at least for capturing areas - sometimes for long period of time.

I tried to 'complete uninstall' and then re-install (which I believe should have removed any config settings) but it did not seem to do any good.

Is it possible to add some way to ensure the recording area is on a display that is actually attached to the PC? Perhaps some kind of 'reset' button which returns the recording area to its original-as-newly-installed position? Or better still, just restore to the 'default' area any time the area is not on any attached screen?

**Comment by vkohaupt** [comment]
I have a reset function implemented.
Please test it.
http://linuxecke.volkoh.de/vokoscreen/vokoscreen-beta.html
Thanks for your help
Volker

**Comment by graeme-defty** [comment]
Hi Volker,

No, it seems that the initial configuration is still off the bottom of my
primary display.

[image: Inline images 1]


[image: Inline images 2]


Thanks for your attention and for an excellent product!

Graeme

PS
Another nice change would be to make these details cut-and-paste-able.  ;-)

**Comment by graeme-defty** [comment]
Hi Volker,

One other thing - although resetting on every start of the program would
certainly work for me, most of the time I am copying the same area of my
screen, so having the area co-ordinates remembered from last time is
exactly what I need.

It is only occasionally that I need to reset, so ideally I could actually
control it myself (i.e. click a button) or the program could detect when
the capture area is off the display and only then reset it.

Thanks again,

Graeme

**Comment by vkohaupt** [comment]
Hi,

i see no images, its only text.
Can you put once more the images

I´m not right understand what you mean. The new reset-funktion reset all 
settings after a new start from vokoscreen. Is this not do?


graeme-defty schrieb am 07.08.2016 um 04:57:
> Hi Volker,
>
> No, it seems that the initial configuration is still off the bottom of my
> primary display.
>
> [image: Inline images 1]
>
>
> [image: Inline images 2]
>
>
> Thanks for your attention and for an excellent product!
>
> Graeme
>
> PS
> Another nice change would be to make these details cut-and-paste-able.  ;-)
>
>
>
>
>
>
>
>

**Comment by vkohaupt** [comment]
![bild3](https://cloud.githubusercontent.com/assets/3152567/17461463/89d4c712-5c8d-11e6-860c-70af9a0ce012.png)

**Comment by graeme-defty** [comment]
ooops!

Sorry - I did not realise that there was a new setting.  I will give it a
try ...

**Comment by graeme-defty** [comment]
Brilliant!

Thanks Volker - works like a dream.

Sorry I was a bit slow.

Graeme

**Comment by javl** [comment]
Hi Volker,
I was having the same problem. Just tried 2.5.1 and the new reset functions works perfectly so I think you can safely close this issue.

One suggestion would be to make a separate button that only resets the area, no other settings (like save path), though it is not at all crucial.

**Comment by vkohaupt** [comment]
Thanks for the hint, i close the issues.
