### ISSUE TITLE
./vokoscreen.run: 1: eval: ./vokoscreen.sh: Permission denied

### ISSUE THREAD

**Issue by emtudo** [vkohaupt/vokoscreen#155]
i tray:
chmod 755 vokoscreen.run
./vokoscreen

received:

./vokoscreen.run 
Verifying archive integrity... All good.
Uncompressing vokoscreen  100%  
./vokoscreen.run: 1: eval: ./vokoscreen.sh: Permission denied

**Comment by emtudo** [comment]
resolved: with umount /tmp

#tmpfs /tmp tmpfs defaults,noatime,nosuid,nodev,noexec,mode=1777,size=5000M 0 0

**Comment by vkohaupt** [comment]
You can start with the option "--keep"

./vokoscreen.run --keep

vokoscreen.run unpacking in the current directory and not in tmp

vokoscreen.run --help gives more options

**Comment by emtudo** [comment]
thanks!
