### ISSUE TITLE
Gifenc

### ISSUE THREAD

**Issue by orschiro** [vkohaupt/vokoscreen#156]
Dear all, 

I noticed that `.gif` animation have a very large file size. 

As a workaround, I currently create the video in `.mkv` and then use the attached script to create a `.gif`. 

What do you think of optimising the `.gif` creation of Vokoscreen drawing inspiration from `gifenc`?

Thankfully,

-Robert

[gifenc.txt](https://github.com/vkohaupt/vokoscreen/files/505084/gifenc.txt)

**Comment by vkohaupt** [comment]
The next Months i want work at the alsa modul, for other feature i have 
no time.

Volker

**Comment by orschiro** [comment]
I see, thanks, Volker!

I will continue then with my procedure to convert videos manually. :-)

    $ gifenc vokoscreen-video.mkv vokoscreen-video.gif 720 10
