### ISSUE TITLE
Vokoscreen opens kdenlive

### ISSUE THREAD

**Issue by littlebelgianwriter** [vkohaupt/vokoscreen#157]
Hello,

I recently heard about Vokoscreen and wanted to use it in Ubuntu 16.04. 
My first impression of your program is that it works fine with my slightly obsolete webcam. In any case, the Vokoscreen pictures have the same resolution as my webcam: 640 x 480.
However, when I use Vokoscreen, Kdenlive opens too.
Does this happen intentionally?
What is the purpose of this?
Is this a bug?
Please, enlighten me, because I am somewhat of a Ubuntu novice.

Kind regards from Belgium.

**Comment by vkohaupt** [comment]
You start vokoscreen and Kdenlive starts to same time?

**Comment by littlebelgianwriter** [comment]
Not really, Kdenlive starts at the moment I start using my webcam with Vokoscreen.

**Comment by vkohaupt** [comment]
littlebelgianwriter schrieb am 03.10.2016 um 10:45:
> Not really, Kdenlive starts at the moment I start using my webcam with Vokoscreen.

I like to see that, please make a short screencast.

-start vokoscreen
-push the button Start
-push all Tab, so i can see all settings
-go to the webcam-tab and start the webcam

You can send the video to vkohaupt@freenet.de or you save on a place 
then i can download it.

**Comment by littlebelgianwriter** [comment]
I will do that later on today. I think this will be easier for you to see what actually happens.

**Comment by littlebelgianwriter** [comment]
Hello,
I am back with the screencast, which I made with Record My Desktop, because now I am experiencing a whole other problem. When I start Vokoscreen, it immediately goes to my webcam and fullscreen. It does not record, only shows my face onscreen. I attach the screencast for you to evaluate. Hmm, it an ogv. I guess I'll have to zip it in order to attach it. That worked, so here it is. 
[out-2.ogv.zip](https://github.com/vkohaupt/vokoscreen/files/507891/out-2.ogv.zip)

**Comment by tuxmuck** [comment]
You have set the webcam in fullscreen!
Make a right click in the webcam window and set the window size to 320x240.

**Comment by vkohaupt** [comment]
Hello,

goto the webcam menue and switch to 160x120 or 320x240 or 640x480

**Comment by littlebelgianwriter** [comment]
When I click the menu, it does not change anything.

**Comment by tuxmuck** [comment]
![bild1](https://cloud.githubusercontent.com/assets/3200758/19070187/612ef4ca-8a2a-11e6-9c8a-a8db430b8667.png)

**Comment by littlebelgianwriter** [comment]
As a matter of fact, this is what I did. When I click the menu nothing changes. You can see this in the following screencast. 
Meanwhile, I browsed through the menu and found out how come the kdenlive program got connected to Vokoscreen, so that issue is solved. Now I have inclosed a screencast made with Vokoscreen and have zipped it. You will notice that nothing happens when I try to resize. 
[vokoscreen-2016-10-04_11-21-44.avi.zip](https://github.com/vkohaupt/vokoscreen/files/508180/vokoscreen-2016-10-04_11-21-44.avi.zip)

**Comment by tuxmuck** [comment]
What if you switch to windowed mode?
In your Ubuntu top left.

![bild2](https://cloud.githubusercontent.com/assets/3200758/19072059/6e71e58a-8a33-11e6-8052-d8893d060351.png)

**Comment by vkohaupt** [comment]
On my website you can download vokoscreen-2.5.0 as a binary-package.

Under Ubuntu can you extract the package to a folder of your choice.
Then open a terminal, switch in the folder and start with 
"./vokoscree.run" without ""

http://linuxecke.volkoh.de/vokoscreen/vokoscreen-download.html

**Comment by littlebelgianwriter** [comment]
@tuxmuck That is something that I will most definitely try to do.
@vkohaupt Thank you for your link and the rule for the terminal .
I most definitely will try your suggestions out, because more than once, I have discovered that the software in the Ubuntu store is not up to date. I have succesfully worked in the terminal before, so thank you very much for your answers.
You must think by now that I am a bit of a pain in the proverbial *** 
I love Ubuntu and dabbling in the terminal, so I will keep you posted of my progress in a positive way.
