### ISSUE TITLE
Rename vokoscreen-yyyy-mm-dd... to vokoscreen-mm-dd?

### ISSUE THREAD

**Issue by orschiro** [vkohaupt/vokoscreen#158]
Dear all, 

Maybe I overlooked a setting. 

Is it possible to change, e.g. `vokoscreen-2016-10-03_17-01-18.mkv` to `vokoscreen-10-03_17-01-18.mkv`?

Thankfully,

-Robert

**Comment by vkohaupt** [comment]
No, yyyy-mm-dd is fix.

Volker

**Comment by orschiro** [comment]
I see, thanks!
