### ISSUE TITLE
[FEATURE REQUEST] Configure Magnification shortcut keys

### ISSUE THREAD

**Issue by silvioprog** [vkohaupt/vokoscreen#160]
Hello,

It would be nice if Voko could allow the user to change the Magnification shortcut keys. Many programming tools uses the Shift+Ctrl+F9 (eg: Intellij IDEA, Lazarus IDE etc), so Voko Magnification conflicts with them.

Thank you!

**Comment by tuxmuck** [comment]
Maybe ....... in the next version -
