### ISSUE TITLE
Out of source build broken

### ISSUE THREAD

**Issue by aleixpol** [vkohaupt/vokoscreen#161]
```
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_TESTLIB_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR='"/home/apol/build-devel/frameworks/vokoscreen"' -I../../../devel/frameworks/vokoscreen -I. -I../../../devel/frameworks/vokoscreen/QtSingleApplicationQt5 -I../../../devel/frameworks/vokoscreen/libqxtQt5 -I../../../devel/frameworks/vokoscreen/audio -I../../../devel/frameworks/vokoscreen/send -I../../../devel/frameworks/vokoscreen/webcam -I../../../devel/frameworks/vokoscreen/settings -I../../../devel/frameworks/vokoscreen/showkey -I../../../devel/frameworks/vokoscreen/showclick -I../../../devel/frameworks/vokoscreen/magnifier -I../../../devel/frameworks/vokoscreen/credits -I../../../devel/frameworks/vokoscreen/version -I../../../devel/frameworks/vokoscreen/winInfo -I../../../devel/frameworks/vokoscreen/region -I../../../devel/frameworks/vokoscreen/formatsAndCodecs -I../../../devel/frameworks/vokoscreen/countdown -I../../../devel/frameworks/vokoscreen/pulse -I../../../devel/frameworks/vokoscreen/log -isystem /usr/include/alsa -I../../../devel/kde5/include -I../../../devel/kde5/include/QtWidgets -I../../../devel/kde5/include/QtX11Extras -I../../../devel/kde5/include/QtGui -I../../../devel/kde5/include/QtNetwork -I../../../devel/kde5/include/QtTest -I../../../devel/kde5/include/QtCore -I. -I. -I../../../devel/kde5/lib64/mkspecs/linux-g++ -o screencast.o ../../../devel/frameworks/vokoscreen/screencast.cpp
../../../devel/frameworks/vokoscreen/screencast.cpp: In constructor ‘screencast::screencast()’:
../../../devel/frameworks/vokoscreen/screencast.cpp:109:78: error: ‘class Ui_screencast’ has no member named ‘ShowkeyCheckBox’; did you mean ‘ShowkeyQCheckBox’?
     QvkShowkeyController *showkeyController = new QvkShowkeyController( myUi.ShowkeyCheckBox );
                                                                              ^~~~~~~~~~~~~~~
../../../devel/frameworks/vokoscreen/screencast.cpp:112:12: error: ‘class Ui_screencast’ has no member named ‘ShowkeyCheckBox’; did you mean ‘ShowkeyQCheckBox’?
       myUi.ShowkeyCheckBox->click();
            ^~~~~~~~~~~~~~~
../../../devel/frameworks/vokoscreen/screencast.cpp:128:19: error: ‘class Ui_screencast’ has no member named ‘pointerCheckBox’; did you mean ‘pointerQCheckBox’?
     connect( myUi.pointerCheckBox, SIGNAL( clicked( bool ) ), animateControl, SLOT( pointerOnOff( bool ) ) );
                   ^~~~~~~~~~~~~~~
../../../devel/frameworks/vokoscreen/screencast.cpp:381:12: error: ‘class Ui_screencast’ has no member named ‘MinimizedByStartCheckBox’; did you mean ‘MinimizedCheckBox’?
       myUi.MinimizedByStartCheckBox->click();
            ^~~~~~~~~~~~~~~~~~~~~~~~
../../../devel/frameworks/vokoscreen/screencast.cpp: In member function ‘virtual void screencast::closeEvent(QCloseEvent*)’:
../../../devel/frameworks/vokoscreen/screencast.cpp:725:13: error: ‘class Ui_screencast’ has no member named ‘pointerCheckBox’; did you mean ‘pointerQCheckBox’?
   if ( myUi.pointerCheckBox->checkState() == Qt::Checked )
             ^~~~~~~~~~~~~~~
../../../devel/frameworks/vokoscreen/screencast.cpp:726:10: error: ‘class Ui_screencast’ has no member named ‘pointerCheckBox’; did you mean ‘pointerQCheckBox’?
     myUi.pointerCheckBox->click();
          ^~~~~~~~~~~~~~~
../../../devel/frameworks/vokoscreen/screencast.cpp: In member function ‘void screencast::saveSettings()’:
../../../devel/frameworks/vokoscreen/screencast.cpp:776:49: error: ‘class Ui_screencast’ has no member named ‘MinimizedByStartCheckBox’; did you mean ‘MinimizedCheckBox’?
     settings.setValue( "MinimizedByStart", myUi.MinimizedByStartCheckBox->checkState() );
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~
../../../devel/frameworks/vokoscreen/screencast.cpp:778:38: error: ‘class Ui_screencast’ has no member named ‘ResetCheckBox’; did you mean ‘webcamCheckBox’?
     settings.setValue( "Reset", myUi.ResetCheckBox->checkState() );
                                      ^~~~~~~~~~~~~
../../../devel/frameworks/vokoscreen/screencast.cpp:828:38: error: ‘class Ui_screencast’ has no member named ‘pointerCheckBox’; did you mean ‘pointerQCheckBox’?
     settings.setValue( "OnOff", myUi.pointerCheckBox->checkState() );
                                      ^~~~~~~~~~~~~~~
../../../devel/frameworks/vokoscreen/screencast.cpp:837:39: error: ‘class Ui_screencast’ has no member named ‘ShowkeyCheckBox’; did you mean ‘ShowkeyQCheckBox’?
     settings.setValue(  "OnOff", myUi.ShowkeyCheckBox->checkState() );
                                       ^~~~~~~~~~~~~~~
../../../devel/frameworks/vokoscreen/screencast.cpp: In member function ‘QString screencast::getFileWithPath(QString)’:
../../../devel/frameworks/vokoscreen/screencast.cpp:2093:4: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
    if ( ProgName.contains("/", Qt::CaseInsensitive) and ( QFile::exists( ProgName ) ) )
    ^~
../../../devel/frameworks/vokoscreen/screencast.cpp:2096:5: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
     QString find;
     ^~~~~~~
../../../devel/frameworks/vokoscreen/screencast.cpp: In member function ‘QString screencast::myAlsa()’:
../../../devel/frameworks/vokoscreen/screencast.cpp:2257:7: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
       if ( listQFrame.count() > 0 )
       ^~
../../../devel/frameworks/vokoscreen/screencast.cpp:2265:9: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
         if (counter > 1)
         ^~
```

In-source builds fine

**Comment by vkohaupt** [comment]
I see no error, check your installation.


vk@cvolker:~/devel> git clone https://github.com/vkohaupt/vokoscreen.git
Klone nach 'vokoscreen'...
remote: Counting objects: 4878, done.
remote: Total 4878 (delta 0), reused 0 (delta 0), pack-reused 4878
Empfange Objekte: 100% (4878/4878), 2.99 MiB | 369.00 KiB/s, Fertig.
Löse Unterschiede auf: 100% (3271/3271), Fertig.
Prüfe Konnektivität... Fertig.
vk@cvolker:~/devel> cd vokoscreen/
vk@cvolker:~/devel/vokoscreen> qmake-qt5
Updating 'language/vokoscreen_ar.qm'...
     78 Übersetzungen wurden erzeugt (78 abgeschlossen und 0 nicht 
abgeschlossen)
     2 nicht übersetzte Texte wurden ignoriert
Updating 'language/vokoscreen_ast.qm'...
[..]
[..]
vk@cvolker:~/devel/vokoscreen> make -j5
/usr/lib64/qt5/bin/uic QvkNoPlayerDialog.ui -o ui_QvkNoPlayerDialog.h
/usr/lib64/qt5/bin/uic vokoscreen.ui -o ui_vokoscreen.h
/usr/lib64/qt5/bin/uic audio/QvkAlsaBusyDialog.ui -o ui_QvkAlsaBusyDialog.h
/usr/lib64/qt5/bin/uic send/QvkMailDialog.ui -o ui_QvkMailDialog.h
/usr/lib64/qt5/bin/uic webcam/QvkWebcamBusyDialog.ui -o 
ui_QvkWebcamBusyDialog.h
/usr/lib64/qt5/bin/uic showclick/showclickDialog.ui -o ui_showclickDialog.h
/usr/lib64/qt5/bin/uic magnifier/QvkMagnifierDialog.ui -o 
ui_QvkMagnifierDialog.h
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG 
-DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB 
-DQT_TESTLIB_LIB -DQT_CORE_LIB 
-DQT_TESTCASE_BUILDDIR=\"/home/vk/devel/vokoscreen\" -I. 
-IQtSingleApplicationQt5 -IlibqxtQt5 -Iaudio -Isend -Iwebcam -Isettings 
-Ishowkey -Ishowclick -Imagnifier -Icredits -Iversion -IwinInfo -Iregion 
-IformatsAndCodecs -Icountdown -Ipulse -Ilog -isystem /usr/include/alsa 
-isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem 
/usr/include/qt5/QtX11Extras -isystem /usr/include/qt5/QtGui -isystem 
/usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtTest -isystem 
/usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o 
qtsingleapplication.o QtSingleApplicationQt5/qtsingleapplication.cpp
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG 
-DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB 
-DQT_TESTLIB_LIB -DQT_CORE_LIB 
-DQT_TESTCASE_BUILDDIR=\"/home/vk/devel/vokoscreen\" -I. 
-IQtSingleApplicationQt5 -IlibqxtQt5 -Iaudio -Isend -Iwebcam -Isettings 
-Ishowkey -Ishowclick -Imagnifier -Icredits -Iversion -IwinInfo -Iregion 
-IformatsAndCodecs -Icountdown -Ipulse -Ilog -isystem /usr/include/alsa 
-isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem 
/usr/include/qt5/QtX11Extras -isystem /usr/include/qt5/QtGui -isystem 
/usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtTest -isystem 
/usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o 
qtlocalpeer.o QtSingleApplicationQt5/qtlocalpeer.cpp

**Comment by aleixpol** [comment]
You didn't reproduce correctly. As the title states, out of source:
```
cd vokoscreen
mkdir build
cd build
qmake ..
make
```

**Comment by J5lx** [comment]
I did just that and didn’t get any errors either.

**Comment by vkohaupt** [comment]
Aleix Pol schrieb am 09.10.2016 um 01:27:
> You didn't reproduce correctly. As the title states, out of source:
> ```
> cd vokoscreen
> mkdir build
> cd build
> qmake ..
> make


Wy do you want build out of source?

**Comment by vkohaupt** [comment]
Ok, i have build from a subdirectory, but i see no error it build fine.


vk@cvolker:~/devel> git clone https://github.com/vkohaupt/vokoscreen.git
Klone nach 'vokoscreen'...
remote: Counting objects: 4886, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 4886 (delta 0), reused 0 (delta 0), pack-reused 4878
Empfange Objekte: 100% (4886/4886), 3.04 MiB | 1.58 MiB/s, Fertig.
Löse Unterschiede auf: 100% (3271/3271), Fertig.
Prüfe Konnektivität... Fertig.
vk@cvolker:~/devel> cd vokoscreen/
vk@cvolker:~/devel/vokoscreen> mkdir build
vk@cvolker:~/devel/vokoscreen> cd build/
vk@cvolker:~/devel/vokoscreen/build> qmake-qt5 ..
Updating 'language/vokoscreen_ar.qm'...
     78 Übersetzungen wurden erzeugt (78 abgeschlossen und 0 nicht 
abgeschlossen)
     2 nicht übersetzte Texte wurden ignoriert
[..]
[..]
vk@cvolker:~/devel/vokoscreen/build> make -j5
/usr/lib64/qt5/bin/lrelease-qt5 ../language/vokoscreen_ar.ts
/usr/lib64/qt5/bin/lrelease-qt5 ../language/vokoscreen_ast.ts
/usr/lib64/qt5/bin/lrelease-qt5 ../language/vokoscreen_ca.ts
/usr/lib64/qt5/bin/lrelease-qt5 ../language/vokoscreen_cs.ts
/usr/lib64/qt5/bin/lrelease-qt5 ../language/vokoscreen_cs_CZ.ts
Updating '../language/vokoscreen_ar.qm'...
Updating '../language/vokoscreen_ca.qm'...
     44 Übersetzungen wurden erzeugt (44 abgeschlossen und 0 nicht 
abgeschlossen)
     36 nicht übersetzte Texte wurden ignoriert
Updating '../language/vokoscreen_ast.qm'...
     71 Übersetzungen wurden erzeugt (71 abgeschlossen und 0 nicht 
abgeschlossen)
[..]
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG 
-DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB 
-DQT_TESTLIB_LIB -DQT_CORE_LIB 
-DQT_TESTCASE_BUILDDIR=\"/home/vk/devel/vokoscreen/build\" 
-I../../vokoscreen -I. -I../QtSingleApplicationQt5 -I../libqxtQt5 
-I../audio -I../send -I../webcam -I../settings -I../showkey 
-I../showclick -I../magnifier -I../credits -I../version -I../winInfo 
-I../region -I../formatsAndCodecs -I../countdown -I../pulse -I../log 
-isystem /usr/include/alsa -isystem /usr/include/qt5 -isystem 
/usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtX11Extras 
-isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork 
-isystem /usr/include/qt5/QtTest -isystem /usr/include/qt5/QtCore -I. 
-I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o moc_QvkCountdown.o 
moc_QvkCountdown.cpp
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG 
-DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB 
-DQT_TESTLIB_LIB -DQT_CORE_LIB 
-DQT_TESTCASE_BUILDDIR=\"/home/vk/devel/vokoscreen/build\" 
-I../../vokoscreen -I. -I../QtSingleApplicationQt5 -I../libqxtQt5 
-I../audio -I../send -I../webcam -I../settings -I../showkey 
-I../showclick -I../magnifier -I../credits -I../version -I../winInfo 
-I../region -I../formatsAndCodecs -I../countdown -I../pulse -I../log 
-isystem /usr/include/alsa -isystem /usr/include/qt5 -isystem 
/usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtX11Extras 
-isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork 
-isystem /usr/include/qt5/QtTest -isystem /usr/include/qt5/QtCore -I. 
-I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o moc_QvkPulse.o moc_QvkPulse.cpp
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG 
-DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB 
-DQT_TESTLIB_LIB -DQT_CORE_LIB 
-DQT_TESTCASE_BUILDDIR=\"/home/vk/devel/vokoscreen/build\" 
-I../../vokoscreen -I. -I../QtSingleApplicationQt5 -I../libqxtQt5 
-I../audio -I../send -I../webcam -I../settings -I../showkey 
-I../showclick -I../magnifier -I../credits -I../version -I../winInfo 
-I../region -I../formatsAndCodecs -I../countdown -I../pulse -I../log 
-isystem /usr/include/alsa -isystem /usr/include/qt5 -isystem 
/usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtX11Extras 
-isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork 
-isystem /usr/include/qt5/QtTest -isystem /usr/include/qt5/QtCore -I. 
-I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o moc_QvkLog.o moc_QvkLog.cpp
g++ -Wl,-O1 -o vokoscreen main.o screencast.o qtsingleapplication.o 
qtlocalpeer.o qxtglobal.o qxtwindowsystem_x11.o qxtglobalshortcut_x11.o 
qxtglobalshortcut.o QvkAlsaWatcher.o QvkAlsaDevice.o alsa_device.o 
QvkMail.o QvkCapturethread.o QvkWebcamWatcher.o QvkWebcamController.o 
QvkWebcamWindow.o QvkWebcamBusyDialog.o QvkSettings.o QvkShowkeyGetkey.o 
QvkShowkeyWindow.o QvkShowkeyController.o QvkGlobalMouse.o 
QvkAnimateWindow.o QvkAnimateControl.o QvkShowClickDialog.o 
QvkCircleWidget.o QvkMagnifier.o QvkCredits.o QvkVersion.o QvkWinInfo.o 
QvkRegionChoise.o QvkRegionRecord.o QvkRegionController.o 
QvkFormatsAndCodecs.o QvkCountdown.o QvkPulse.o QvkLog.o 
qrc_screencast.o moc_screencast.o moc_qtsingleapplication.o 
moc_qtlocalpeer.o moc_qxtglobalshortcut.o moc_QvkAlsaWatcher.o 
moc_QvkAlsaDevice.o moc_QvkMail.o moc_QvkCapturethread.o 
moc_QvkWebcamWatcher.o moc_QvkWebcamController.o moc_QvkWebcamWindow.o 
moc_QvkWebcamBusyDialog.o moc_QvkSettings.o moc_QvkShowkeyGetkey.o 
moc_QvkShowkeyWindow.o moc_QvkShowkeyController.o moc_QvkGlobalMouse.o 
moc_QvkAnimateWindow.o moc_QvkAnimateControl.o moc_QvkShowClickDialog.o 
moc_QvkCircleWidget.o moc_QvkMagnifier.o moc_QvkCredits.o 
moc_QvkVersion.o moc_QvkWinInfo.o moc_QvkRegionChoise.o 
moc_QvkRegionRecord.o moc_QvkRegionController.o 
moc_QvkFormatsAndCodecs.o moc_QvkCountdown.o moc_QvkPulse.o moc_QvkLog.o 
   -lX11 -lasound -lv4l2 -lv4lconvert -lQt5Widgets -L/usr/lib64 
-lQt5X11Extras -lQt5Gui -lQt5Network -lQt5Test -lQt5Core -lGL -lpthread
vk@cvolker:~/devel/vokoscreen/build>
vk@cvolker:~/devel/vokoscreen/build> ls -al v*
-rwxr-xr-x 1 vk users 1874154  9. Okt 05:42 vokoscreen
vk@cvolker:~/devel/vokoscreen/build>

**Comment by J5lx** [comment]
@vkohaupt The purpose of out-of-source builds is to avoid clutter (build artifacts) in your source directories. Some build systems (meson for instance) don’t even *allow* in-source builds.

**Comment by vkohaupt** [comment]
Can we close this issues or give still inconsistencies?
