### ISSUE TITLE
Size and position to capture area

### ISSUE THREAD

**Issue by eribertomota** [vkohaupt/vokoscreen#162]
Hi Volker,

Can you add a option to set the position and area to be captured? It is useful to capture several windows of programs when making a lesson.

In KDE I can set the position and size for each window. So, if Vokoscreen could also do it, I would have a perfect aligment.

Thanks!

Eriberto

**Comment by vkohaupt** [comment]
Hi Eriberto,

can you do it with area function, or you mean a other thing?

Volker

**Comment by eribertomota** [comment]
2016-11-08 13:53 GMT-02:00 Volker Kohaupt <notifications@github.com>:

> Hi Eriberto,
>
> can you do it with area function, or you mean a other thing?
>
>
Hi Volker,

I need say to area function a position (coordinates, using numbers) and a
size (using numbers). Most important is the position. E.g. position 173,126
(173 pixels from top, 126 pixels from left corner).

Cheers,

Eriberto

**Comment by vkohaupt** [comment]
Maybe something like that?
I hope the svg is displayed.

**Comment by eribertomota** [comment]
Hum... No svg...

**Comment by vkohaupt** [comment]
Again as jpg

**Comment by eribertomota** [comment]
Nope... Can you send to my email?

**Comment by vkohaupt** [comment]
![area-settings](https://cloud.githubusercontent.com/assets/3152567/20119584/6c05470a-a609-11e6-81ca-d5e0fad82621.jpg)

**Comment by eribertomota** [comment]
Yeap!!!! Very good!!!!

**Comment by eribertomota** [comment]
Hi! There is a chance to release a new version with this feature up to Jan 20? If yes, I will put it in new Debian (Debian Stretch 9.0, accepting uploads up to Jan 25).

Thanks!

Eriberto

**Comment by vkohaupt** [comment]
Hi,
i work hard the last night on this feature and is finish.
Please test it with beta 2.5.3
By the capture area the green butons have now animation by doppelclick 
to maximized, once more click the area go to the old size and position.
Its a good time for all user to test and see the animation bevor i 
release vokoscreen 2.5.6 on the next weekend.
A 64 Bit Binary-Package gives on my homepage.
http://linuxecke.volkoh.de/vokoscreen/vokoscreen-beta.html

Volker

**Comment by vkohaupt** [comment]
> release vokoscreen 2.5.6 on the next weekend.
                      ^^^^^
I wanted say 2.6.0. Sorry.

Volker

**Comment by eribertomota** [comment]
2017-01-15 8:42 GMT-02:00 Volker Kohaupt <notifications@github.com>:

> Hi,
> i work hard the last night on this feature and is finish.
> Please test it with beta 2.5.3
> By the capture area the green butons have now animation by doppelclick
> to maximized, once more click the area go to the old size and position.
> Its a good time for all user to test and see the animation bevor i
> release vokoscreen 2.5.6 on the next weekend.
> A 64 Bit Binary-Package gives on my homepage.
> http://linuxecke.volkoh.de/vokoscreen/vokoscreen-beta.html
>
> Volker
>
>

Hi Volker,

Thanks a lot for your wonderful work. I already tested  the current commit
and it seems works fine. I will wait for the final release to upload to
Debian.

Cheers,

Eriberto

**Comment by eribertomota** [comment]
Hi,

Any news? Sorry for my curiosity.

Cheers,

Eriberto

**Comment by vkohaupt** [comment]
Hi,
on my developer maschine works all fine, but tests with Plasma5 and 
Unity i see many bugs, it´s better we release later.

**Comment by eribertomota** [comment]
2017-01-22 20:14 GMT-02:00 Volker Kohaupt <notifications@github.com>:

> Hi,
> on my developer maschine works all fine, but tests with Plasma5 and
> Unity i see many bugs, it´s better we release later.
>


Thanks! For the next Debian Stable I can upload up to Jan 25 18:00 UTC,

Cheers,

Eriberto
