### ISSUE TITLE
Video file not saved when recording paused and restarted

### ISSUE THREAD

**Issue by daveh** [vkohaupt/vokoscreen#164]
When I record a video and use "Stop" to stop the recording, the screen is recorded properly and the video file is saved in the specified folder. However, when making a recording if I pause it, then start it again, the video file is not saved. No file appears at all.

This behaviour occurs when using the buttons or the keyboard shortcuts.

I'm using version: 2.4.0-2 on a 64-bit install of Xubuntu 16.04.

If you need any more information please let me know.

**Comment by vkohaupt** [comment]
Hi Dave,

The best way is you start vokoscreen from a terminal, start a record, 
make pause, go record and stop.

Then copy all output from the terminal here.

**Comment by daveh** [comment]
$ vokoscreen

[vokoscreen] Locale: "en_GB" 
[vokoscreen] Version: "2.4.0" 
[vokoscreen] Qt version:  4.8.7 
[vokoscreen] Operating system: "ubuntu 16.04" 
[vokoscreen] asoundlib version: "1.1.0" 
[vokoscreen] current icon-theme: "hicolor" 

[vokoscreen] ---Begin Search external tools--- 
[vokoscreen] Search ffmpeg ..... found "/usr/bin/ffmpeg" Version: "2.8.8-0ubuntu0.16.04.1" 
[vokoscreen] Search pactl  ..... found Version: "8.0" 
[vokoscreen] ---End search external tools--- 

[vokoscreen] ---Begin search Screen--- 
[vokoscreen] Number of screens: 1 
[vokoscreen] Primary screen is: Display 1 
[vokoscreen] VirtualDesktop: false 
[vokoscreen] "Display 1:  1920 x 1080" 
[vokoscreen] ---End search Screen--- 

[vokoscreen] ---Begin Environment--- 
[vokoscreen] runs on DISPLAY ":0.0" 
[vokoscreen] ---End Environment--- 

[vokoscreen] ---Begin search Videoplayer--- 
[vokoscreen] Find Videoplayer : "/usr/bin/vlc" 
[vokoscreen] ---End search Videoplayer--- 

[vokoscreen] [Regional selection] Frame locked: false 

[vokoscreen] ---Begin search PulseAudio Plugin--- 
[vokoscreen] Found file .asound for PulseAudio Plugin 
[vokoscreen] ---End search PulseAudio Plugin--- 

 
[vokoscreen] ---Begin Pulse unload Module--- 
[vokoscreen] ---End Pulse unload Module--- 
 
[vokoscreen] ---Begin search Alsa capture device--- 
[vokoscreen] alsa_device_sample() in alsadevice.c: open audio device hw:0,0 (Success)
[vokoscreen] alsa_device_sample() in alsadevice.c: Samplerate = 44100
[vokoscreen] Find CaptureCard: "[hw:0,0] HDA Intel PCH" 
[vokoscreen] ---End search Alsa capture device--- 

[vokoscreen] ---Begin search PulseAudio Capture Devices--- 
[vokoscreen] Find CaptureCard: "Monitor of Built-in Audio Analogue Stereo" with device: "alsa_output.pci-0000_00_1f.3.analog-stereo.monitor" 
[vokoscreen] Find CaptureCard: "Built-in Audio Analogue Stereo" with device: "alsa_input.pci-0000_00_1f.3.analog-stereo" 
[vokoscreen] ---End search PulseAudio Capture Devices--- 

[vokoscreen] [Regional selection] Frame locked: true 

[vokoscreen] recording area 
[vokoscreen] Executive command : "/usr/bin/ffmpeg -report  -f x11grab -framerate 25 -video_size 1472x828 -i :0.0+336,122  -pix_fmt yuv420p -c:v mpeg4   -q:v 1  /tmp/vokoscreen-vokoscreen/vokoscreen-2016-11-20_15-21-54.avi" 

[vokoscreen] "/usr/bin/ffmpeg" is running and is ready for reading and writing 

[vokoscreen] "/usr/bin/ffmpeg" is not running 
 
[vokoscreen] ---Begin Pulse unload Module--- 
[vokoscreen] ---End Pulse unload Module--- 
 
[vokoscreen] Executive command : "/usr/bin/ffmpeg -report  -f x11grab -framerate 25 -video_size 1472x828 -i :0.0+336,122  -pix_fmt yuv420p -c:v mpeg4   -q:v 1  /tmp/vokoscreen-vokoscreen/screencast-pause-1.avi" 

[vokoscreen] "/usr/bin/ffmpeg" is running and is ready for reading and writing 

[vokoscreen] "/usr/bin/ffmpeg" is not running 
[vokoscreen] [Regional selection] Frame locked: false 


[vokoscreen] "/usr/bin/ffmpeg" is running and is ready for reading and writing 

[vokoscreen] "/usr/bin/ffmpeg" is not running 
[vokoscreen] [Regional selection] Frame locked: false 

[vokoscreen] Mergestring : "/usr/bin/ffmpeg -report -f concat -i /tmp/mergeFile.txt -c copy /home/noddy/Videos/vokoscreen-2016-11-20_15-21-54.avi" 
 
[vokoscreen] ---Begin Pulse unload Module--- 
[vokoscreen] ---End Pulse unload Module--- 
 
 
[vokoscreen] ---Begin Pulse unload Module--- 
[vokoscreen] ---End Pulse unload Module---

**Comment by vkohaupt** [comment]
Ok i see, you take avi with pause. I have avi removed in vokoscreen 
2.5.0, because avi is a very old and with pause a very bad format. For 
the removed avi comes mp4 in vokoscreen.
Please take mkv or download from your distribution vokoscreen 2.5.0 or 
from hier my binary-package.
http://linuxecke.volkoh.de/vokoscreen/vokoscreen-download.html

**Comment by daveh** [comment]
Great - I just installed 2.5.0 and tried mp4 (I can't use mkv as the site I'm uploading it to doesn't support it) and it works perfectly, pause and resume work as before.

Thank you so much for replying so quickly (and on a Sunday!) :-)

**Comment by Nicholasjaar** [comment]
lütfen.. bende 2.5.0 kurulu ama hata alıyorum kayıt yapılamıyor..
![22](https://user-images.githubusercontent.com/37977783/38543272-cbf1ab3c-3cac-11e8-9a6a-975084e58005.png)
