### ISSUE TITLE
possible bug during leap second

### ISSUE THREAD

**Issue by azbulutlu** [vkohaupt/vokoscreen#167]
While documenting a work that was running at Dec 31st 2016 using vokoscreen, The exact time period during the leap second vanished. The video jumps to the next second, but otherwise is perfectly fine. Running the (almost) identical code later doesn't result in this.
thanks :)

**Comment by debuglevel** [comment]
Thanks for this bug report. Leap seconds seem to provoke some fun stuff ;-). Assuming this bug can be reproduced, it would be an upstream issue for ffmpeg (the tool which vokoscreen uses to capture the screen).

**Comment by azbulutlu** [comment]
alright. will report it there. Thanks :) (reproducing it will be interesting through :D)
