### ISSUE TITLE
Bug: Vokoscreen closes and tray icon disappears

### ISSUE THREAD

**Issue by orschiro** [vkohaupt/vokoscreen#168]
Dear all, 

I tried to capture the problem I experience with version 2.5.0 on Ubuntu 16.10 in the following animation.

Steps to reproduce:

1. Open and minimise Vokoscreen to tray
2. Click "Hide window"
3. Use CTRL + Shift + F10 to start the recording
4. Instead of recording, Vokoscreen terminates and the tray icon disappears

If I don't hide the window, then everything is just fine. There seems to be a problem with "Hide window".

And ideas?

Yours,

-Robert

![peek 2017-01-15 08-12](https://cloud.githubusercontent.com/assets/170947/21960926/ec2bbc40-dafa-11e6-8405-c6d4d3742e6f.gif)

**Comment by vkohaupt** [comment]
Hallo,

if you start from a terminal comes an error?

Volker

**Comment by orschiro** [comment]
Dear Volker, 

It ends like this:

```
  
[vokoscreen] ---Begin search PulseAudio Capture Devices--- 
[vokoscreen] Find CaptureCard: "Monitor of Built-in Audio Analog Stereo" with device: "alsa_output.pci-0000_00_1b.0.analog-stereo.monitor" 
[vokoscreen] Find CaptureCard: "Built-in Audio Analog Stereo" with device: "alsa_input.pci-0000_00_1b.0.analog-stereo" 
[vokoscreen] ---End search PulseAudio Capture Devices--- 
  
[vokoscreen] recording fullscreen Display:  0 
[vokoscreen] Executive command : "/usr/bin/ffmpeg -report -f x11grab -draw_mouse 1 -framerate 25 -video_size 1366x768 -i :0+0,0 -f pulse -name vokoscreen -i alsa_input.pci-0000_00_1b.0.analog-stereo -pix_fmt yuv420p -c:v libx264 -preset veryfast  -c:a libmp3lame -q:v 1 -s 1366x768 -f matroska /tmp/vokoscreen-orschiro/vokoscreen-2017-01-15_15-45-13.mkv" 
  
Warning: QProcess: Destroyed while process ("/usr/bin/ffmpeg") is still running. ((null):0, (null))
```
