### ISSUE TITLE
Dual Monitor to Single Monitor Bug

### ISSUE THREAD

**Issue by christoph2005** [vkohaupt/vokoscreen#169]
Hi, 

Thanks for making Vokoscreen I've found it very useful.

I tend to use it to screen capture an area of the screen, which I then convert to a .gif animation.

When I use vokoscreen to capture an area of the screen on a 2nd monitor, and then the monitor is removed, I am no longer able to capture an area of the screen. It just crashes/doesn't record, and I'm only able to capture an entire screen or window.

Please fix the vokoscreen "area capture" so that it first checks if the monitor even exists, otherwise it should default to whatever monitor actually still exists.

Thanks,
~CM

**Comment by vkohaupt** [comment]
Hi,
The problem is known, but to time i have no second monitor.
If you are working often with vokoscreen you can Download from my 
Homepage a 64 Bit Binary-Package
http://linuxecke.volkoh.de/vokoscreen/vokoscreen-beta.html
there gives a option for reset all settings
http://linuxecke.volkoh.de/vokoscreen/vokoscreen-tips.html

Volker

**Comment by AlexZeitler** [comment]
Hi, I love Vokoscreen and I've been facing the same issue, the [Tips page](http://linuxecke.volkoh.de/vokoscreen/vokoscreen-tips.html) does not show how to reset settings (or I didn't see it :smiley:). I found the [Troubleshooting page](http://linuxecke.volkoh.de/vokoscreen/vokoscreen-troubleshooting.html) which shows how to set a `DISPLAY` env but it doesn't fix the problem.

**Comment by vkohaupt** [comment]
Thats right, to time gives no hint on my homepage for this problem.
The resetbutton gives in the next version and is built into the beta.
You can solved it to time, delete the vokoscreen profile in ~/.config/
Thanks for your hint.

**Comment by AlexZeitler** [comment]
Thanks, this did the trick.

**Comment by vkohaupt** [comment]
A other way is to edit "X=???" in the section [Area] in file 
~/.config/vokoscreen/vokoscreen.conf
