### ISSUE TITLE
Show different kind of clicks.

### ISSUE THREAD

**Issue by BiLachner** [vkohaupt/vokoscreen#172]
Specially for explaning how to use software you need to explain the different kind of clicks and what action they cause.
Therefore it would be nice to have different "ShowClick"-Options:
1.) left mouseclick -> show the leftclick-circle only for a short moment (color 1)
2.) left mouseclick -> show the rightclick-circle only for a short moment (color 2)
3.) click and hold left mousebutton -> show the leftclick-circle as long as the button is pressed (color 1)
4.) middle mouseclick -> show the middleclick-circle only for a short moment (color 3) -> middle-button = mouse-wheel
5.) not sooo much neccesary but would be nice ... mouse wheel-up and down -> may be show arrows for up and down (I'm not fully happy about this idea)

Thanks

**Comment by tuxmuck** [comment]
Kann man drüber nachdenken .....
Schafft es auf einer to do Liste aber sicherlich nicht nach ganz oben. Anwender die sowas benötigen dürften verschwindend gering sein -

**Comment by BiLachner** [comment]
Aber die Unterscheidung zwischen Rechts- und Linksklick ist doch grundlegend für die Vorstellung von Software und so etwas sehe ich als die Hauptfunktion von einem Screencasting Programm    ... ich glaube schon, dass mehr Interesse daran haben.

**Comment by tuxmuck** [comment]
Es bleibt im Hinterkopf -
Ob, wie, wann .... lassen wir mal offen -
Volker hat derzeit andere Baustellen im Programm.

**Comment by vkohaupt** [comment]
tuxmuck schrieb am 17.02.2017 um 13:52:
> Es bleibt im Hinterkopf -
> Ob, wie, wann .... lassen wir mal offen -
> Volker hat derzeit andere Baustellen im Programm.

Eine Baustelle in den letzten drei Wochen war/ist eine Schnittstelle für 
Erweiterungen zu schaffen. Diese habe ich heute auf github abgeladen. In 
wie weit diese binär kompatibel auf/abwärts zu den Qt Versionen ist muß 
ich noch eingehender testen.

Vokoscreen ist in letzten 5 Jahren Stück um Stück gewachsen, aber es ist 
halt nichts umsonst, besonders nicht für den Entwickler. Strom, 
Bildschirm, webcam, PC und sonstige Hardware kosten halt Geld.

Daher habe ich vor geraumer Zeit beschlossen in Zukunft Erweiterungen 
anzubieten die das Projekt durch einen Kauf Unterstützen sollen.

**Comment by tuxmuck** [comment]
Jou - leider auch so ein unschönes Thema.
Man will mit so einem Projekt ja nicht reich werden, aber wenn die "Spenden" nicht mal die Kosten für die Webseite decken, dann wird "ich will ...." auch nicht gerade zum Hit in der Freizeitprogrammierung.

**Comment by BiLachner** [comment]
Also, ich bin bereit für ein gutes Produkt zu bezahlen. Ich bin geradezu verzweifelt auf der Suche. Ich hätte ja jedes Produkt genommen, dass mehr als SimpleScreenRecorder kann, aber es gab wirklich absolut gar nichts!!!

Wie wäre es mit Crowfounding? Für ein Jahr betreiben der Plattform? Oder Einbau von einer Erweiterung?
Bei meinen Online-Lehrerbekanntschaft gibt es ein paar Linux-Nutzer und wie ich erwähnte, ist das Erstellen von Screencasts recht wichtig für uns. Für ein sich aktiv weiterentwickelndes Programm würden sicher alle etwas abdrücken.

**Comment by vkohaupt** [comment]
So in der Richtung, speziell die folgenden drei Punkte?
- Clickindikator
- Mouseimage
- Halo
https://www.youtube.com/watch?v=XyuudVcofUI

Oder gibt da noch was anderes an dem man sich Orientieren könnte?

**Comment by BiLachner** [comment]
Och, das ist aber schön ... muss ich mir gerade mal installieren. ;-)

Das bietet ja mehr, als ich mir gedacht habe. Im Prinzip waren meine Vorschläge so in der Richtung.
Ich kannte bisher halt nur keymon https://code.google.com/archive/p/key-mon/
Der Unterschied zu "Spot the mouse" ist im wesentlichen, dass die Anzeige, was man macht, bei keymon an einer Stelle bleibt, die man festlegt. Bei "Spot the mouse" orientiert es sich ja eher an dem Mauszeiger.
