### ISSUE TITLE
libx265 seems to be missing in dropdown

### ISSUE THREAD

**Issue by Martii** [vkohaupt/vokoscreen#173]
I noticed recently that libx265 *(HEVC)* is missing from the dropdown and I was wondering if there is a setting to enable during compiling for detection. Please note that my codec installation path is located under `/usr/lib64` in my Linux distro.

It used to show up late last year when I was testing this the first time but now it appears to be absent.

Thank you for your efforts and this is a nice Qt application. :smile_cat:

**Comment by Martii** [comment]
Oh I see you haven't made it that far yet [in the code](https://github.com/vkohaupt/vokoscreen/blob/bac1ee68c290e91a1d349337770b3522c92d4eaf/screencast.cpp#L680-L688) on the repo.

Seems my distro has advanced the package a bit ahead of the repository.

So Matroska and MP4 both are supported containers for the video.

References:
* https://en.wikipedia.org/wiki/Comparison_of_video_container_formats#Video_formats_supported

So I am not really sure if it's still an issue if I know how to fix it. :smile:

How do you feel about pull requests?

**Comment by vkohaupt** [comment]
Hi Marti Martz,

vokoscreen supports now libx265

https://github.com/vkohaupt/vokoscreen/commit/d22352fafaecbf3516752a78bc55d89b5e05a7a4

**Comment by Martii** [comment]
Thanks so much.

From what I can tell my distro uses these in the package they host:

``` cpp
   QStringList MKV_videoCodecList = ( QStringList() << "libx264" << "libx265" << "mpeg4" << "huffyuv" << "gif");
   QStringList MKV_AudioCodecLIst = ( QStringList() << "libmp3lame" << "libvorbis" << "pcm_s16le" << "libvo_aacenc" << "aac" );

   QStringList MP4_videoCodecList = ( QStringList() << "libx264" << "libx265" << "mpeg4" << "huffyuv" << "gif");
   QStringList MP4_AudioCodecList = ( QStringList() << "libmp3lame" << "libvorbis" << "pcm_s16le" << "libvo_aacenc" << "aac");
```

the rest are the same as this repo.
