### ISSUE TITLE
webcam lose some frames

### ISSUE THREAD

**Issue by remussatala** [vkohaupt/vokoscreen#175]
Webcam lose some frames. Please check this.

**Comment by tuxmuck** [comment]
How much fps did you set?

At the beginning? At the end? During recording?
More information, please!

**Comment by remussatala** [comment]
I set to 30fps but the webcam remains almost 20fps. The webcam have 30fps. Exactly 29.75fps. Sure is lost frames. Is visible. You should do some more tests closely.

**Comment by tuxmuck** [comment]
Your videocodec? Mpeg4 or libx264?
If you set the fps to 199 and make a full image of the desktop (without webcam) , how much fps are then displayed?

**Comment by tuxmuck** [comment]
I just set my webcam to 199 fps .... and I get 199 fps -!

**Comment by remussatala** [comment]
Codec is not to blame. I have the 30fps in capture. Only webcam lose frames. Not many but visible.

**Comment by tuxmuck** [comment]
You have not answered any of my questions -

Send a short video on which I can see the vokoscreen settings and the webcam to the support address.

Same as your PC. Distribution, desktop, processor etc.

**Comment by vkohaupt** [comment]
remussatala schrieb am 18.04.2017 um 15:52:
> Webcam lose some frames. Please check this.

Hi remussatala,

the webcam no lose frames the settings are fixed.
width  = 640
height = 480
fps    =  25

Question, with which tool can I systemwide the webcam configure?
And then how can I check if the settings are correct.

Volker

**Comment by remussatala** [comment]
Look at this:
http://s.go.ro/qnqzogo5

**Comment by vkohaupt** [comment]
remussatala schrieb am 19.04.2017 um 07:52:
> Look at this:
> http://s.go.ro/qnqzogo5

Now better fps

https://github.com/vkohaupt/vokoscreen/commit/946deb57001f56975ed81f06099e9ae76de7fe96

Please test it.

**Comment by remussatala** [comment]
Yes, thank you very much.
