### ISSUE TITLE
keyboard layout switch is not working for "showkey"

### ISSUE THREAD

**Issue by sergstetsuk** [vkohaupt/vokoscreen#176]
at least for ver 2.4.0

**Comment by vkohaupt** [comment]
Serg Stetsuk schrieb am 21.04.2017 um 12:43:
> at least for ver 2.4.0


           germany --> key = z

switch to english --> key = y

I see no bug

Test on opensuse 13.2 with vokoscreen 2.4.0

**Comment by sergstetsuk** [comment]
I tested switching from english to cyrillic on Xubuntu 16.04. https://www.youtube.com/watch?v=LSd8bPpgG2Q
Maybe I'm doing smth wrong?

**Comment by vkohaupt** [comment]
I have test with a new user in Russian and Russian keyboard, but 
vokoscreen want not show cyrillic font, and i have no knowledge to fix 
this bug.
