### ISSUE TITLE
Vokoscreen does not record sound. I live in Turkey and I am a victim of Vokoscreen.

### ISSUE THREAD

**Issue by ghost** [vkohaupt/vokoscreen#177]
Vokoscreen does not record sound. I live in Turkey and I am a victim of Vokoscreen.

**Comment by vkohaupt** [comment]
victim? :>)
No, No your are a victim, if you are work with other tools :>)

Please tell me your vokoscreen version und your Operationsystem.

**Comment by yusufgogus501** [comment]
Version:2.5.3 Beta
Operating System:Pisi Linux

**Comment by vkohaupt** [comment]
Please start vokoscreen from a terminal, make a short record, then copy 
all output from the terminal and print here.

**Comment by diodesignbr** [comment]
Hi @vkohaupt ! I love Vokoscreen!
Help me with this point, please:
I'm a musician, and when I try to record my sessions using Ardour and record the screen at the same time, I get this:

 dio@dio-pc:~$ vokoscreen
QApplication: invalid style override passed, ignoring it.
    Available styles: Windows, Fusion
[vokoscreen] Version: "2.5.0" 
[vokoscreen] Locale: "en_US" 
[vokoscreen] Qt version:  5.12.2 
[vokoscreen] Operating system: "ubuntu 19.04" 
[vokoscreen] Desktop: "XFCE" 
[vokoscreen] asoundlib version: "1.1.8" 
[vokoscreen] current icon-theme: "ubuntustudio" 
[vokoscreen] Qt-PluginsPath:      "/usr/lib/x86_64-linux-gnu/qt5/plugins" 
[vokoscreen] Qt-TranslationsPath: "/usr/share/qt5/translations" 
[vokoscreen] Qt-LibraryPath:      "/usr/lib/x86_64-linux-gnu" 
  
[vokoscreen] ---Begin Search external tools--- 
[vokoscreen] Search ffmpeg     ..... found "/usr/bin/ffmpeg" Version: "ffmpeg version 4.1.3-0ubuntu1 Copyright (c) 2000-2019 the FFmpeg developers" 
[vokoscreen] Search pactl      ..... found Version: "pactl 12.2" 
[vokoscreen] Search xdg-email  ..... found Version: "xdg-email 1.1.3" 
[vokoscreen] Search lsof       ..... found Version: "revision: 4.91" 
[vokoscreen] ---End search external tools--- 
  
[vokoscreen] ---Begin search Screen--- 
[vokoscreen] Number of screens: 1 
[vokoscreen] Primary screen is: Display 1 
[vokoscreen] VirtualDesktop: false 
[vokoscreen] DevicePixelRatio: 1  (Normal displays is 1, Retina display is 2) 
[vokoscreen] "Display 1:  1440 x 900" 
[vokoscreen] ---End search Screen--- 
  
[vokoscreen] ---Begin Environment--- 
[vokoscreen] runs on DISPLAY ":0.0" 
[vokoscreen] ---End Environment--- 
  
[vokoscreen] detect codecs with "/usr/bin/ffmpeg" 
[vokoscreen] ---Begin search formats--- 
[vokoscreen] find Format "mkv" 
[vokoscreen] ---Begin search video codec--- 
[vokoscreen] find Videocodec "libx264" 
[vokoscreen] find Videocodec "mpeg4" 
[vokoscreen] find Videocodec "huffyuv" 
[vokoscreen] ---End search video codec--- 
  
[vokoscreen] ---Begin search audio codec--- 
[vokoscreen] find Audiocodec "libmp3lame" 
[vokoscreen] find Audiocodec "libvorbis" 
[vokoscreen] find Audiocodec "pcm_s16le" 
[vokoscreen] not found Audiocodec "libvo_aacenc" 
[vokoscreen] find Audiocodec "aac" 
[vokoscreen] ---End search audio codec--- 
  
[vokoscreen] find Format "mp4" 
[vokoscreen] find Format "gif" 
[vokoscreen] ---End search formats--- 
  
[vokoscreen] ---Begin search Videoplayer--- 
[vokoscreen] Find Videoplayer : "/snap/bin/vlc" 
[vokoscreen] Find Videoplayer : "/usr/bin/kdenlive" 
[vokoscreen] ---End search Videoplayer--- 
  
[vokoscreen] ---Begin search GIFplayer--- 
[vokoscreen] Find GIFplayer : "firefox" 
[vokoscreen] ---End search GIFplayer--- 
  
[vokoscreen] ---Begin Pulse unload Module--- 
[vokoscreen] ---End Pulse unload Module--- 
  
[vokoscreen] ---Begin search devices--- 
[vokoscreen] find device "x11grab" 
[vokoscreen] ---End search devices--- 
  
[vokoscreen] ---Begin search Alsa capture device--- 
[vokoscreen] alsa_device_sample() in alsadevice.c: cannot open audio device hw:0,3 (No such file or directory)
[vokoscreen] Find CaptureCard: "[hw:0,3] HDA ATI HDMI" 
[vokoscreen] Find CaptureCard: "[hw:1,0] HD-Audio Generic" 
[vokoscreen] alsa_device_sample() in alsadevice.c: cannot open audio device hw:2,0 (Device or resource busy)
[vokoscreen] Find CaptureCard: "[hw:2,0] USB Audio CODEC" 
[vokoscreen] ---End search Alsa capture device--- 
  
[vokoscreen] ---Begin search PulseAudio Capture Devices--- 
[vokoscreen] Find CaptureCard: "Monitor of PCM2902 Audio Codec Analog Stereo" with device: "alsa_output.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo.monitor" 
[vokoscreen] Find CaptureCard: "PCM2902 Audio Codec Analog Stereo" with device: "alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo" 
[vokoscreen] Find CaptureCard: "Monitor of Family 17h (Models 00h-0fh) HD Audio Controller Digital Stereo (IEC958)" with device: "alsa_output.pci-0000_0a_00.3.iec958-stereo.monitor" 
[vokoscreen] Find CaptureCard: "Family 17h (Models 00h-0fh) HD Audio Controller Analog Stereo" with device: "alsa_input.pci-0000_0a_00.3.analog-stereo" 
[vokoscreen] ---End search PulseAudio Capture Devices--- 
  
[vokoscreen] alsa_device_busy() in alsadevice.c: cannot open audio device hw:2,0 (Device or resource busy)

When I change the audio device, Vokoscreen works, but with no sound.

Any sugestion, please?

Thanks!!

**Comment by knows1** [comment]
[vokoscreen] alsa_device_sample() in alsadevice.c: cannot open audio device hw:0,3 (No such file or directory)
