### ISSUE TITLE
 Vokoscreen pause resume doesn't work lost whole video doesn't save

### ISSUE THREAD

**Issue by almas** [vkohaupt/vokoscreen#178]
When click pause button it lost whole video. Doesn't save any video. If I doesn't pause then it working well.

Here are logs:

./.config/vokoscreen/ffmpeg-20170504-142722.log
ffmpeg started on 2017-05-04 at 14:27:22
Report written to "ffmpeg-20170504-142722.log"
Command line:
/usr/bin/ffmpeg -report -f concat -i /tmp/mergeFile.txt -c copy /home/dd/Desktop/vokoscreen-2017-05-04_14-26-30.mkv
ffmpeg version N-81995-gd790e48 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
  configuration: --extra-libs=-ldl --prefix=/opt/ffmpeg --mandir=/usr/share/man --enable-avresample --disable-debug --enable-nonfree --enable-gpl --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb --disable-decoder=amrnb --disable-decoder=amrwb --enable-libpulse --enable-libfreetype --enable-gnutls --enable-libx264 --enable-libx265 --enable-libfdk-aac --enable-libvorbis --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libspeex --enable-libass --enable-avisynth --enable-libsoxr --enable-libxvid --enable-libvidstab --enable-libwavpack --enable-nvenc
  libavutil 55. 32.100 / 55. 32.100
  libavcodec 57. 61.103 / 57. 61.103
  libavformat 57. 52.100 / 57. 52.100
  libavdevice 57. 0.102 / 57. 0.102
  libavfilter 6. 64.100 / 6. 64.100
  libavresample 3. 0. 0 / 3. 0. 0
  libswscale 4. 1.100 / 4. 1.100
  libswresample 2. 2.100 / 2. 2.100
  libpostproc 54. 0.100 / 54. 0.100
Splitting the commandline.
Reading option '-report' ... matched as option 'report' (generate a report) with argument '1'.
Reading option '-f' ... matched as option 'f' (force format) with argument 'concat'.
Reading option '-i' ... matched as input file with argument '/tmp/mergeFile.txt'.
Reading option '-c' ... matched as option 'c' (codec name) with argument 'copy'.
Reading option '/home/dd/Desktop/vokoscreen-2017-05-04_14-26-30.mkv' ... matched as output file.
Finished splitting the commandline.
Parsing a group of options: global .
Applying option report (generate a report) with argument 1.
Successfully parsed a group of options.
Parsing a group of options: input file /tmp/mergeFile.txt.
Applying option f (force format) with argument concat.
Successfully parsed a group of options.
Opening an input file: /tmp/mergeFile.txt.
[file @ 0x30bba60] Setting default whitelist 'file,crypto'
[concat @ 0x30bb220] Unsafe file name '/tmp/vokoscreen-vokoscreen/vokoscreen-2017-05-04_14-26-30.mkv'
[AVIOContext @ 0x30c3da0] Statistics: 177 bytes read, 0 seeks
/tmp/mergeFile.txt: Operation not permitted

---Begin Pulse unload Module---
[vokoscreen] ---End Pulse unload Module---

[vokoscreen] alsa_device_busy() in alsadevice.c: cannot open audio device hw:1,0 (Device or resource busy)
[vokoscreen] Executive command : "/usr/bin/ffmpeg -report -f x11grab -framerate 25 -video_size 1544x838 -i :0+1331,182 -f alsa -i pulse -pix_fmt yuv420p -c:v libx264 -preset veryfast -c:a libmp3lame -q:v 1 /tmp/vokoscreen-vokoscreen/screencast-pause-1.mkv"

[vokoscreen] "/usr/bin/ffmpeg" is running and is ready for reading and writing

[vokoscreen] "/usr/bin/ffmpeg" is not running

[vokoscreen] ---Begin Pulse unload Module---
[vokoscreen] ---End Pulse unload Module---

[vokoscreen] alsa_device_busy() in alsadevice.c: cannot open audio device hw:1,0 (Device or resource busy)
[vokoscreen] Executive command : "/usr/bin/ffmpeg -report -f x11grab -framerate 25 -video_size 1544x838 -i :0+1331,182 -f alsa -i pulse -pix_fmt yuv420p -c:v libx264 -preset veryfast -c:a libmp3lame -q:v 1 /tmp/vokoscreen-vokoscreen/screencast-pause-2.mkv"

[vokoscreen] "/usr/bin/ffmpeg" is running and is ready for reading and writing

[vokoscreen] "/usr/bin/ffmpeg" is not running
[vokoscreen] [Regional selection] Frame locked: false

[vokoscreen] "/usr/bin/ffmpeg" is running and is ready for reading and writing

[vokoscreen] "/usr/bin/ffmpeg" is not running
[vokoscreen] [Regional selection] Frame locked: false

[vokoscreen] Mergestring : "/usr/bin/ffmpeg -report -f concat -i /tmp/mergeFile.txt -c copy /home/dd/Desktop/vokoscreen-2017-05-04_14-24-05.mkv"

[vokoscreen] ---Begin Pulse unload Module---
[vokoscreen] ---End Pulse unload Module---

**Comment by tuxmuck** [comment]
What version of Ubuntu do you use and which version of vokoscreen?

Works here under Ubuntu 17.04 without problems.

**Comment by almas** [comment]
Ubuntu 16.04, Vokoscreen 2.4.0

It seems ffmpeg checking filename:

[concat @ 0x30bb220] Unsafe file name '/tmp/vokoscreen-vokoscreen/vokoscreen-2017-05-04_14-26-30.mkv'

**Comment by almas** [comment]
I downloaded Vokoscreen 2.5 from http://linuxecke.volkoh.de/vokoscreen/vokoscreen-download.html 
It's working well :) Thank you for your support.

**Comment by tomjridge** [comment]
I also had this issue, on Ubuntu 16.04. Lost whole video :(

**Comment by zlcys** [comment]
Hi there!  I also confirm that Vokoscreen don't save the video if I press "pause" than stop. I just lost 90 minutes of video. It just happened yesterday. I believe the bug is steel there. Other than that it's a great software. Many thanks for the programmer (s)!

**Comment by vkohaupt** [comment]
Is this the first time you press Pause?

vokoscreen Version?

**Comment by vkohaupt** [comment]
Ok i see, this Problem is in 2.4.0 with format avi, please change to 2.5.0
