### ISSUE TITLE
Automatic stop

### ISSUE THREAD

**Issue by kjeldflarup** [vkohaupt/vokoscreen#185]
Is there a way to automatically stop a recording after some time.
Or would this do:
sleep 300; killall vokoscreen

**Comment by vkohaupt** [comment]
kjeldflarup schrieb am 23.07.2017 um 10:18:
> Is there a way to automatically stop a recording after some time.

No.


> Or would this do:
> sleep 300; killall vokoscreen

This is a good way to lose your data.
