### ISSUE TITLE
Ugly frame

### ISSUE THREAD

**Issue by trisz** [vkohaupt/vokoscreen#187]
Hi Michael,
A wide ugly black frame is present choosing area recording. It prevents to set the frame width and height accurately. The last usable vokoscreen version was 1.9.0, but it is not compatible with debian any more. I use nvidia card and this problem is present on KDE, Gnome, Mate... I think it should be transparent, but it is not. I think the arrows with the green discs are not necessary at all. A thin lined frame is enough. I need only the blue frame. It could be a feature request, but how can I set it to transparent?

![vokoscreen2017-08-29 21-28-55](https://user-images.githubusercontent.com/31453749/29841071-6263c3d8-8d04-11e7-8411-affacdb86e20.png)

**Comment by vkohaupt** [comment]
trisz schrieb am 29.08.2017 um 22:07:

> A wide ugly black frame is present choosing area recording. It prevents to set the frame width and height accurately. The last usable vokoscreen version was 1.9.0, but it is not compatible with debian any more. I use nvidia card and this problem is present on KDE, Gnome, Mate... I think it should be transparent, but it is not.

Then enable composite.
Why you disable the compositer?


> I think the arrows with the green discs are not necessary at all.

This is your personal opinion, but not my.


> A thin lined frame is enough. I need only the blue frame.

If you want, then programming self


>  It could be a feature request, but how can I set it to transparent?

Ha, ha you disable composite and make a feature request, or have you a 
so old PC that composting no do, then do your PC to trash.

**Comment by debuglevel** [comment]
Hi @trisz,

actually, the black border should already be transparent. In Linux, to enable fancy features like transparency, a special component called "compositing manager" needs to be activated. In most distributions and desktop environments, it should already be activated by default.

In rare cases, it might be the case that this component does not work and creates graphical issues in conjunction with some bad graphics drivers. Maybe you had it deactivated for some reason or it was not activated by default at all.

If you cannot use compositing due to bad driver support or something, I guess there is no easy way to get vokoscreen to an usable state.

We are happy for your reply, whether you were able to resolve your problem this way! :-)

**Comment by trisz** [comment]
Hi,
The compositer is enabled. I think, not all of the graphics cards support 'this' (what?) kind of transparency used by vokoscreen. I have a very recent and new graphics card (maybe not for gaiming), and I am not intend to 'do it to trash'. A 4 core processor is not enough? To tell the truth, i cannot find any computer display vokoscreen correctly.
I use marco/compton HW compositer on Mate. The same experience on debian 8/KDE.

Moreover, the compositer is recommended to be disabled during recording because the computer need serious power in order to play something on the screen, capture and encode at the same time. The compositer need extra resource and this results week quality output file. It is not an opinion. The question is 'decorative or effective'?

**Comment by tuxmuck** [comment]
Take this beta version 2.5.4:
http://linuxecke.volkoh.de/vokoscreen/vokoscreen-beta.html
There is the black frame removed -

**Comment by vkohaupt** [comment]
What say

cat  /var/log/Xorg.0.log | grep Driver

**Comment by trisz** [comment]
Hi Michael,
The beta version 2.5.4 works well. Please, keep this code for the future relaese!
The 2.5.0 behaves unpredictably. The ugly black frame disappears if I switch to HW and then back to SW compositing. If I use SW compositing sometimes black frame appears, but sometimes it is normal. Sometimes compiz behaves differently than marco, sometimes does not.
So I can close this issue.
