### ISSUE TITLE
Inadequate area designation (v. 1.9.0-2)

### ISSUE THREAD

**Issue by finnianr** [vkohaupt/vokoscreen#188]
My monitor is 1920 x 1200 and I want to screen cast only the upper most area 1920 x 1080. I can do this with Kazam, but with Vokoscreen I cannot extend the area right out to the edge.

**Comment by tuxmuck** [comment]
Which version of vokoscreen, which distribution, which desktop?

**Comment by vkohaupt** [comment]
you need vokoscreen 2.4.0 or later

http://linuxecke.volkoh.de/vokoscreen/vokoscreen-beta.html
