### ISSUE TITLE
ffmpeg failures Flash update

### ISSUE THREAD

**Issue by Martii** [vkohaupt/vokoscreen#189]
This is more of an informational ticket of some trouble that I've been having with vokoscreen so please close if you feel the need but wanted to let you *(and everyone who searches for this)* know of an issue with:

Flash 27.0.0.130
Linux
vokoscreen *(any beta version commit tag since I've been twiddling with this)*
Qt  *(all 5.x versions... release and snapshots)*

1. I went to go record a video and it froze up vokoscreen for a little bit. 
2. Pressing the stop button didn't work.
3. Pressed it two to three times then it finally stopped but...
4. Claimed there was a ffmpeg issue with crashing.
5. Video failed to record.
6. Turned off Audio recording then it's okay.

After a crash course on re-configuring Pulse *(Phonon)* I found it was an update that was applied with that particular flash version.

Additional symptoms were sound multiplexing *(system sounds, other audio programs utilizing audio)* would fail. The simplest reproduction test was to put something in the recycle bin and delete it to get a system sound while listening/watching a video with Flash.

Side note: Yeah I know Flash is ick but streaming MP4 still has some buffering issues so I'm stuck with it for the time being in certain cases.

Anyhow... just thought someone might want to know what I've experienced and I hope it helps.

Ref(s):
* https://forums.adobe.com/thread/2382913  *(nearest ref that is similar... time to go see if the Settings resolves this... **EDIT** NOPE!)*

P.S. Keep up the great work. :)

**Comment by Martii** [comment]
They seem to have fixed this in 27.0.0.170. Thanks for the eyes.

**Comment by tuxmuck** [comment]
Everything will be fine  ; -)
