### ISSUE TITLE
beta 2.5.7 RUN version: mouse click visualization shows black square on Kubuntu 17.04

### ISSUE THREAD

**Issue by TheDiveO** [vkohaupt/vokoscreen#190]
When using the beta 2.5.7 RUN on Kubuntu 17.04 the mouse click visualization doesn't correctly overlay with the existing background but instead only shows a black square containing the click spot image. For reference, the 2.5.0 version installed from the official Ubuntu ppa also shows the same compositing bug (2.5.0 is even worse as the reference frame overlaid over the screen has compositing problems too, showing a thick black border around the frame itself).

**Comment by vkohaupt** [comment]
https://github.com/vkohaupt/vokoscreen/blob/master/README.md

GUI
For transparent effects in the area, countdown, and showclick, a 
switched-on compositer is needed, otherwise the surfaces appear in black.

**Comment by TheDiveO** [comment]
hm, this is a stock Kubuntu 17.04 installation using X11 X.org with AMD drivers. I don't know where I would disable or enable compositing.

**Comment by tuxmuck** [comment]
KDE settings - Monitor - Compositor -> enable!

**Comment by vkohaupt** [comment]
SHIFT+ALT+F12 switch on/off

**Comment by TheDiveO** [comment]
Now finally found the chance to check the compositor settings ... and for whatever reason it was disabled (now that's strange). Anyway, switching compositing back on again makes click indications to properly compose over the display as intended. Thank you very much for pointing me towards the proper configuration option.
