### ISSUE TITLE
Vokoscreen doesn't Work in Wayland-Based Desktops

### ISSUE THREAD

**Issue by Lonniebiz** [vkohaupt/vokoscreen#191]
https://bugs.launchpad.net/ubuntu/+source/vokoscreen/+bug/1723396

**Comment by tuxmuck** [comment]
This is a known issue with wayland. Documented on:
https://fedoraproject.org/wiki/How_to_debug_Wayland_problems#Screen_capture_is_not_available_with_usual_apps

All screenshot, screencast and remote desktop programs do not work.

**Comment by tuxmuck** [comment]
Workaround -
Log out -> Gear symbol -> Select x-org.
Wayland is no longer active and vokoscreen works again.

**Comment by aek** [comment]
Doing that start to partially work. Only record whole screen, you cannot select a specific window to be recorded

**Comment by glaubersm** [comment]
will vokoscreen support pipewire?
https://blogs.gnome.org/uraeus/2018/01/26/an-update-on-pipewire-the-multimedia-revolution-an-update/
