### ISSUE TITLE
vokoscreen doesn't work with ubuntu 17.10

### ISSUE THREAD

**Issue by prabinkumarsahu28** [vkohaupt/vokoscreen#192]
vokoscreen doesn't work with ubuntu 17.10. it records only sound but not the screen. it plays only audio with a black screen. Please solve this problem as quick as possible.
![screenshot from 2017-11-02 07-18-14](https://user-images.githubusercontent.com/33302132/32305883-153793c4-bf9e-11e7-8a76-11e3d9c272fd.png)

**Comment by tuxmuck** [comment]
Look here:
https://github.com/vkohaupt/vokoscreen/issues/191

**Comment by nbkhope** [comment]
Is there any solution to this problem? I'm using Ubuntu 17.10.

**Comment by prabinkumarsahu28** [comment]
Yes bro login with "Ubuntu on Xorg" and the problem will solve...

**Comment by nbkhope** [comment]
Okay, so I logged off and on the login screen clicked the setting icon and chose "Ubuntu on Xorg." Using that worked. Thank you!

**Comment by prabinkumarsahu28** [comment]
You welcome👍👍👍

**Comment by prabinkumarsahu28** [comment]
Are you using "playonlinux" in ubuntu 17.10 ?

**Comment by knows1** [comment]
vokoscreen doesn't work with  Debian10
