### ISSUE TITLE
video player recognition issue

### ISSUE THREAD

**Issue by Ghostboy-287** [vkohaupt/vokoscreen#194]
Hello, i'm using [elementary os](https://elementary.io/) which is based on ubuntu 16.04 xenial and its video player is named [Audience](https://github.com/elementary/videos) ( or in [Launchpad](https://launchpad.net/audience) )

the problem is that vokoscreen does not recognize it as a video player and do not list it in the Player field and so cant play the screencast when clicking on play button.

note: Audience is compatible with the video format proposed by vokoscreen (can play avi and mkv videos)

**Comment by tuxmuck** [comment]
Is this the same when you install the VLC or any other player ?

**Comment by Ghostboy-287** [comment]
no, 
when i install vlc or another popular video player, vokoscreen recognizes it and displays it in the player field normally

**Comment by tuxmuck** [comment]
Vokoscreen searches for the name "usual" players.
Audience is rather an exotic one which is not included in our search mask.

**Comment by Ghostboy-287** [comment]
I saw that you added it to the list ([screencast.cpp](https://github.com/vkohaupt/vokoscreen/blob/674a28435313e969ea706135542ac51adef227d2/screencast.cpp)). 
thank you. it will save me a few seconds that will become hours:)

**Comment by vkohaupt** [comment]
Hi Ghostboy-287,
Have finished and a little bit more,
In the picture wie see vokoscreen can now use the standard system videoplayer and
If the theme have a icon to the player we see the programmicon.  And not to forgot i added Audience.

![screenshot_20171112_205045](https://user-images.githubusercontent.com/3152567/32702736-78ee23c4-c7eb-11e7-8f12-de0a49b0aa07.jpg)

**Comment by Ghostboy-287** [comment]
ah this is cool
vokoscreen takes another step to conquer the hearts of users :)
great job

**Comment by vkohaupt** [comment]
Please test "Standard system player" audience should start, if is the system videoplayer

**Comment by Ghostboy-287** [comment]
i can't build it , i have a little problem [ #beginner ^^ ]
i tried to follow [INSTALL](https://github.com/vkohaupt/vokoscreen/blob/master/INSTALL) instructions but i got an error whan i have to run "qmake": 
```
sh: 1: lrelease-qt5: not found
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_ar.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_ast.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_ca.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_cs_CZ.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_cs.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_da_DK.qm'
RCC: Error in 'screencast.qrc': Cannot find file 'language/vokoscreen_de_AT.qm'
...
..
.
```
**additional info:** 
```
~$ qmake -v 
QMake version 3.0
Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu
```
ps: i have `qttools5-dev-tools` and `qttools5-dev` installed 
i noticed also that i have lrelease instead of lrelease-qt5
```
~$ locate lrelease
/usr/bin/lrelease
/usr/bin/lrelease-qt4
/usr/lib/x86_64-linux-gnu/qt4/bin/lrelease
/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease
/usr/share/man/man1/lrelease-qt4.1.gz
/usr/share/qt4/bin/lrelease
```
and when i checked the version of lrelease i found that it's the same than the version of qmake i used on the top
```
~$ lrelease -version
lrelease version 5.5.1
```
Any idea, please?

**Comment by vkohaupt** [comment]
Change in file vokoscreen.pro all lrelease-qt5 to lrelease

**Comment by Ghostboy-287** [comment]
thank you for your instructions, 
I was able to build it after following your instructions, and I tested it, and everything works fine. 
it recognizes Audience , and the standard system player feature works just fine.
I also noticed that you added the possibility to create gifs, which I appreciated especially that they are good quality.
