### ISSUE TITLE
Option to block screen saver during recording

### ISSUE THREAD

**Issue by maciex** [vkohaupt/vokoscreen#195]
A nice feature would be an option to block screen saver during recordings

**Comment by petergruenbeck** [comment]
I'm finding that Vokoscreen loses the recorded session if the screen sleeps, but gives no indication.  

On a related but separate issue, Vokoscreen loses the recorded session and restarts if the virtual desktop rotates.

**Comment by vkohaupt** [comment]
petergruenbeck schrieb am 16.11.2017 um 21:03:
> I'm finding that Vokoscreen loses the recorded session if the screen sleeps, but gives no indication.
> 
> On a related but separate issue, Vokoscreen loses the recorded session and restarts if the virtual desktop rotates.

Please specify, I do not like to pull everything out of your nose.
