### ISSUE TITLE
Dualscreen: Magnification only works on one screen

### ISSUE THREAD

**Issue by pjotrek-b** [vkohaupt/vokoscreen#197]
Vokoscreen works like a charm. Out-of-the-box. Thank you very much!
However, there's a small glitch when using the "magnification" option:

On my dual-screen setup, the magnification window doesn't work on the second screen.

Here's what happens:
- Mouse on main (1st) screen: everything works perfectly.
- Moving mouse to the other (2nd) screen right:
  magnified window stays at right-edge of the 1st screen.
- While mouse is on 2nd screen, magnified window doesn't update its contents.

Thought you might want to know?

**Comment by vkohaupt** [comment]
The "magnification" option works only on the first screen, it is not 
designed for dual-screen.
Maybe you can change the first screen to second and second to first in 
your system.
