### ISSUE TITLE
Custom cursor [feature]

### ISSUE THREAD

**Issue by apienk** [vkohaupt/vokoscreen#203]
We're creating highly customized video tutorials for K-12 schools. We need a way to set a custom cursor from image that would replace all system cursors. It could be implemented by storing cursor positions from `xdotool getmouselocation` while recording, then rendering the custom image at those positions on captured frames. Since this rendering would be a resource-intensive process, it may be done after recording stops.

**Comment by debuglevel** [comment]
Instead of modifying the video afterwards, why not just use a custom cursor in your desktop environment from the beginning?

**Comment by apienk** [comment]
Because it changes all the time. Move it over text and it's a vertical line, move it over a link and it's a hand, move it over a window edge and it's an arrow, etc. And if you use an application while screencasting, e.g. Inkscape or Gimp, you get a dozen additional cursors. Unless you're doing a tutorial on how to use the application it's a problem.

**Comment by tuxmuck** [comment]
The mouse pointer is a feature of the operating system - not the function of a screencast program.

**Comment by debuglevel** [comment]
Then you should set your desktop environments cursor to a static one. I can't imagine why a cursor should NOT change in a video, if it hovers a link.

**Comment by vkohaupt** [comment]
Hi Andrzej,

I think you means something like that
--start vokoscreen
--select Window
--press start
--an added custom cursor view

**Comment by apienk** [comment]
This is handy when you're recording a general presentation, not just showing software or your work in software, and you intend to use the cursor only for pointing (and, perhaps, handwriting or drawing). For example, you're creating a screencast tutorial on how to divide words into syllables and you'd like it to look professional. Or, you want to show things on the screen using a really large cursor so it's clearly visible on small screens or from large distances. In such cases you don't want cursor changes. Camtasia used to have this option to set a custom cursor but they turned it off.

It might be better to add this option to ffmpeg first. I looked briefly at its source code but I have zero skill in C programming. In [xcbgrab](https://github.com/FFmpeg/FFmpeg/blob/adc489adc97faf959f955933d198659f6227adb5/libavdevice/xcbgrab.c) there's a line:
`cursor = xcb_xfixes_get_cursor_image_cursor_image(ci);`. I think it may be used to load the image from a file instead. After it's done, very small changes in Vokoscreen would be necessary to implement that option. What do you think?
