### ISSUE TITLE
Support for 265?

### ISSUE THREAD

**Issue by manuelsongokuh** [vkohaupt/vokoscreen#204]
hi

will be good codec 265 for vokoscreen high quality and low size..?

thank you

**Comment by vkohaupt** [comment]
vokoscreen-beta has x265 support in mkv, mp4 and mov
The quality is good but size is higher as in x264 and the CPU is very 
high and to time i have no time to improve this.

**Comment by Martii** [comment]
Every capture that I've saved in HEVC *(h.265)*, the file size, has been smaller in comparison to AVC *(h.264) so far... but can be CPU intensive for slower machines.

**Comment by vkohaupt** [comment]
Interesting,
maschine is a 4 x Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
see images statusline

x264 --> 1022 KB
![screenshot_20180121_121216](https://user-images.githubusercontent.com/3152567/35193983-81d47884-feab-11e7-871d-fd737bca95d1.jpg)

x265 --> 1436 KB
![screenshot_20180121_121440](https://user-images.githubusercontent.com/3152567/35194007-e41bf760-feab-11e7-89d7-8a4672463469.jpg)

**Comment by vkohaupt** [comment]
Ok i see my mistake, by both x264 and x265 i have the same preset, and 
by x265 additionally a CRF option.
I remove the CRF option and all is good.

**Comment by Martii** [comment]
FYI: I usually use 30fps and mp4 container format usually... perhaps the source content is what makes a difference as well.
