### ISSUE TITLE
THANK YOU!

### ISSUE THREAD

**Issue by manuelsongokuh** [vkohaupt/vokoscreen#205]
hi, i want to say to @vkohaupt T+H+A+N+K+ +Y+O+U+, this TOOL is perfect! 
👍 💯  🥇 

all people will can to say thank to @vkohaupt

**Comment by jfarid27** [comment]
@vkohaupt can I donate Eth to you? Serious question. I want to donate but I have crypto.

**Comment by tuxmuck** [comment]
Donations are only possible with PayPal
