### ISSUE TITLE
Audio device determination

### ISSUE THREAD

**Issue by lambdacalculator** [vkohaupt/vokoscreen#206]
If the audio checkbox is on, but no audio source is selected, then an audio source should be chosen automatically for any recording that is started. Whenever I start vokoscreen (v. 2.5.0), the audio checkbox is on, but no audio source is selected. There have been several times when I made a recording, only to discover afterwards that there was no audio, even though I had my specialized microphone plugged into the USB port and recognized by vokoscreen, with the result that I had to re-record the entire video.

The audio device used by a recording, if not explicitly chosen by the user before recording starts, should be the one that was most recently used among all that are available at the time that a recording is started.

**Comment by vkohaupt** [comment]
Ok i see the problems and i answer in more mails, step by step

lambdacalculator schrieb am 31.01.2018 um 21:51:
> If the audio checkbox is on, but no audio source is selected, then an 
> audio source should be chosen automatically for any recording that is 
> started.

Ok, but what is, when the user don´t want audio?

**Comment by vkohaupt** [comment]
> Whenever I start vokoscreen (v. 2.5.0), the audio checkbox is 
> on, but no audio source is selected.

That´s right, so long no device is selected.


> There have been several times when 
> I made a recording, only to discover afterwards that there was no audio, 
> even though I had my specialized microphone plugged into the USB port 
> and recognized by vokoscreen, with the result that I had to re-record 
> the entire video.

If selected a device and the GUI will be closed, the selected device 
will be save and show on if the GUI new started.

But i see one Zenario the device is lose.
-start the GUI
-select a device
-close GUI
-plug off USB-Device
-start the GUI
-close the GUI
-plug on USB-Device
-start the GUI
and yes the device must new seleted.

And yes this all is not nice. For the first i want change that the audio 
checkbox is disable at the first start after install vokoscreen.

**Comment by tuxmuck** [comment]
You have a headset microphone, a webcam microphone, a sound card to record background music or other sound sources.
How should vokoscreen know what you want to record from where?
Today you just want to record background music, tomorrow the webcam with voice. You have to choose what you want, vokoscreen can't do that for you.

**Comment by lambdacalculator** [comment]
On every recording I make, I want audio. And every time I plug in my specialized USB microphone, I want to use that device to record audio. There should be a way where I don't have to explicitly select this device every time -- and sometimes end up forgetting to do this and have to re-record my video.

**Comment by debuglevel** [comment]
Software has to remember the user's choice. Even if the device was not available when vokoscreen was started somewhen - the user still set his choice, and a software should respect his choice and not unset it just because a device was not available.

So, whenever the preferred/chosen device is available (or even _becomes_ available during runtime), the device must be selected as input. If it is not available, the best might be to show a warning when starting a recording or on startup. Just selecting no input at all (or a random device) is not what one would expect.

**Comment by vkohaupt** [comment]
lambdacalculator schrieb am 01.02.2018 um 21:21:
> On every recording I make, I want audio. And every time I plug in my 
> specialized USB microphone, I want to use that device to record audio. 
> There should be a way where I don't have to explicitly select this 
> device every time -- and sometimes end up forgetting to do this and have 
> to re-record my video.

Is that what you mean, a simple cache. Whenever a device is plugged in, 
this is prioritized and selected.

**Comment by lambdacalculator** [comment]
> Is that what you mean, a simple cache. Whenever a device is plugged in, this is prioritized and selected.

Here is my detailed suggestion:

First, I should be able to set a preference that gives me three options: (1) enable audio by default, (2) disable audio by default, or (3) use previously selected setting. Option (3) means that if my previous recording had audio, then audio is enabled for the current recording, whereas if my previous recording didn't have audio, then audio is disabled for the current recording. If I had to choose defaults for these settings, I would choose (3) but disable audio the very first time vokoscreen was run.

Second, if a recording is started and audio is enabled but no audio device is selected, then the audio device should default to the most-recently-used device that is currently available. If there isn't such a device (for example, audio had never been used on a recording before), then there should be an alert asking the user to choose an audio device (or disable audio) before starting the recording.

Third, if an audio device is plugged in after a recording has started, then audio should be enabled (if it was disabled) and should select that device, whereas if the audio device that is currently being used during a recording is unplugged, then audio should switch sources to the most recently-used device that is currently available or disable audio altogether if there is no such device.

**Comment by vkohaupt** [comment]
Ouch, that's hundreds of hours of work until it's impelmented. Please 
check in the future if the device is selected.

**Comment by lambdacalculator** [comment]
If that's too much to do at once, then start with the most important part (from my perspective): don't allow a recording to be started if the audio checkbox is on but no audio device is selected. That alone would fix the problem I initially complained about.
