### ISSUE TITLE
No sound recorded with ALSA

### ISSUE THREAD

**Issue by Karmenzind** [vkohaupt/vokoscreen#212]
Video is well but no sound recorded.

Attached [alsa-info.txt](https://github.com/vkohaupt/vokoscreen/files/1965938/alsa-info.txt) generated by alsa-info.sh. Hope it may help.

----------

**screenfetch**

 OS: Arch Linux 
 Kernel: x86_64 Linux 4.16.5-1-ARCH
 Uptime: 23h 18m
 Packages: 1271
 Shell: bash 4.4.19
 Resolution: 1920x1080
 WM: i3
 GTK Theme: Vertex [GTK2/3]
 Icon Theme: Paper
 CPU: Intel Core i5-6500 @ 4x 3.6GHz [27.8°C]
 GPU: intel
 RAM: 3237MiB / 7835MiB

----------

**console output while recording**

[vokoscreen] Version: "2.5.8 Beta" 
[vokoscreen] Locale: "en_US" 
[vokoscreen] Qt version:  5.10.1 
[vokoscreen] Operating system: "Arch Linux" 
[vokoscreen] Platform: "xcb" 
[vokoscreen] Desktop: "" 
[vokoscreen] asoundlib version: "1.1.6" 
[vokoscreen] current icon-theme:  "hicolor" 
[vokoscreen] Qt-PluginsPath:      "/usr/lib/qt/plugins" 
[vokoscreen] Qt-TranslationsPath: "/usr/share/qt/translations" 
[vokoscreen] Qt-LibraryPath:      "/usr/lib" 
  
[vokoscreen] ---Begin Search external tools--- 
[vokoscreen] Search ffmpeg     ..... found "/usr/bin/ffmpeg" Version: "ffmpeg version 3.4.2 Copyright (c) 2000-2018 the FFmpeg developers" 
[vokoscreen] Search pactl      ..... found Version: "pactl 11.1" 
[vokoscreen] Search xdg-email  ..... found Version: "xdg-email 1.1.2" 
[vokoscreen] Search lsof       ..... found Version: "revision: 4.91" 
[vokoscreen] ---End search external tools--- 
  
[vokoscreen] ---Begin search Screen--- 
[vokoscreen] Number of screens: 1 
[vokoscreen] Primary screen is: Display 1 
[vokoscreen] VirtualDesktop: false 
[vokoscreen] DevicePixelRatio: 1  (Normal displays is 1, Retina display is 2) 
[vokoscreen] "Display 1:  1920 x 1080" 
[vokoscreen] ---End search Screen--- 
  
[vokoscreen] ---Begin Environment--- 
[vokoscreen] WAYLAND_DISPLAY is "" 
[vokoscreen] Is a X11 session 
[vokoscreen] Runs on DISPLAY ":0" 
[vokoscreen] ---End Environment--- 
  
[vokoscreen] ---Begin search formats--- 
[vokoscreen] find Format "mkv" 
[vokoscreen] ---Begin search video codec--- 
[vokoscreen] find Videocodec "libx264" 
[vokoscreen] 
find Videocodec "libx264rgb" 
[vokoscreen] find Videocodec "libx265" 
[vokoscreen] find Videocodec "mpeg4" 
[vokoscreen] find Videocodec "huffyuv" 
[vokoscreen] find Videocodec "libvpx" 
[vokoscreen] ---End search video codec--- 
  
[vokoscreen] ---Begin search audio codec--- 
[vokoscreen] find Audiocodec "libmp3lame" 
[vokoscreen] find Audiocodec "libvorbis" 
[vokoscreen] find Audiocodec "flac" 
[vokoscreen] find Audiocodec "pcm_s16le" 
[vokoscreen] not found Audiocodec "libvo_aacenc" 
[vokoscreen] find Audiocodec "aac" 
[vokoscreen] ---End search audio codec--- 
  
[vokoscreen] find Format "webm" 
[vokoscreen] find Format "mp4" 
[vokoscreen] find Format "gif" 
[vokoscreen] find Format "mov" 
[vokoscreen] ---End search formats--- 
  
[vokoscreen] ---Begin search Videoplayer--- 
[vokoscreen] Find Videoplayer : "/usr/bin/vlc" 
[vokoscreen] Find Videoplayer : "/usr/bin/smplayer" 
[vokoscreen] Find Videoplayer : "/usr/bin/mpv" 
[vokoscreen] ---End search Videoplayer--- 
  
[vokoscreen] ---Begin search GIFplayer--- 
[vokoscreen] Find GIFplayer : "firefox" 
[vokoscreen] Find GIFplayer : "mpv" 
[vokoscreen] Find GIFplayer : "chromium" 
[vokoscreen] ---End search GIFplayer--- 
  
[vokoscreen] ---Begin Pulse unload Module--- 
[vokoscreen] ---End Pulse unload Module--- 
  
[vokoscreen] ---Begin search devices--- 
[vokoscreen] find device "x11grab" 
[vokoscreen] ---End search devices--- 
  
[vokoscreen] ExtensionsPath: "/home/k/vokoscreen_extensions/" 
[vokoscreen] No library for extension found 
  
[vokoscreen] ---Begin search Alsa capture device--- 
[vokoscreen] Find CaptureCard: "[hw:0,0] HDA Intel PCH" 
[vokoscreen] Find CaptureCard: "[hw:1,0] Loopback" 
[vokoscreen] ---End search Alsa capture device--- 
  
[vokoscreen] ---Begin search PulseAudio Capture Devices--- 
[vokoscreen] ---End search PulseAudio Capture Devices--- 
  
[vokoscreen] recording fullscreen Display:  0 
[vokoscreen] Executing command: /usr/bin/ffmpeg -report -f x11grab -draw_mouse 1 -framerate 25 -video_size 1920x1080 -i :0+0,0 -f alsa -ac 2 -i hw:0,0 -pix_fmt yuv420p -c:v libx264 -preset veryfast -c:a libmp3lame -q:v 1 -s 1920x1080 -f matroska -threads 4 /home/k/Videos/.vokoscreen-recording/vokoscreen-2018-05-02_12-35-52.mkv 
  
[vokoscreen] "/usr/bin/ffmpeg" is running and is ready for reading and writing 
  
[vokoscreen] "/usr/bin/ffmpeg" is not running 
  
[vokoscreen] ---Begin Pulse unload Module--- 
[vokoscreen] ---End Pulse unload Module--- 
  
[vokoscreen] File VERSION available
  

----------

**aplay -L**

null
    Discard all samples (playback) or generate zero samples (capture)
pulse
    PulseAudio Sound Server
default
    Default ALSA Output (currently PulseAudio Sound Server)
sysdefault:CARD=PCH
    HDA Intel PCH, ALC887-VD Analog
    Default Audio Device
front:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Analog
    Front speakers
surround21:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Analog
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Analog
    4.0 Surround output to Front and Rear speakers
surround41:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Analog
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Analog
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Analog
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Analog
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Digital
    IEC958 (S/PDIF) Digital Audio Output
hdmi:CARD=PCH,DEV=0
    HDA Intel PCH, HDMI 0
    HDMI Audio Output
hdmi:CARD=PCH,DEV=1
    HDA Intel PCH, HDMI 1
    HDMI Audio Output
hdmi:CARD=PCH,DEV=2
    HDA Intel PCH, HDMI 2
    HDMI Audio Output
sysdefault:CARD=Loopback
    Loopback, Loopback PCM
    Default Audio Device
front:CARD=Loopback,DEV=0
    Loopback, Loopback PCM
    Front speakers
surround21:CARD=Loopback,DEV=0
    Loopback, Loopback PCM
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=Loopback,DEV=0
    Loopback, Loopback PCM
    4.0 Surround output to Front and Rear speakers
surround41:CARD=Loopback,DEV=0
    Loopback, Loopback PCM
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=Loopback,DEV=0
    Loopback, Loopback PCM
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=Loopback,DEV=0
    Loopback, Loopback PCM
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=Loopback,DEV=0
    Loopback, Loopback PCM
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers

**Comment by Karmenzind** [comment]
[alsa-info.txt](https://github.com/vkohaupt/vokoscreen/files/1965940/alsa-info.txt)

**Comment by vkohaupt** [comment]
You can provide a video for download?

**Comment by vkohaupt** [comment]
And please make a short record and put here then the ffmpeg log from 
~/config/vokoscreen

**Comment by Karmenzind** [comment]
Sorry for the late.
I just found the background sound has been actually recorded, but too weak, like whispering.
I've made a new video 
[vokoscreen-2018-05-06_17-56-43.mkv.log](https://github.com/vkohaupt/vokoscreen/files/1977515/vokoscreen-2018-05-06_17-56-43.mkv.log)
 (need to download and rename it to mkv).
Here are my 
[console_output.log](https://github.com/vkohaupt/vokoscreen/files/1977518/console_output.log)
and 
[ffmpeg-20180506-175643.log](https://github.com/vkohaupt/vokoscreen/files/1977523/ffmpeg-20180506-175643.log).
Thanks for your help!

**Comment by tuxmuck** [comment]
The sliders you use are for the speaker only.
You need to boost the internal volume level.

But I don't know where that is with Arch.

**Comment by zwastik** [comment]
I have the same issue, alsa volume controls are at max in alsamixer.
