### ISSUE TITLE
Recording black screen with a mouse cursor

### ISSUE THREAD

**Issue by probonopd** [vkohaupt/vokoscreen#213]
Getting only a black screen with a mouse cursor when trying to record in Fedora 29 Rawhide using Vokoscreen 2.5.1 Beta RUN version.

Example:
https://www.youtube.com/watch?v=aUjOIGUz97M&feature=youtu.be

**Comment by probonopd** [comment]
Possibly caused by https://github.com/vkohaupt/vokoscreen/issues/191, but what is the solution?

**Comment by vkohaupt** [comment]
Hi probonopd,

All X11 applications running on a Wayland Desktop will not have access 
to the screen. The best way is to switch to X11 when logging in.

**Comment by vkohaupt** [comment]
To time gives not a Desktop Cross solution.

**Comment by probonopd** [comment]
Would it be possible to have vokoscreen detect whether Wayland is running or not and at least give a warning/refuse recording, or (better) use a different method for recording when it detects that Wayland is running?

**Comment by Martii** [comment]
@probonopd 
There's a few search results for detecting Wayland vs X11 both configure/compile and runtime... from the description probably [this comment](https://forum.qt.io/topic/54592/qt-5-x-on-linux-detect-x11-vs-wayland/12) would be the most likely runtime... e.g. if `XGrabKey()` or some other similar function failed it may be enough of a flag to determine it.

**Comment by probonopd** [comment]
https://github.com/foss-project/green-recorder uses the D-Bus API to connect to the built-in screencasting tool in GNOME Shell. It uses this to record video. To record audio, it launches an instance of ffmpeg in the background. After the recording is finished, it merges the two files into the WebM file. For Xorg, it uses ffmpeg only for both audio and video.

Maybe that could be a solution for vokoscreen as well?

**Comment by probonopd** [comment]
The environment variable `XDG_SESSION_TYPE` contains the string `wayland` in Wayland sessions, according to https://github.com/foss-project/green-recorder/blob/master/green-recorder#L69-L82

**Comment by ryanrain** [comment]
also seeing this in debian buster, and also it appears that the option to login using x11, present in stretch, has been removed. thanks everyone!

**Comment by probonopd** [comment]
Wait, are they now forcing Wayland on us?

**Comment by umeklinks** [comment]
Please check this link, the issue has be fixed:
https://github.com/MaartenBaert/ssr/issues/565#issuecomment-518389403

**Comment by glaubersm** [comment]
your link contains no fix.
vokoscreen needs Wayland support.

**Comment by umeklinks** [comment]
> your link contains no fix.
> vokoscreen needs Wayland support.

I just edited it to fix in the full solution.

**Comment by knows1** [comment]
Vockoscreen black screen
