### ISSUE TITLE
Warning: QImage::scaled: Image is a null image ((null):0, (null))`

### ISSUE THREAD

**Issue by dtschmitz** [vkohaupt/vokoscreen#216]
`[dts@dts-pc Videos]$ vokoscreen &
[1] 18726
[dts@dts-pc Videos]$ qt5ct: using qt5ct plugin
[vokoscreen] Version: 2.5.8 Beta 
[vokoscreen] Locale: en_US 
[vokoscreen] Qt version: 5.11.0 
[vokoscreen] Operating system: Manjaro Linux 
[vokoscreen] Platform: xcb 
[vokoscreen] Desktop: XFCE 
[vokoscreen] asoundlib version: 1.1.6 
[vokoscreen] current icon-theme:  Vertex-Maia 
[vokoscreen] Qt-PluginsPath:      /usr/lib/qt/plugins 
[vokoscreen] Qt-TranslationsPath: /usr/share/qt/translations 
[vokoscreen] Qt-LibraryPath:      /usr/lib 
  
[vokoscreen] ---Begin Search external tools--- 
[vokoscreen] Search ffmpeg     ..... found "/usr/bin/ffmpeg" Version: "ffmpeg version 4.0 Copyright (c) 2000-2018 the FFmpeg developers" 
[vokoscreen] Search pactl      ..... found Version: "pactl 11.1" 
[vokoscreen] Search xdg-email  ..... found Version: "xdg-email 1.1.3" 
[vokoscreen] Search lsof       ..... found Version: "revision: 4.91" 
[vokoscreen] ---End search external tools--- 
  
[vokoscreen] ---Begin search Screen--- 
[vokoscreen] Number of screens: 1 
[vokoscreen] Primary screen is: Display 1 
[vokoscreen] VirtualDesktop: false 
[vokoscreen] DevicePixelRatio: 1  (Normal displays is 1, Retina display is 2) 
[vokoscreen] Display 1:  1366 x 768 
[vokoscreen] ---End search Screen--- 
  
[vokoscreen] ---Begin Environment--- 
[vokoscreen] WAYLAND_DISPLAY is "" 
[vokoscreen] Is a X11 session 
[vokoscreen] Runs on DISPLAY ":0.0" 
[vokoscreen] ---End Environment--- 
  
[vokoscreen] ---Begin search formats--- 
[vokoscreen] find Format "mkv" 
[vokoscreen] ---Begin search video codec--- 
[vokoscreen] find Videocodec "libx264" 
[vokoscreen] find Videocodec "libx264rgb" 
[vokoscreen] find Videocodec "libx265" 
[vokoscreen] find Videocodec "mpeg4" 
[vokoscreen] find Videocodec "huffyuv" 
[vokoscreen] find Videocodec "libvpx" 
[vokoscreen] ---End search video codec--- 
  
[vokoscreen] ---Begin search audio codec--- 
[vokoscreen] find Audiocodec "libmp3lame" 
[vokoscreen] find Audiocodec "libvorbis" 
[vokoscreen] find Audiocodec "flac" 
[vokoscreen] find Audiocodec "pcm_s16le" 
[vokoscreen] not found Audiocodec "libvo_aacenc" 
[vokoscreen] find Audiocodec "aac" 
[vokoscreen] ---End search audio codec--- 
  
[vokoscreen] find Format "webm" 
[vokoscreen] find Format "mp4" 
[vokoscreen] find Format "gif" 
[vokoscreen] find Format "mov" 
[vokoscreen] ---End search formats--- 
  
[vokoscreen] ---Begin search Videoplayer--- 
[vokoscreen] Find Videoplayer : "/usr/bin/vlc" 
[vokoscreen] ---End search Videoplayer--- 
  
[vokoscreen] ---Begin search GIFplayer--- 
[vokoscreen] Find GIFplayer : "firefox" 
[vokoscreen] Find GIFplayer : "chromium" 
[vokoscreen] ---End search GIFplayer--- 
  
[vokoscreen] ---Begin Pulse unload Module--- 
[vokoscreen] ---End Pulse unload Module--- 
  
D-Bus system tray: no 
[vokoscreen] ---Begin search devices--- 
[vokoscreen] find device "x11grab" 
[vokoscreen] ---End search devices--- 
  
[vokoscreen] ExtensionsPath: "/home/dts/vokoscreen_extensions/" 
[vokoscreen] No library for extension found 
  
[vokoscreen] ---Begin search Alsa capture device--- 
[vokoscreen] Find CaptureCard: "[hw:0,0] HDA Intel MID" 
[vokoscreen] ---End search Alsa capture device--- 
  
[vokoscreen] ---Begin search PulseAudio Capture Devices--- 
[vokoscreen] Find CaptureCard: "Monitor of Built-in Audio Analog Stereo" with device: "alsa_output.pci-0000_00_1b.0.analog-stereo.monitor" 
[vokoscreen] Find CaptureCard: "Built-in Audio Analog Stereo" with device: "alsa_input.pci-0000_00_1b.0.analog-stereo" 
[vokoscreen] ---End search PulseAudio Capture Devices--- 
  
111111111111111111111111111111111111111111111 timer ist an 
[vokoscreen] ---Begin search cameras--- 
[vokoscreen] "Integrated Camera: Integrated C" "/dev/video0" 
[vokoscreen] ---End search cameras--- 
  
[vokoscreen] QCamera::LoadedState 
[vokoscreen] ---Begin search camera parameters and checkbox is disabled--- 
[vokoscreen] camera resolutions (QSize(320, 240), QSize(352, 288), QSize(640, 480), QSize(800, 600), QSize(1024, 768), QSize(1280, 720), QSize(1280, 800), QSize(1600, 1200)) 
[vokoscreen] ---End search camera parameters and checkbox is disabled--- 
 
Warning: Unable to query the parameter info: "Invalid argument" ((null):0, (null))
Warning: Unable to query the parameter info: "Invalid argument" ((null):0, (null))
111111111111111111111111111111111111111111111 timer ist an 
111111111111111111111111111111111111111111111 timer ist an 
111111111111111111111111111111111111111111111 timer ist an 
111111111111111111111111111111111111111111111 timer ist an 
111111111111111111111111111111111111111111111 timer ist an 
111111111111111111111111111111111111111111111 timer ist an 
111111111111111111111111111111111111111111111 timer ist an 
111111111111111111111111111111111111111111111 timer ist an 
111111111111111111111111111111111111111111111 timer ist an 
111111111111111111111111111111111111111111111 timer ist an 
111111111111111111111111111111111111111111111 timer ist an 
111111111111111111111111111111111111111111111 timer ist an 
111111111111111111111111111111111111111111111 timer ist an 
111111111111111111111111111111111111111111111 timer ist an 
111111111111111111111111111111111111111111111 timer ist an 
111111111111111111111111111111111111111111111 timer ist an 
111111111111111111111111111111111111111111111 timer ist an 
111111111111111111111111111111111111111111111 timer ist an 
111111111111111111111111111111111111111111111 timer ist an 
111111111111111111111111111111111111111111111 timer ist an 
111111111111111111111111111111111111111111111 timer ist an 
111111111111111111111111111111111111111111111 timer ist an 
111111111111111111111111111111111111111111111 timer ist an 
[vokoscreen] QCamera::LoadingStatus 
[vokoscreen] QCamera::LoadedStatus 
 
Warning: Unable to query the parameter info: "Invalid argument" ((null):0, (null))
Warning: Unable to query the parameter info: "Invalid argument" ((null):0, (null))
[vokoscreen] QCamera::StartingStatus 
111111111111111111111111111111111111111111111 timer ist an 
[vokoscreen] ---Begin search cameras--- 
[vokoscreen] ---End search cameras--- 
  
[vokoscreen] QCamera::LoadingStatus 
[vokoscreen] QCamera::UnloadingStatus 
[vokoscreen] QCamera::UnloadedStatus 
[vokoscreen] camera removed "/dev/video0" 
  
**Warning: QImage::scaled: Image is a null image ((null):0, (null))`**

**Comment by tuxmuck** [comment]
Please try them out::

1. switch off timer
2. delete the hidden folder ~/config/vokoscreen
