### ISSUE TITLE
Border option no longer available for webcam

### ISSUE THREAD

**Issue by nateGeorge** [vkohaupt/vokoscreen#217]
I think in 2.1.0, there was an option to remove the window border around the webcam frame.  I'm not seeing this option in the latest beta version, or in 2.4.0.  However, the variables still seem to be in some files, like in settings/QvkSettings.cpp

Here was the line from the changes log:

Sep 14, 2014 : border and Noborder in webcam menu now [x]Border

http://linuxecke.volkoh.de/vokoscreen/vokoscreen-changes.html

Is this option just not available for Ubuntu or something, or was it somehow removed?  Or is there some other issue?  I'm on Ubuntu 16.04.

**Comment by tuxmuck** [comment]
Click with the right mouse button **into** the webcam image.
-> frame on / off

**Comment by nateGeorge** [comment]
Ah, so simple!  Thanks.
