### ISSUE TITLE
maybe is bug: missing alpha for "showclick"

### ISSUE THREAD

**Issue by manuelsongokuh** [vkohaupt/vokoscreen#218]
hi
version is 2.5 vokoscreen

i activated showclick but result missing alpha..instead background is black..

linux opensuse tumbleweed 2018

**Comment by manuelsongokuh** [comment]
![mpv-shot0008](https://user-images.githubusercontent.com/12126929/42410273-74c02af2-81e7-11e8-9926-17a2fa7338b8.jpg)

**Comment by tuxmuck** [comment]
Activate the compositor in the system settings.
Hardware - Monitor - Compositor.

**Comment by manuelsongokuh** [comment]
ooh that is works thank you!
