### ISSUE TITLE
Recordings are missing footage

### ISSUE THREAD

**Issue by Awkky** [vkohaupt/vokoscreen#219]
I've attempted to record long videos of CS 1.6 gameplay with my nephew and brother so I could capture funny stuff happening naturally, but videos over an hour and 10 minutes or so seem to randomly cut off, even though I still click the "Stop" button to end the recording. I recorded audio separately today and my audio recording was about 30 minutes longer than my video, which sucks because I tried going straight to the end of my recording to get the best stuff and it was all gone. No idea why it does this.

**Comment by tuxmuck** [comment]
Maybe a problem with your /tmp folder?
These cannot become "infinitely" large.
