### ISSUE TITLE
Make the show key option more configurable?

### ISSUE THREAD

**Issue by DuendeInexistente** [vkohaupt/vokoscreen#221]
I like the show keys option, I really do. It's just *terribly obnoxious* at a visual level.

Would it be feasible to add options to configure it, ie: changing the font size/area where it's displayed? If I could just keep it to a corner of the screen it'd be great.

Btw I saw there's another open issue regarding a similar topic, and I see how they could be merged -Adding this would essentially fix the other one- but I think these are two separate matters.

**Comment by ElijahLynn** [comment]
Would love this too, my main like for this is to control the timeout on it, currently it is set to ~5 seconds, and I want it to be closer to 1-2 seconds.

**Comment by adexmont** [comment]
https://github.com/wavexx/screenkey#installation-and-basic-usage
Sorry if not legit but this looks a good addon, not sure it may be included in vokoscreen hope you can add it in a easy way or improve the code u already wrote.
