### ISSUE TITLE
How to display Showkey info inside recording Area

### ISSUE THREAD

**Issue by MurzNN** [vkohaupt/vokoscreen#222]
When I record a small area of screen, the Showkey feature shows keys line aligned to full screen, not into the capturing area. How can I configure it to show keys inside selected capturing area?

**Comment by tuxmuck** [comment]
I'm afraid that's not possible.

**Comment by vcardenas** [comment]
Maybe is it possible to do it by display selected?
I have two displays/monitors/screens setup but often I need to record only one of them. The showkey feature spans across the two displays allowing to capture only half of keys displayed.

**Comment by MurzNN** [comment]
vcardenas, I got same problem, with 2 displays Showkey string shows stretched to both screens width :(
