### ISSUE TITLE
Problems : folder name with accents

### ISSUE THREAD

**Issue by LomigLavnek** [vkohaupt/vokoscreen#224]
Hi,

I found a bug with folder containing accent in their name.
My video folder is named Vidéos (I'm french) and I can't pause and restart a recording. It's looking in Vidos folder instead of Vidéos to find previous state.

```
Opening an input file: /tmp/mergeFile.txt.
[concat @ 0x55c8a71e7e00] Opening '/tmp/mergeFile.txt' for reading
[file @ 0x55c8a71e8880] Setting default whitelist 'file,crypto'
[NULL @ 0x55c8a71f1c40] Opening '/home/lomig/Vidos/.vokoscreen-recording/vokoscreen-2018-10-17_10-30-47.mkv' for reading
[concat @ 0x55c8a71e7e00] Impossible to open '/home/lomig/Vidos/.vokoscreen-recording/vokoscreen-2018-10-17_10-30-47.mkv'
[AVIOContext @ 0x55c8a71f0d40] Statistics: 154 bytes read, 0 seeks
/tmp/mergeFile.txt: No such file or directory

```

thanks

**Comment by tuxmuck** [comment]
Rename the folder to Videos and everything is fine.
It is not possible to implement all languages with all their possible accents.

**Comment by debuglevel** [comment]
It's not about implementing languages, but just about supporting Unicode properly. That should not be a big issue, as most software is able to handle paths in Unicode.

**Comment by vkohaupt** [comment]
tuxmuck schrieb am 17.10.18 um 11:32:
> Rename the folder to Videos and everything is fine.

Renaming the video folder is a very bad idea, any program that uses the 
"Vidéos" folder, including vokoscreen, will not find the new "Videos" 
folder.

I have two workarounds. To change the video folder global in KDE, Gnome etc.
Or much better within vokoscreen to change the video path so this only 
affects in vokoscreen.


> It is not possible to implement all languages with all their possible 
> accents.

It is the task of the operating system to provide and support this. Why 
vokoscreen not like accent in the pause function can only see in the 
analysis of the sourcecode.

**Comment by vkohaupt** [comment]
Marc Kohaupt schrieb am 17.10.18 um 12:39:
> It's not about implementing languages, but just about supporting Unicode 
> properly. That should not be a big issue, as most software is able to 
> handle paths in Unicode.

That's exactly how it is. I did not implement correctly, it is my fault.

**Comment by debuglevel** [comment]
Qt provides a QDir class; this might be a reliable, stable and cross-plattform-proof way to handle paths/directories.
