### ISSUE TITLE
GIF size much larger than Peeks

### ISSUE THREAD

**Issue by ElijahLynn** [vkohaupt/vokoscreen#226]
Love Vokoscreen! The one thing keeping me from using it more is that the GIF sizes are significantly larger than Peek. Is there a way we can provide some settings or a more efficient default to get the GIF sizes down? 

I tried recording a ~10 second GIF twice now and the size was 20-30MB and isn't uploadable to Twitter or GitHub. Peak's GIF doing the same fullscreen area is under 5MB.

**Comment by milosonator** [comment]
Same/similar issue here: The image size is very large, and the quality is very low. As far as I know, ffmpeg is able to create much better gifs, so probably needs a bit of parameter tuning. Would be greatly appreciated. (Currently I make an mp4 and pull it through one of these crappy online converters)
