### ISSUE TITLE
Pixelated icons and bad font rendering when fractional display scaling is used on linux

### ISSUE THREAD

**Issue by glaubersm** [vkohaupt/vokoscreen#228]
Hi

I use vokoscreen 2.9.5 beta on Arch Linux running KDE Plasma 5.15.2 desktop environment
with fractional display scaling enabled.
To enabled it, open system settings > display and monitor > scale display, set scale factor to 1.2
and relogin.
As we can see in my screenshot, vokoscreen shows pixelated icons and fonts in the left side
are badly rendered.

![vokoscreen](https://user-images.githubusercontent.com/15967631/53701143-dc506f80-3dd8-11e9-818e-149024b70f10.png)

**Comment by Martii** [comment]
@glaubersm 

> I use vokoscreen 2.9.5 beta on Arch Linux...

2.9.5? vs [releases](https://github.com/vkohaupt/vokoscreen/releases)

**Comment by Martii** [comment]
Ahh I see... see https://github.com/vkohaupt/vokoscreenNG
