### ISSUE TITLE
VP8 support

### ISSUE THREAD

**Issue by TuxNuX** [vkohaupt/vokoscreen#229]
Hi,

I compiled version 2.5.6 and have VP8 support (libvpx)
I compiled version 2.9.5 and I do not have VP8 support
both compiled with the same options and the same devel libraries

![Screenshot_20190407_003043](https://user-images.githubusercontent.com/17123357/55676041-dadd0000-58cc-11e9-9b6a-a95e38d712b4.png)
![Screenshot_20190407_002916](https://user-images.githubusercontent.com/17123357/55676042-db759680-58cc-11e9-8fa3-87bb2e12b7cf.png)

**Comment by vkohaupt** [comment]
Please read
https://github.com/vkohaupt/vokoscreenNG/blob/master/INSTALL
or
https://github.com/vkohaupt/vokoscreenNG

**Comment by TuxNuX** [comment]
> Please read
> https://github.com/vkohaupt/vokoscreenNG/blob/master/INSTALL
> or
> https://github.com/vkohaupt/vokoscreenNG

I had already read this :)
here are the buildrequires and requires from spec file

```
BuildRequires:  desktop-file-utils
BuildRequires:  pkgconfig(alsa)
BuildRequires:  ffmpeg-devel
BuildRequires:  libv4l-devel
BuildRequires:  opencv-devel
BuildRequires:	pkgconfig(Qt5Core)
BuildRequires:	pkgconfig(Qt5Gui)
BuildRequires:	pkgconfig(Qt5MultimediaWidgets)
BuildRequires:	pkgconfig(Qt5Widgets)
BuildRequires:	pkgconfig(Qt5X11Extras)
BuildRequires:	pkgconfig(gstreamer-pbutils-1.0) >= 1.12.5
BuildRequires:	pkgconfig(gstreamer-plugins-base-1.0) >= 1.12.5
BuildRequires:	pkgconfig(gstreamer-plugins-bad-1.0) >= 1.12.5
BuildRequires:  qttools5
BuildRequires:  pkgconfig
%ifarch x86_64
BuildRequires:	lib64qt5base5-devel >= 5.9.4
%endif
%ifarch %{ix86}
BuildRequires:	libqt5base5-devel >= 5.9.4
%endif
Requires:       gstreamer1.0-vaapi >= 1.12.5
Requires:       gstreamer1.0-plugins-good >= 1.12.5
Requires:       gstreamer1.0-plugins-bad >= 1.12.5
Requires:       gstreamer1.0-plugins-base >= 1.12.5
Requires:       alsa-utils
Requires:	    ffmpeg
Requires:	    lame
Requires:	    lsof
Requires:       mkvtoolnix
Requires:       pulseaudio-utils
Requires:       v4l-utils
Requires:       mpv

```
and VP8 no work
![Screenshot_20190407_133430](https://user-images.githubusercontent.com/17123357/55682927-15c94d00-593a-11e9-80a2-0c52fd664d61.png)

**Comment by tuxmuck** [comment]
Required does not say that it is needed for running ability.
A VP8/VP9 codec library must be installed by yourself.

**Comment by TuxNuX** [comment]
> Required does not say that it is needed for running ability.
> A VP8/VP9 codec library must be installed by yourself.

Ohhh  thanks to you !

I just came to find the problem
just need to add
Requires:   gstreamer1.0-vp8
and good work
![Screenshot_20190407_133430](https://user-images.githubusercontent.com/17123357/55683312-870aff00-593e-11e9-877d-acc47dbc41f4.png)
