### ISSUE TITLE
Vokoscreen window does not scale

### ISSUE THREAD

**Issue by Jacob-Vlijm** [vkohaupt/vokoscreen#232]
Working on a 4k laptop, It seems obvious that the Vokoscreen application window does not act on the set scaling (200%). 

Ubuntu Budgie 19.04, screen 3840 x 2160, scale 200%. Vokoscreem 2.5.0

![Screenshot from 2019-06-29 22-11-40](https://user-images.githubusercontent.com/8932980/60389067-78566300-9abb-11e9-9b56-144407ff635a.png)

If you need testing on 4k, I'd be happy to help out.

**Comment by tuxmuck** [comment]
You can enlarge the window with the mouse.
At the edge or in the corners.

**Comment by Jacob-Vlijm** [comment]
@tuxmuck I am afraid you don't understand. It is about scaling, not just window size. All elements, fonts, images, are not scaled to set scaling.

**Comment by tuxmuck** [comment]
Sorry, I misunderstood.

**Comment by Jacob-Vlijm** [comment]
No problem :) Thanks!

**Comment by debuglevel** [comment]
I guess your desktop environment is GTK+ based and you set the scaling in its settings. Vokoscreen is a Qt application, which may need additional settings. Could you try if some other Qt based applications do scale correctly? If they do not scale, you could try setting the environment variable like this: https://wiki.archlinux.org/index.php/HiDPI#Qt_5

**Comment by Jacob-Vlijm** [comment]
@debuglevel You're right. I tried VLC, same issue. Settings variables as in the link does not give any change though unfortunately.
