### ISSUE TITLE
does not record if default videopath does not exist

### ISSUE THREAD

**Issue by mtennie** [vkohaupt/vokoscreen#233]
Using Debian Buster

Upon first use, the default videopath was /home/user/Videos, however /Videos did not exist.  When pressing Start I expected that it would either make this directory and place a recording there, or throw an error and refuse to record.  I came to find that it silently failed to record a video instead.

**Comment by Martii** [comment]
Please note that https://github.com/vkohaupt/vokoscreenNG is activly being developed right now. 

Presuming this happens it kind of sucks but my distro automatically generates these on user creation. Work-around for described issue...  `mkdir ~/Videos` or change it to a valid path first in the options. :smile_cat:
