### ISSUE TITLE
Support for WebM

### ISSUE THREAD

**Issue by steelbrain** [vkohaupt/vokoscreen#93]
WebM provides good quality with a significant reduction in the file size. It would be great to have vokoscreen support it as a video format.

**Comment by borisov87** [comment]
+1 for this feature.

**Comment by Omnifarious** [comment]
+2 for this feature. :-) I really like your 'capture a window' feature, and simplescreenrecorder is missing it. But WebM/VP8 support would be very nice as it seems like a really good format for screen recordings.

**Comment by tuxmuck** [comment]
Coming soon - in the next release.

**Comment by manuelsongokuh** [comment]
+5 this feature!

**Comment by vkohaupt** [comment]
![screenshot_20180120_141116](https://user-images.githubusercontent.com/3152567/35183800-236d14b4-fdec-11e7-9865-9c81f0084044.jpg)

**Comment by manuelsongokuh** [comment]
![immagine](https://user-images.githubusercontent.com/12126929/35183898-87bfb6c8-fded-11e7-879d-9cdecef431b4.png)

**Comment by manuelsongokuh** [comment]
maybe it is for next version..?

**Comment by vkohaupt** [comment]
please look at the title bar from my image

**Comment by manuelsongokuh** [comment]
okay, when will be release stable..?

**Comment by vkohaupt** [comment]
To time i write a new area selection. This new area is kompatibel with 
X11, Wayland and XWayland.
New Feature, by click on a button it turns to yellow and shows the X/Y 
coordinates.

The new releas comes, but first if all it finsh.

**Comment by vkohaupt** [comment]
Here the new area selection in progress.
![bild](https://user-images.githubusercontent.com/3152567/35189533-6ea959be-fe4c-11e7-9c6b-a9bb935abc7e.png)

**Comment by Martii** [comment]
> by click on a button it turns to yellow and shows the X/Y

Nice. Maybe some savable presets at some point would be awesome too... I'm patient though. Great app btw. :)

**Comment by vkohaupt** [comment]
Which presets do you mean?

**Comment by Martii** [comment]
Coordinates for the capture area... typically I'm switching on a system with multiple screens between 4:3 aspect ratio and then 16x9 aspect ratio a lot. e.g. have to resize constantly in the same spots. `x`, `y`, `width`, `height` ... usually `height` and `y` gets toggled.... but `x` and `width` remain constant... however a full preset would let me toggle quicker without using the mouse drag to resize the capture window.
