### ISSUE TITLE
Add the chance to show menu indicator entry from panel icon.

### ISSUE THREAD

**Issue by Alejo-K** [vkohaupt/vokoscreen#95]
I'm using Vokoscreen for about a 2 month and everything works flawless except for a few inconsistencies or little bugs on interface, semi translated features (in spanish lang). Well but there is a feature that really miss on this screencaster, that panel icon could show a menu entry like sound applet indicator. With a few buttons like stop, start, pause recording and a framerate change. I mean give it the possible of handled this app, completely from the systray icon indicator.
Something like this: 
![menu-entry-1](https://cloud.githubusercontent.com/assets/9622594/4971666/a43c0dc6-6884-11e4-9eed-07ab18d641be.png)
I don't know, if this is the right place, but I couldn't find a vokoscreen forum. Thanks for this great app.

**Comment by manuelsongokuh** [comment]
sorry, i love crazy to use vokoscreen!!! but i love icon "play" and "stop" in tray icon, opensuse 13.2.
but version 2.3 there are icons for play and stop in tray icon..
today 2.4 is missed or remove...why?
