### ISSUE TITLE
No interface in IceWm

### ISSUE THREAD

**Issue by Fibroblasto** [vkohaupt/vokoscreen#97]
In the last beta (2.1.7) no interface appears while in IceWm as a window manager. I get the icon in the toolbar and I can start and stop recording, but I get no interface at all to change the settings, while the stable version shipped in the Debian repositories works fine. If I start the beta version in the KDE environment, vokoscreen interface appears without any problem.

I am using Debian Wheezy and IceWm 1.3.7-4

**Comment by vkohaupt** [comment]
Please give me the contents of the file
~/.config/vokoscreen/vokoscreen.conf

**Comment by Fibroblasto** [comment]
vokoscreen.conf:

[Alsa]
Alsa=false
NameCaptureCard=

[Area]
Height=557
NoShowInTaskBar=1
Width=978
X=590
Y=201

[Audio]
AudioOnOff=2

[GUI]
Systray=2
Tab=5
X=894
Y=258

[Miscellaneous]
Countdown=0
Minimized=0
VideoPath=/home/durr/Videos
Videoplayer=vlc

[Pulse]
NameCaptureCard-1=Monitor of Audio Interno Est\xe9reo Anal\xf3gico
Pulse=true

[Record]
Area=false
FullScreen=false
Window=true

[Videooptions]
Audiocodec=libmp3lame
Format=mkv
Frames=25
HideMouse=0
Videocodec=libx264

[Webcam]
Border=true
Bottom=true
Height=240
Left=false
Mirrored=0
Right=false
Rotate=0
Top=false
Width=320
X=100
Y=100

[vokoscreen]
Version=2.1.7 Beta


--------------------

If I rename vokoscreen.conf, starting again the beta version makes a new one with this:

[vokoscreen]
Version=2.1.7 Beta

**Comment by vkohaupt** [comment]
You build with Qt4 or Qt5?

**Comment by Fibroblasto** [comment]
That was the problem!

I had built it with Qt5 qmake.

After your question I have built it again, this time with Qt4 qmake and I have an interface again. Thanks a lot!!!

My problem is solved, but I can perform more test if you want.

By the way, a great piece of software indeed. I have tried similar programs and this is the only one that works perfect. Thanks a lot for your work.

**Comment by vkohaupt** [comment]
You can test once more IceWm with Qt5, start vokoscreen from a terminal 
and give me the complete output.

**Comment by Fibroblasto** [comment]
Upgraded with "git pull".
compiled with Qt5 and the problem persist.

Terminal output:


[vokoscreen] Locale: "es_ES"
[vokoscreen] Version: "2.1.7 Beta"
[vokoscreen] Qt Version:  5.3.2
[vokoscreen] asoundlib Version: "1.0.25"
[vokoscreen] current icon-theme: ""

[vokoscreen] ---Begin Search external tools---
[vokoscreen] Search avconv ..... found Version: "version"
[vokoscreen] Search pactl  ..... found Version: "4.0"
[vokoscreen] Search mkvmerge ... found Version: "v7.5.0"
[vokoscreen] ---End search external tools---

[vokoscreen] ---Begin RecordApplikation---
[vokoscreen] Used "avconv"
[vokoscreen] ---End RecordApplikation---

Fontconfig warning: "~/.fonts.conf", line 588: saw number, expected matrix
[vokoscreen] ---Begin search Screen---
[vokoscreen] Number of screens: 1
[vokoscreen] Primary screen is: Display 1
[vokoscreen] VirtualDesktop: false
[vokoscreen] "Display 1:  1920 x 1080"
[vokoscreen] ---End search Screen---

[vokoscreen] ---Begin Environment---
[vokoscreen] runs on DISPLAY ":0"
[vokoscreen] ---End Environment---

[vokoscreen] ---Begin search Videoplayer---
[vokoscreen] Find Videoplayer : "/usr/bin/dragon"
[vokoscreen] Find Videoplayer : "/usr/bin/gxine"
[vokoscreen] Find Videoplayer : "/usr/bin/vlc"
[vokoscreen] Find Videoplayer : "/usr/bin/xine"
[vokoscreen] ---End search Videoplayer---

[vokoscreen] [Regional selection] Frame locked: false

[vokoscreen] ---Begin search PulseAudio Plugin---
[vokoscreen] Found file .asound for PulseAudio Plugin
[vokoscreen] ---End search PulseAudio Plugin---


[vokoscreen] ---Begin Pulse unload Module---
[vokoscreen] ---End Pulse unload Module---

[vokoscreen] ---Begin search Alsa capture device---
[vokoscreen] alsa_device_sample() in alsadevice.c: cannot open audio device hw:0,0 (Dispositivo o recurso ocupado)
[vokoscreen] Find CaptureCard: "[hw:0,0] HDA ATI SB"
[vokoscreen] alsa_device_sample() in alsadevice.c: cannot open audio device hw:1,3 (No existe el fichero o el directorio)
[vokoscreen] Find CaptureCard: "[hw:1,3] HDA ATI HDMI"
[vokoscreen] alsa_device_sample() in alsadevice.c: cannot open audio device hw:2,0 (Dispositivo o recurso ocupado)
[vokoscreen] Find CaptureCard: "[hw:2,0] AK5370"
[vokoscreen] ---End search Alsa capture device---

[vokoscreen] ---Begin search PulseAudio Capture Devices---
[vokoscreen] Find CaptureCard: "Monitor of Audio Interno Estéreo Analógico" with device: "alsa_output.pci-0000_00_14.2.analog-stereo.monitor"
[vokoscreen] Find CaptureCard: "Audio Interno Estéreo Analógico" with device: "alsa_input.pci-0000_00_14.2.analog-stereo"
[vokoscreen] Find CaptureCard: "AK5370 I/F A/D Converter Mono Analógico" with device: "alsa_input.usb-AKM_AK5370-00-AK5370.analog-mono"
[vokoscreen] ---End search PulseAudio Capture Devices---

[vokoscreen] File VERSION available
